### ISSUE TITLE
After importing package, this happens

### ISSUE THREAD

**Issue by KusadaKusaba** [bdunderscore/modular-avatar#100]
Packages\nadena.dev.modular-avatar\Editor\Localization\Localization.cs(50,24): error CS0433: The type 'JsonConvert' exists in both 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' and 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'

**Comment by bdunderscore** [comment]
Interesting! Looks like you have two versions of Newtownsoft.Json installed in your project. I'll take a look to see if there's something I can do to address this.

**Comment by bdunderscore** [comment]
I suspect you may have a copy of newtonsoft json in your project assets. This is likely to break things - is it possible to delete it? Modular Avatar uses the unity package manager version, which is the recommended way to install this package.

**Comment by bdunderscore** [comment]
Also, please confirm which version of unity and VRCSDK you are using.

**Comment by KusadaKusaba** [comment]
After I manually updated NEWtonsoft Json to version 3.0.2, the error no longer exists.
Latest VRCSDK, Unity2019.4.31f1

**Comment by bdunderscore** [comment]
Did you install NEWtonsoft Json via UPM? Or some other method?

**Comment by KusadaKusaba** [comment]
UPM

**Comment by bdunderscore** [comment]
Hi, sorry for the late reply. Can you please check if you have a copy of the `Newtonsoft.Json.dll` file somewhere in Assets?
