### ISSUE TITLE
MA Scale Adjusterの影響でハンドルの座標系選択の適用が再選択後になっている+再選択すると動かなくなる

### ISSUE THREAD

**Issue by Sayamame-beans** [bdunderscore/modular-avatar#1003]
再選択すると座標系の変更が適用されるようです。
ただ、Unity側も含めて奇妙な気がするのでとりあえず列挙します。(Harmony Patchの影響かどうかみ確認のため)

MA: 1.10.0-beta.2
VRCSDK: 3.7.0-beta.1
Unity: 2022.3.22f1

### Global Normal Positioning Handle
![image](https://github.com/user-attachments/assets/16719054-9631-4549-8d71-8905df8c3a8a)

### Local Normal Positioning Handle
![image](https://github.com/user-attachments/assets/818b1409-a3c4-48f7-bd16-53dd4132aed7)

### Global Normal Scaling Handle
![image](https://github.com/user-attachments/assets/155cca64-d98f-448b-9ab1-7ebe4a94de95)

### Local Normal Scaling Handle
![image](https://github.com/user-attachments/assets/e731885f-92b2-40c6-8964-ea9568117c93)

### Global Scale Adjuster Handle (一旦他のオブジェクトを選択してからの再選択で向きが変わります)
![image](https://github.com/user-attachments/assets/4b8ffbf2-b580-478d-ad9f-7723ba0a4917)

### Local Scale Adjuster Handle (一旦他のオブジェクトを選択してからの再選択で向きが変わります)
![image](https://github.com/user-attachments/assets/a371d549-84e5-40c5-ad78-20c07781e0a4)

**Comment by Sayamame-beans** [comment]
これ、再選択で座標系が揃うのは良いんですけど、再選択前の状態じゃないと操作してScale Adjusterの値が変わっても描画上変化がないです(再選択前にそのまま動かすと動く(壊れますけど))

**Comment by Sayamame-beans** [comment]
アバター: https://mk22.booth.pm/items/1948102 v2
衣装: https://woodapple.booth.pm/items/3023946 公立

**Comment by bdunderscore** [comment]
このバグは1.9.13でも再現できますか？

**Comment by Sayamame-beans** [comment]
ハンドルの向きに関しては1.9.13でも同様ですね
ただ、再選択すると動かなくなる挙動は現状1.10.0-beta固有の現象に見えます(更なる検証が必要)

**Comment by Sayamame-beans** [comment]
Scalingハンドルの座標系について改善が見られました
現在は
- Scale Adjusterを付けるまではGlobalを選択していてもLocalの軸方向になっている(MAを抜いて再起動しても発生したためUnityのバグの可能性が高い?)
- Scale Adjusterを付けてから操作していない段階では異なるまま(ここは改善の余地がありそう)
- ハンドルに触れて動かすか、他のオブジェクトを選択して戻ってきた時は軸の方向が正常に適用される

という挙動になっているようです。
それ以外の部分は正常に動作していそうに見えます。(動かなくなる問題や、座標系選択後に即時反映されない問題は修正されています)
ご報告まで…
