### ISSUE TITLE
In some case, Move Independently and Scale Adjuster are completely broken

### ISSUE THREAD

**Issue by Sayamame-beans** [bdunderscore/modular-avatar#1004]
MA: 1.10.0-beta.2
VRCSDK: 3.7.0-beta.1
Unity: 2022.3.22f1

### Base (Setup Outfit済)
![image](https://github.com/user-attachments/assets/5a662e05-a502-493d-9a61-9d69137861e5)

### When use Move Independently for Upper Leg
![image](https://github.com/user-attachments/assets/2ceb0041-b4a3-4cb7-8296-23d6c9d8608a)

Then undo
![image](https://github.com/user-attachments/assets/fa2693fb-26bb-4756-a215-1c9b77092e9c)

### When use Scale Adjuster for Upper Leg
![image](https://github.com/user-attachments/assets/db90389b-dc02-492a-97f4-ef2d1f8f93e2)

Then undo
![image](https://github.com/user-attachments/assets/e1fea027-37f1-415b-bbfb-567b1745821a)

**Comment by Sayamame-beans** [comment]
Scale Adjusterについては、Merge Armature無しにそれ単体で付けた場合、ハンドルを動かしたり値を変えたりしても動いてなさそうです? (y軸だけ動くけど負の方向にいかなかったりしておかしい)
Move IndependentlyはMerge Armature無しでも動きます

**Comment by Sayamame-beans** [comment]
アバター: https://mk22.booth.pm/items/1948102 v2
衣装: https://woodapple.booth.pm/items/3023946 公立

**Comment by Sayamame-beans** [comment]
参考までに、Move IndependentlyをUpper Legにmove together: Lower Legで動かした場合のエラーログです。(前述の画像の状態はいずれもエラーありません)
[Move_Independently.txt](https://github.com/user-attachments/files/16601529/Move_Independently.txt)

**Comment by bdunderscore** [comment]
この辺は現在の `main` ブランチで直っていますか？

**Comment by Sayamame-beans** [comment]
1.10.0-rc.0でテストしたところ、直っていそうです。
