### ISSUE TITLE
Setup outfit heuristic fails when there are multiple direct children of the Armature

### ISSUE THREAD

**Issue by bdunderscore** [bdunderscore/modular-avatar#101]
Reported by: https://twitter.com/arare_o9

![image](https://user-images.githubusercontent.com/64174065/204194857-972159f4-51e8-4c3d-8ed2-c55e9901251f.png)

Setup outfit is disabled in this case due to armature having multiple direct children

**Comment by arare** [comment]
こちら対応してます
