### ISSUE TITLE
MA Merge Armatureの機能を用いたスケール調整後、Undoすると衣装のTransformが壊れる(Undoで元に戻らない)

### ISSUE THREAD

**Issue by Sayamame-beans** [bdunderscore/modular-avatar#1024]
#839 に近い類の現象かもしれません。
衣装をアバターに追加(この時点では位置等がズレている)し、Setup Outfitした後、MA Merge Armatureの機能で位置/スケールを調整します。
その後、Undoして元に戻そうとすると正常にUndoされません。
以前の現象と同様に、MA Merge Armatureの付与まで含めてUndoすると戻ります(戻ったように見えます)。

以前までの報告に記述していなかったのですが、アバタールートのScaleが(1, 1, 1)ではなく(0.92, 0.92, 0.92)でした。(配布されているprefabからしてScaleが1でないので、忘れていました)
これも要因の一端かもしれません。

アバター: https://mk22.booth.pm/items/1948102
衣装: 位置/スケールが異なる任意のもの?

Unity: 2022.3.22f1
MA: 1.10.0-beta.4

**Comment by bdunderscore** [comment]
最新mainブランチで再現できませんでした。

https://github.com/user-attachments/assets/70f5ede4-2913-4320-99c0-cde457d11020

再現手順としてはこれであってますか？

**Comment by Sayamame-beans** [comment]
合ってると思います
今回試した衣装は他のもの(2つ)だったので、後ほどもう少し確認してみますね

**Comment by Narazaka** [comment]
少なくともしばらく前（1.9系より前であるかどうかは不明）から起こっている類似事象について参考になるかもなので

MA Merge Armatureの機能を直接使わずに普通にTransformからスケールや位置等を調整した上で、Undoをするとなぜか中途半端な位置に戻る事象があります。その時点でprefabには変更あった表記になっているのでRevertをすると元に戻ります。

- いちおうMA Merge Armatureを付けているものに限定的であるかあまり定かでないです
  - 他で起こったケースは今のところないと記憶している
  - 起こるときと起こらないときがあると思います

**Comment by Sayamame-beans** [comment]
- bd_さんの動画と同じ衣装(PublicSchoolUniform)では再現しませんでした。
- ねこねこジャージ(あまとうさぎアバター向けVariantを使用)では再現しました。
- ゆめいろワンピース(ミルク向けVariantを使用)では再現しました。
- Re: セーラーロリ(あまとうさぎアバター向けVariantを使用)では再現しました。

壊れ方がアバターと衣装とのScale差等によって変動している気がします。
そのため、対応衣装であるPublicSchoolUniformでは(等倍変形なので)発生しなかったのかも…?

**Comment by bdunderscore** [comment]
ゆめいろワンピース(ミルク向けVariantを使用)で再現しました。たぶん、座標系の違いが原因かなと思います。
