### ISSUE TITLE
素体に付けたMA Scale Adjusterについて、Merge Armature対象のボーンについても同様にスケールしたい

### ISSUE THREAD

**Issue by Narazaka** [bdunderscore/modular-avatar#1027]
いわゆる素体スケール改変とかのために素体側にMA Scale Adjusterを付ける場合に於いて、衣装セットアップ時にいちいち素体側ボーンから設定をコピーしてこないと行けないのが面倒。

- Scale AdjusterにMerge Armatureでマージされる側をよしなにするオプションを追加する
- Merge ArmatureにMerge Targetの同位置にあるScale Adjusterをコピーする機能を追加する

いずれかなどがあると便利と思います。

（自分自身は旧来からのTransform直接でやってますが、素体スケール改変勢から聞いたので）

**Comment by autch** [comment]
#910 と重複かも

**Comment by bdunderscore** [comment]
重複のためクローズしますね。
