### ISSUE TITLE
Links of document do not work after specify step

### ISSUE THREAD

**Issue by cleantted** [bdunderscore/modular-avatar#103]
Links of [Modular Avatar](https://modular-avatar.nadena.dev/docs/intro) page and [Tutorials](https://modular-avatar.nadena.dev/docs/tutorials/) page do not work after specify step.

### Modular Avatar

- Access "Modular Avatar" document page from [URL](https://modular-avatar.nadena.dev/docs/intro)
  - or reload page (F5 or Ctrl + R)
- Then links ("Simple clothing setup", "Advanced clothing setup", "detailed reference documentation" and "page on prefab distribution") do not work

To recover this issue: clicking `Modular Avatar` from sidebar

note:
"Simple clothing setup" page's URL is `https://modular-avatar.nadena.dev/docs/tutorials/clothing/`.
But after reload page,  I click "Simple clothing setup" then access to `https://modular-avatar.nadena.dev/docs/intro/tutorials/clothing` (added `/intro/` ).

### Tutorials

- Access to [document top page](https://modular-avatar.nadena.dev/)
- Click "Tutorials" and access to "Tutorials" page
- Then links ("Configuring a simple outfit", "Configuring a complex (cloth) outfit" and "Toggle an object") do not work
 
To recover this issue: reloading page

note:
"Configring a simple outfit" page's URL is `https://modular-avatar.nadena.dev/docs/tutorials/clothing/`.
But before reload page, I click "Configring a simple outfit" then access to `https://modular-avatar.nadena.dev/docs/clothing/` (losted `/tutorials/`).

## Reproduction environment

- Firefox(64bit) 107.0
- Google Chrome(64bit) 107.0.5304.122

**Comment by bdunderscore** [comment]
This should be fixed now, thanks for the report!
