### ISSUE TITLE
AvatarObjectReference の referencePath が切れていることに気づきづらい

### ISSUE THREAD

**Issue by nekobako** [bdunderscore/modular-avatar#1037]
AvatarObjectReference に targetObject が設定されていればそちらが使われると思いますが、referencePath が targetObject のパスと一致していないとき、そのことが分かるようにするか自動で修正されるとよいと思いました。

1. AvatarObjectReference の Inspector で対象オブジェクトを設定する
2. 対象オブジェクトをリネームするか階層を移動する
3. AvatarObjectReference の Inspector では referencePath が古いままであることが分からない
4. AvatarObjectReference を含むオブジェクトをプレハブ化して再配置する
5. この時点で AvatarObjectReference の参照が切れ、referencePath が古いままだったことが分かる

**Comment by bdunderscore** [comment]
うーん、勝手にPrefab Overrideを作るのもなーという気持ちがあるけど、どうにかできないかなと模索してみたりします。

**Comment by nekobako** [comment]
たしかにそうですね・・
自動で修正はせず再リンクのためのボタンが表示されるぐらいが丸いかもしれません。
(パスと参照の両方を持っているという説明が必要になるかもしれませんが…)

もしくは、

- AvatarObjectReference を含むオブジェクトが Prefab の一部ではない
- AvatarObjectReference を含むオブジェクトが現在編集中の Prefab の一部である
- AvatarObjectReference を含むオブジェクトが現在編集中ではない Prefab の一部であり、既に Override されている

の場合は自動で修正してもよいかも…？

**Comment by bdunderscore** [comment]
そうかもですね。今週末ObjectChangeEventStreamで移動を感知し、必要であれば修正するなど実験する予定です
