### ISSUE TITLE
[FEATURE] Add to Ignore Transforms if BoneProxy target is under PhysBone

### ISSUE THREAD

**Issue by anatawa12** [bdunderscore/modular-avatar#104]
アクセサリをBoneProxyで追加する際、TargetがPhysBoneは以下の場合にIgnoreTransformにアクセサリを手動で追加しなければなりません。また、Editor状態ではPhysBone配下ではないためPhysBoneが意図したように動かないことに気づくことができません。

Ignore Transformsに追加するのを自動化できないでしょうか。

**Comment by bdunderscore** [comment]
たしかにこれはあったほうが良さそうですね
