### ISSUE TITLE
MA Parameters に VRCExpressionParameter を設定したい (VRCExpressionMenuが編集できないので)

### ISSUE THREAD

**Issue by whiteflare** [bdunderscore/modular-avatar#1048]
MA Parameters の先頭に、VRCExpressionParameter の設定フィールドを追加してほしいです。

![0339d89f6c17ab98a936deca1a69dfee](https://github.com/user-attachments/assets/b7e39325-7d80-48e7-9cf7-0cc50d0e8b6c)

理由としては VRCSDK 3.7.0 において VRCExpressionMenu Editor が変更されたことが挙げられます。
新しい Menu Editor では、Parameter に設定のない項目の value を編集できなくなりました。

![image](https://github.com/user-attachments/assets/98545cae-43f3-4957-9b54-90628859ebfb)

編集フローとしては次の流れを考えています。
1. VRCExpressionParameter を作成
2. VRCExpressionMenu を作成
3. MA Parameters に 1 で作成した Parameter を設定
4. MA Menu Installer あるいは MA Menu Item に 2 で作成した Menu を設定

現在は 3 のみ実現できていません。4は実現できます。
MA Parameters に Parameter を設定できるようにすれば、Menu 側の設定方法とも調和するので良いのではと思います。

**Comment by whiteflare** [comment]
Animatorのみ変数をどうするかについては検討できていません。(VRCExpressionParameterに追加せずVRCExpressionMenuを編集する方法はMAの如何の前に実現できなくなってしまったので)
もしかしたらcannyあるかもしれないですが自分は未発見です。

いちおうInspectorをdebugにすれば値を指定することもできますが。

関連するissueはこちらです。当時は「今までのアセットを使いまわしたい」という意図だったと思いますが、VRCSDKが変わってしまったので重要度はより高まったのではと考えています。
https://github.com/bdunderscore/modular-avatar/issues/880

**Comment by bdunderscore** [comment]
クロスプラットフォーム対応を次に取り掛かる予定である以上、VRCSDKの型への依存から離れたいですね…MA Menu Itemへの意向を推奨します。

それはそうと、VRCSDKへのバグ報告やharmonyパッチを検討します

**Comment by whiteflare** [comment]
MA Menu Item ってパラメータまで生やすんでしたっけ！？
それならそっちのほうがずっと簡単ですね。
MA MenuItem のプッシュが足りていないのかもしれないです。みんな MA Parameters + MA MenuInstaller を使っていて、MA MenuItem は殆ど使われていない気がします。
MA Parameters + MA MenuInstaller から MA MenuItem への変換をサポートして、前者は非推奨にしてしまうのが良いのではと思っています。

**Comment by bdunderscore** [comment]
実はMenu Installerにすでに変換機能がありまして・・・

![image](https://github.com/user-attachments/assets/5caa2744-1744-4623-9703-77cf6c2810cd)

MA ParametersはMIの自動パラメーター作成より多機能なのでそっちは用途に合わせてって感じ。

**Comment by bdunderscore** [comment]
https://feedback.vrchat.com/sdk-bug-reports/p/370-regression-its-no-longer-possible-to-edit-expression-menus-without-defining VRCSDKにバグ報告を出してみました。

動き次第では何かパッチを充てるかも（できれば避けたいけど）

**Comment by bdunderscore** [comment]
既存機能で迂回できるのでクローズさせていただきます
