### ISSUE TITLE
MA Proxy Renderer for "object name"としてアバター内の全てのSkinned MeshがScene内に生成される

### ISSUE THREAD

**Issue by egist-forr** [bdunderscore/modular-avatar#1055]
例えばPrefabの編集モードに入ったり戻ったりするタイミングで該当Prefab内に存在するSkinned Meshの全て（のように見える）がMA Proxy Renderer for "object name"という名前で意図に反して作成されます。(Scene上、マテリアルエラー状態のSkinned Meshが表示されます)
エラーメッセージもコンソールに出力されていてMA ScaleAdjusterの処理中のように見えます。
アバターはprefab variantの多重で運用していて、[1 元prefab]→[2 沢山の衣装を投入したprefab]→[3 全体scaleやMA ScaleAdjusterで調整したprefab]→[4 アップロードするための衣装だけにしたprefab]のようにしていて、3では素体Amatureの他にEditor Onlyにしている衣装のAmatureへもMA ScaleAdjusterを適用しています。

![image](https://github.com/user-attachments/assets/3208ab39-607c-493f-a040-a1a1cb7ab5fa)

エラーメッセージ内容
ArgumentException: An element with the same key but a different value already exists. Key: 'Kikyo_Blouse (UnityEngine.SkinnedMeshRenderer)'
System.Collections.Immutable.ImmutableDictionary`2+HashBucket[TKey,TValue].Add (TKey key, TValue value, System.Collections.Generic.IEqualityComparer`1[T] keyOnlyComparer, System.Collections.Generic.IEqualityComparer`1[T] valueComparer, System.Collections.Immutable.ImmutableDictionary`2+KeyCollisionBehavior[TKey,TValue] behavior, System.Collections.Immutable.ImmutableDictionary`2+OperationResult[TKey,TValue]& result) (at <85bee8cbddb7458fb7e9ff936e888708>:0)
System.Collections.Immutable.ImmutableDictionary`2[TKey,TValue].Add (TKey key, TValue value, System.Collections.Immutable.ImmutableDictionary`2+KeyCollisionBehavior[TKey,TValue] behavior, System.Collections.Immutable.ImmutableDictionary`2+MutationInput[TKey,TValue] origin) (at <85bee8cbddb7458fb7e9ff936e888708>:0)
System.Collections.Immutable.ImmutableDictionary`2+Builder[TKey,TValue].Add (TKey key, TValue value) (at <85bee8cbddb7458fb7e9ff936e888708>:0)
nadena.dev.modular_avatar.core.ProxyManager.BuildRenderers () (at ./Packages/nadena.dev.modular-avatar/Runtime/ScaleAdjuster/ProxyManager.cs:167)
nadena.dev.modular_avatar.core.ProxyManager.OnPreCull (UnityEngine.Camera camera) (at ./Packages/nadena.dev.modular-avatar/Runtime/ScaleAdjuster/ProxyManager.cs:269)
UnityEngine.Camera.FireOnPreCull (UnityEngine.Camera cam) (at <b41119cc6741409ea29f63c7f98de938>:0)

**Comment by bdunderscore** [comment]
1.10.0-rc.1で改善されると思いますのでご確認ください。
https://modular-avatar.nadena.dev/dev/ja/docs/intro#%E3%83%86%E3%82%B9%E3%83%88%E7%89%88

**Comment by egist-forr** [comment]
ありがとうございます。1.10.0-rc.1はまだ未リリースになりますよね？
リリースされ次第確認いたします。
![image](https://github.com/user-attachments/assets/de997147-5ba1-416f-9101-6432d5a678b6)

**Comment by bdunderscore** [comment]
あ、rc.0でもOKです（バージョン番号を間違えてました）

**Comment by bdunderscore** [comment]
ふーむ・・・シーンのどこかにアバターの子にAvatar Descriptorがあったりしますか？
また、シーンを切り分けて、一部のアバターだけで1.10で固まる現象は再現できますか？

**Comment by egist-forr** [comment]
ありがとうございます。お手数おかけして申し訳ありません。
以下調査結果を記載します。

・[1] アバターの子にAvatar Descriptorはありません。
　（3アバターのキメラを行っていますがAvatar Descriptorは削除済み）

・[2] 1sceneに1アバターだけにしたsceneのみLoadした状態で、1.10.0-rc.0(+1.5.0-rc.1)で起動。
　→sceneのtreeを開くのにダイアログが出ている時間は数分ありましたが
　　openされました。コンソールにエラーは出ませんでした。
　→prefabの編集モードに入ろうとするところでまた数分ダイアログが表示されましたが編集モードには入れました。
　→sceneに2アバターにすると固まりました。CPU使用率・メモリ使用量は変動を見せていました。
　　タスクマネージャからUnityキルし再立ち上げすると、sceneにアバターが1つだけの状態(追加した分はsceneにsaveされなかった？)。
　→再度アバターを配置しようとするとダイアログが出たまま終わらない状態になりました。
　※1.10.0-rc.1もリリースされているようでしたが1.10.0-rc.0を使っています。

![image](https://github.com/user-attachments/assets/2d0a0c26-6bbf-45b4-ad9a-3d70da9df0b1)



以下はついでの確認になりますが…
・[3] 1sceneに1アバターだけにして該当sceneのみLoad。1.9.15(+1.4.1)の状態。
　→同じエラーは発生しませんが、MA ScaleAdjusterにてエラーは発生しました。

![image](https://github.com/user-attachments/assets/7f1ca281-3e25-4fff-86bc-101c415c3ae6)

MissingReferenceException: The object of type 'SkinnedMeshRenderer' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
nadena.dev.modular_avatar.core.ProxyManager.ClearStates () (at ./Packages/nadena.dev.modular-avatar/Runtime/ScaleAdjuster/ProxyManager.cs:352)
nadena.dev.modular_avatar.core.ProxyManager.OnPreCull (UnityEngine.Camera camera) (at ./Packages/nadena.dev.modular-avatar/Runtime/ScaleAdjuster/ProxyManager.cs:272)
UnityEngine.Camera.FireOnPreCull (UnityEngine.Camera cam) (at <b41119cc6741409ea29f63c7f98de938>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

・[4] 3の状態から元sceneをLoad。
　→再度MA Proxy Renderer for xxxが大量に作成されました。

![image](https://github.com/user-attachments/assets/c9eaf6b2-984d-4a15-9917-be3d6343d12d)

**Comment by bdunderscore** [comment]
```
　→sceneのtreeを開くのにダイアログが出ている時間は数分ありましたが
　　openされました。コンソールにエラーは出ませんでした。
```

この過程のprofilerトレースを取っていただけたら助かります。やり方：
1. Window -> analysis -> profiler を開く
2. Preferencesを開く
![image](https://github.com/user-attachments/assets/886303bd-a3ff-4e86-a2be-a251a2910c5f)
3. Frame Countを多めに設定（９００以上）
4. Play ModeのところをEdit Modeに変更
5. 激重操作を行う
6. 動き出したら即座にRECボタンを押して停止（Frame Countでこの猶予が決まります）
7. 右上のフロッピーアイコンを押して保存
8. 保存したファイルを添付してください。

**Comment by egist-forr** [comment]
本日実施したところsceneのtreeを開く瞬間は一瞬で終わってしまったため他の重い動作のtraceを取ってみましたが…こちらで参考になりますでしょうか？

・openPrefabMode.data：prefabモードに入る時。数分程度でした。
・putAdditionalAvatar.data：sceneに2つめのアバターを配置するとき。30分～？

[openPrefabModeAnd.zip](https://github.com/user-attachments/files/16824270/openPrefabModeAnd.zip)

**Comment by bdunderscore** [comment]
うーん・・・Profilerを見た限り、100msを超えるタイミングがないっぽい？RECモードを外すのが間に合わなかったのかな・・・？

**Comment by bdunderscore** [comment]
おそらく間に合ってないと思いますので、自動的にRECモードを外す機能を作ってみました。実験的な機能につき、手動導入してください。

1. プロジェクト内の `Packages/nadena.dev.ndmf/Editor/UI/Menus.cs` を[こちらのファイル](https://github.com/bdunderscore/ndmf/raw/654b0ecfd0b950d0dcdaff7e90dc46422b182eba/Editor/UI/Menus.cs)で置き換えてください
2. `Tools -> NDM Framework -> Debug Tools -> Arm frametime profiler` を押してください。プロファイルウィンドウが自動的に開いてRECモードに入ります
3. 重い操作を行う（５秒以上止まったらプロファイルを自動停止します）
4. 保存して添付してください

**Comment by egist-forr** [comment]
そういう仕様だったのですね…理解できてませんでした。お手数おかけしてすいません。

・20240901_openSceneTree.data：sceneのtreeを開くとき(sceneの左の三角をクリック)
ダイアログにApplication.UpdateScene - Waiting for Unity's code to finish executing. - が出て3分～？程かかった。

・20240901_openPrefabMode.data：prefabモードに入るとき(sceneに配置したアバターprefabの右側の矢印をクリック)
ダイアログにUnitySynchronization.ExecuteTasks  - Waiting for Unity's code to finish executing. - が出て4？分～程度？

・20240901_putAdditionalAvatar.data：sceneに2つめのアバターを配置。
ダイアログは出ませんが5？分～程度？
profilerが自動で止まった後もマウスがファイルをドラッグしてドロップする前のマウスにアイコンが追従してくる状態でwindowを触れない状態が数分。
467Mありzip圧縮しても80M。下記Googleドライブリンクにアップロードしています'(どこかのタイミングで消します。)

[20240901_openPrefabModeAnd.zip](https://github.com/user-attachments/files/16827069/20240901_openPrefabModeAnd.zip)

https://drive.google.com/file/d/1eDqUHLv5T2IBy4oA2yjy4zI21kzywyYP/view?usp=sharing

**Comment by bdunderscore** [comment]
![image](https://github.com/user-attachments/assets/5953ef4d-6c78-43a5-acc0-bd9d5b54339f)
![image](https://github.com/user-attachments/assets/344f87ef-9cb2-4f83-9ee6-398c6a6763a8)

同じオブジェクトを繰り返し処理してるんですね・・・原因はわかったので更新します。

**Comment by bdunderscore** [comment]
https://github.com/bdunderscore/modular-avatar/releases/tag/1.10.0-rc.2 で修正をしてみました。もう一度ご確認お願いします 🙏

**Comment by egist-forr** [comment]
ありがとうございます。同じ問題は出なくなっているように見えます。
しかしコンソールに下記のエラーが何百など表示されます。

NullReferenceException: Object reference not set to an instance of an object
nadena.dev.ndmf.preview.ProxyPipeline+<>c__DisplayClass22_0.<Build>b__3 (UnityEngine.Renderer r) (at ./Packages/nadena.dev.ndmf/Editor/PreviewSystem/Rendering/ProxyPipeline.cs:184)
System.Linq.Enumerable+SelectIListIterator`2[TSource,TResult].MoveNext () (at <de4a1a1490a74771a34fee0d1d586658>:0)
System.Threading.Tasks.Task.WhenAll[TResult] (System.Collections.Generic.IEnumerable`1[T] tasks) (at <eef08f56e2e042f1b3027eca477293d9>:0)
nadena.dev.ndmf.preview.ProxyPipeline.Build (nadena.dev.ndmf.preview.ProxyObjectCache proxyCache, System.Collections.Generic.IEnumerable`1[T] filters, nadena.dev.ndmf.preview.ProxyPipeline priorPipeline) (at ./Packages/nadena.dev.ndmf/Editor/PreviewSystem/Rendering/ProxyPipeline.cs:202)
Rethrow as AggregateException: One or more errors occurred. (Object reference not set to an instance of an object)
UnityEngine.Debug:LogException(Exception)
nadena.dev.ndmf.preview.ProxyPipeline:ShowError() (at ./Packages/nadena.dev.ndmf/Editor/PreviewSystem/Rendering/ProxyPipeline.cs:314)
nadena.dev.ndmf.preview.ProxySession:OnPreCull(Boolean) (at ./Packages/nadena.dev.ndmf/Editor/PreviewSystem/Rendering/ProxySession.cs:82)
nadena.dev.ndmf.preview.PreviewSession:OnPreCull(Boolean) (at ./Packages/nadena.dev.ndmf/Editor/PreviewSystem/PreviewSession.cs:51)
nadena.dev.ndmf.preview.ProxyManager:OnPreCull(Camera) (at ./Packages/nadena.dev.ndmf/Editor/PreviewSystem/ProxyManager.cs:61)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

またPrefabモードに入ると最初処理が終わって触り始められそうにはなりますが、
それからすぐ何か触ったわけでもないタイミングでダイアログ「UnitySynchronization.ExecuteTasks」が表示され
30分待っても終わらない状態となりました。
prefabモードに入って出る時でも同じような状態となったのを確認しています。
どのタイミングで発生するかわからず、またダイアログが終了したところは確認できておらず、Unityをキルして立ち上げなおしてとしてるため、profilerは取れていないです。

私の環境でのみ起きている問題のようですし(?)、予想が付かないようであれば一旦切り捨てるか、優先度を下げていただいて問題ないです。

**Comment by bdunderscore** [comment]
実はこのやり取りでバグを発見しまくってるので助かってます・・・！
次のrcで何かしらの安全装置（？）を入れて固まらないようにします。

**Comment by egist-forr** [comment]
対処がリリース済みかどうかわかりませんが1.10.0-rc.4では下記NullReferenceExceptionが大量(1348件)に出力されましたので情報として。
※行番号は多少違いますが、同じ箇所？

NullReferenceException: Object reference not set to an instance of an object
nadena.dev.ndmf.preview.ProxyPipeline+<>c__DisplayClass22_0.<Build>b__3 (UnityEngine.Renderer r) (at ./Packages/nadena.dev.ndmf/Editor/PreviewSystem/Rendering/ProxyPipeline.cs:187)
System.Linq.Enumerable+SelectIListIterator`2[TSource,TResult].MoveNext () (at <de4a1a1490a74771a34fee0d1d586658>:0)
System.Threading.Tasks.Task.WhenAll[TResult] (System.Collections.Generic.IEnumerable`1[T] tasks) (at <eef08f56e2e042f1b3027eca477293d9>:0)
nadena.dev.ndmf.preview.ProxyPipeline.Build (nadena.dev.ndmf.preview.ProxyObjectCache proxyCache, System.Collections.Generic.IEnumerable`1[T] filters, nadena.dev.ndmf.preview.ProxyPipeline priorPipeline) (at ./Packages/nadena.dev.ndmf/Editor/PreviewSystem/Rendering/ProxyPipeline.cs:205)
Rethrow as AggregateException: One or more errors occurred. (Object reference not set to an instance of an object)
UnityEngine.Debug:LogException(Exception)
nadena.dev.ndmf.preview.ProxyPipeline:ShowError() (at ./Packages/nadena.dev.ndmf/Editor/PreviewSystem/Rendering/ProxyPipeline.cs:341)
nadena.dev.ndmf.preview.ProxySession:OnPreCull(Boolean) (at ./Packages/nadena.dev.ndmf/Editor/PreviewSystem/Rendering/ProxySession.cs:82)
nadena.dev.ndmf.preview.PreviewSession:OnPreCull(Boolean) (at ./Packages/nadena.dev.ndmf/Editor/PreviewSystem/PreviewSession.cs:51)
nadena.dev.ndmf.preview.ProxyManager:OnPreCull(Camera) (at ./Packages/nadena.dev.ndmf/Editor/PreviewSystem/ProxyManager.cs:61)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by bdunderscore** [comment]
次RCに原因特定のためのデバッグログを追加します。

**Comment by bdunderscore** [comment]
先ほど出した1.10.0-rc.5で、`Renderer deleted during proxy pipeline construction` みたいなログ出ていますか？

**Comment by egist-forr** [comment]
同ログはありませんでしたが、下記のスタックトレースが出ていました。
Application.UpdateSceneのダイアログがずっと出たままになる事象や、NullReferenceExceptionが大量にでる事象などUnity作業に支障がでる問題は
解消いたしました。

![image](https://github.com/user-attachments/assets/703f4596-7548-41d2-8f9b-73e9bb19ac84)

[nadena.dev.modular_avatar.core.editor.ScaleAdjusterPreview] Duplicate renderer Yukata Bag (UnityEngine.SkinnedMeshRenderer) in groups: nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject], nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject], nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject], nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject], nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject], nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject], nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject], nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject], nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject], nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject], nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject], nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject], nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject], nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject], nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject], nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject], nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject], nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject], nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject], nadena.dev.ndmf.preview.RenderGroup`1[UnityEngine.GameObject]
UnityEngine.Debug:LogError (object)
nadena.dev.ndmf.preview.TargetSet:.ctor (System.Collections.Immutable.ImmutableList`1<nadena.dev.ndmf.preview.IRenderFilter>) (at ./Packages/nadena.dev.ndmf/Editor/PreviewSystem/Rendering/TargetSet.cs:59)
nadena.dev.ndmf.preview.TargetSet:Refresh (System.Collections.Immutable.ImmutableList`1<nadena.dev.ndmf.preview.IRenderFilter>) (at ./Packages/nadena.dev.ndmf/Editor/PreviewSystem/Rendering/TargetSet.cs:87)
nadena.dev.ndmf.preview.ProxyPipeline/<Build>d__22:MoveNext () (at ./Packages/nadena.dev.ndmf/Editor/PreviewSystem/Rendering/ProxyPipeline.cs:121)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start<nadena.dev.ndmf.preview.ProxyPipeline/<Build>d__22> (nadena.dev.ndmf.preview.ProxyPipeline/<Build>d__22&)
nadena.dev.ndmf.preview.ProxyPipeline:Build (nadena.dev.ndmf.preview.ProxyObjectCache,System.Collections.Generic.IEnumerable`1<nadena.dev.ndmf.preview.IRenderFilter>,nadena.dev.ndmf.preview.ProxyPipeline)
nadena.dev.ndmf.preview.ProxyPipeline/<>c__DisplayClass21_0:<.ctor>b__0 (object) (at ./Packages/nadena.dev.ndmf/Editor/PreviewSystem/Rendering/ProxyPipeline.cs:99)
UnityEngine.UnitySynchronizationContext:ExecuteTasks ()

**Comment by bdunderscore** [comment]
Yukata Bag の親オブジェクトに、Avatar Descriptorのある階層が複数あったりしませんか？

**Comment by egist-forr** [comment]
ありがとうございます。
確認しましたがAvatar Descriptorはありませんでした。
yukata bagの親＆yukata bagでcomponentが付いているのはスクショの4つで、それより上はアバタールートになります。
アバタールートはAnimator,Avatar Descriptor,Pipeline Managerのほかには
Light Limit Changer For MA 1.14.0を付与しています。

![image](https://github.com/user-attachments/assets/e8a1350f-44f9-45ea-bc43-71749424cba7)

**Comment by bdunderscore** [comment]
間違えてクローズしたので再オープン。先ほどリリースした 1.10.0-rc.6 で直っている（かもしれない）ので、確認のほどよろしくお願いします。

**Comment by egist-forr** [comment]
発生しなくなりました。ありがとうございました！

**Comment by bdunderscore** [comment]
デバッグに協力してくださってありがとうございます！
