### ISSUE TITLE
Menu Item のパラメーター名が設定されていると一部設定が操作できなくなる

### ISSUE THREAD

**Issue by nekobako** [bdunderscore/modular-avatar#1079]
https://github.com/bdunderscore/modular-avatar/issues/994#issuecomment-2286900029 の

> * MA Parameters なし
>   
>   * MA Menu Item (パラメーター名: Hoge, パラメーター値: 0)
>   * MA Menu Item (パラメーター名: Hoge, パラメーター値: 1)
>   * MA Menu Item (パラメーター名: Hoge, パラメーター値: 2)
> 
> という構成にしたとき、
> 
> * すべての MA Menu Item の「初期設定にする」のシリアライズされた値が false であれば、いずれかの MA Menu Item の「初期設定にする」にチェックを入れることができますが、いずれかの MA Menu Item の「初期設定にする」のシリアライズされた値が true であれば、すべての MA Menu Item の「初期設定にする」のチェックボックスが操作できなくなります。
>   ただし、複数選択した場合には操作できるようになります。
> * すべての MA Menu Item の「同期する」のシリアライズされた値がどうなっていても、すべての MA Menu Item の「同期する」のチェックボックスが操作できなくなります。
>   ただし、複数選択した場合には操作できるようになります。
> 
> 期待する挙動は操作できなくならないことです。(多分…)

について、きちんと修正確認ができていませんでした。
複数選択時の挙動が修正されたのは確認できていますが、MA Parameters なしで複数の MA Menu Item に同じ「パラメーター名」が設定されているとき、「初期設定にする」や「同期する」が操作できなくなる場合がある問題についてはそのままになっているようです。

伝わりづらいかと思うので動画を撮って起きている内容を書き起こしました。

https://github.com/user-attachments/assets/c36884d6-ec29-44ff-a1dc-d505e6d2e77b

- 0:00 - 0:04 | `Menu` オブジェクトに `Menu Installer` と `Menu Group` が、`Cloth` オブジェクトに `Menu Item (Sub Menu)` がアタッチされています
- 0:05 - 0:24 | `Blue`、`Pink`、`Yellow` オブジェクトに「パラメーター名」が同じで「パラメーター値」が異なる `Menu Item (Toggle)` がアタッチされており、それらすべての `IsDefault` は `False` になっています
- 0:25 - 0:40 | すべての `Menu Item (Toggle)` の「初期設定にする」は操作できます (正常)
- 0:41 - 0:50 | いずれかの `Menu Item (Toggle)` の「初期設定にする」を操作し、`IsDefault` が `True` になっていることを確認して Inspector を閉じます
- 0:51 - 1:09 | すべての `Menu Item (Toggle)` の「初期設定にする」は操作できません (異常)
- 1:10 - 1:26 | `IsDefault` が `True` になっている `Menu Item (Toggle)` の「パラメーター名」を削除し、「初期設定にする」を操作し、「パラメーター名」を戻し、`IsDefault` が `False` になっていることを確認して Inspector を閉じます
- 1:27 - 1:45 | すべての `Menu Item (Toggle)` の「初期設定にする」は操作できます (正常)

**Comment by bdunderscore** [comment]
うーん、こちらの環境では再現できませんでした。

異常状態のプレハブを用意できますか？

**Comment by nekobako** [comment]
こちらです！ [1079.zip](https://github.com/user-attachments/files/16841774/1079.zip)
プレハブ 1079 を開くかシーンに配置すると、Menu/A オブジェクト、Menu/B オブジェクト、Menu/C オブジェクトにアタッチされている Menu Item の「初期設定にする」と「同期する」が操作できない状態になっています。

下記のパッケージのみを追加した新規プロジェクトにインポートして再現することを確認しています。

- VRChat SDK - Avatars 3.7.0
- VRChat SDK - Base 3.7.0
- Av3Emulator 3.4.5
- Modular Avatar 1.10.0-rc.2
- Non-Destructive Modular Framework 1.5.0-rc.3

**Comment by bdunderscore** [comment]
再現できました。ありがとうございます！
