### ISSUE TITLE
MA Shape Changer を設定すると Scene 上からのメッシュ選択の挙動が不自然になる

### ISSUE THREAD

**Issue by Not-uNya2** [bdunderscore/modular-avatar#1084]
Modular Avatar 1.10.0-rc.2 にて、衣装に MA Shape Changer で体のブレンドシェイプ適用を設定した後に体のメッシュをScene上からダブルクリックして選択しようとすると、選択を即解除するような挙動が起こるのですが、仕様でしょうか？ ( ただ、 Hierarchy から直接選択した場合は自動で選択解除されないようです。)

**Comment by bdunderscore** [comment]
https://github.com/bdunderscore/ndmf/issues/357 と重複（暫定的修正が次のNDMFバージョンに入ります）

**Comment by Not-uNya2** [comment]
重複失礼しました。了解です。
もう一つお聞きしたいのですが、MA Shape Changer の設定はそのままで一旦無効にしたい時に、コンポーネントのチェックを外しても有効になり続けてしまうようです。一旦無効にする方法はありますか？

**Comment by bdunderscore** [comment]
どこのチェックのことでしょうか？
GameObjectのチェックなら、反映されてないとバグですので、別イッシューとして詳細をお願いします。
なお、今日この後もろもろ更新をかける予定なので、そのあと再確認をお願いします。

**Comment by bdunderscore** [comment]
もともとのイッシューはMA 1.10.0-rc.3, NDMF 1.5.0-rc.4で修正。
なお、いったん無効にできない問題については、 https://github.com/bdunderscore/modular-avatar/pull/1078 に該当するかもしれない。その場合は 1.10.0-rc.3 で修正しているはずですので、再確認の上でまだ問題だったら改めてイッシュー立てるようお願いいたします。
