### ISSUE TITLE
リアクションデバッグツールを操作していると徐々に処理が重くなる

### ISSUE THREAD

**Issue by nekobako** [bdunderscore/modular-avatar#1100]
リアクションデバッグツールを操作していると徐々に処理が重くなっていき、長いプログレスバーが表示されるようになります。

再現手順です。
1. [#1079 の再現プレハブ](https://github.com/bdunderscore/modular-avatar/issues/1079#issuecomment-2325381173) をシーンに配置する
2. B のリアクションデバッグツールを開く
3. 「MenuItem の選択状態をオーバーライド」の「+」と「-」を繰り返しクリックする

https://github.com/user-attachments/assets/b6dd46f4-815b-4f03-8b2f-fabe4fc2f8a9

**Comment by bdunderscore** [comment]
わぁ・・・
![image](https://github.com/user-attachments/assets/fb6d9bbc-f1ab-46a2-b8cc-3aa2ba24d467)
