### ISSUE TITLE
1.10.0-rc.4: NDMFプラグインでの生成したVRCExpressionMenuがPlay時に正常に動作するが、アップロード時・Manual Bake時に誤ったパラメーター値が入る

### ISSUE THREAD

**Issue by Narazaka** [bdunderscore/modular-avatar#1109]
プラグインでメニューの生成をしているAvatar Menu Creatorの選択式(Choose)メニューにおいて、Play時には正常に動作するにもかかわらず、アップロード時・Manual Bake時には生成したメニューに誤った値が入ります。
https://x.com/hotatech/status/1831654714301411424

たとえばメニューとしてparameterに`[0,1,2,3,4,5,6]`を入れて生成したが、Manual Bakeするとそこに`[1,2,4,5,6,7,8]`が入っているといった具合です。（0と3が抜けて、その後の番号がプラスされて埋められている状態です。）

このメニューはMA Menu Itemで親メニューを作り子のVRCExpressionMenuを参照する方法、あるいは親メニューのVRCExpressionMenu自体をMA Menu Installerで参照したものどちらでも起こります。
https://github.com/Narazaka/AvatarMenuCreaterForMA/blob/60c34b6d92015ec202d361a6460a3f6cb6a6b2c6/Editor/CreatedAssets.cs#L70-L84

各メニュー生成の当該コード（ログを仕込んだ） https://github.com/Narazaka/AvatarMenuCreaterForMA/blob/60c34b6d92015ec202d361a6460a3f6cb6a6b2c6/Editor/CreateAvatarChooseMenu.cs#L266-L301
![image](https://github.com/user-attachments/assets/4bab04f0-1d9a-453b-8e40-d84dcd1a67d4)
Manual Bake時のログ（Purpleにはvalue=0が入る事が分かる）
![image](https://github.com/user-attachments/assets/85bbe560-37e6-4489-8aa6-64fe0f5f0f71)
Manual Bakeされたメニューアセット（Purpleにはvalue=1が入っている）
![image](https://github.com/user-attachments/assets/cee2a9d9-14af-49be-8166-69fa74da92ab)

ちょっとどういうところで壊れるか分からず検証手段が分からないので、個別NDMFプラグイン依存ですがこのままissueとして立てます。

なお同様の構成をNDMF pluginによる生成ではなく事前生成した上でMenu Installerで導入するとこの問題は発生しません。
![image](https://github.com/user-attachments/assets/5073a7cf-73e7-49db-8b16-738cb6dc1991)

**Comment by kb10uy** [comment]
Manual bake で試した限りでは 1.10.0.rc-3 では発生してなさそうです

**Comment by nekobako** [comment]
プレイモードでなければ MenuItem の Reset() が呼ばれて automaticValue が true になるのが原因かなと思っています。
帰ったらちゃんと確認してみます。

**Comment by bdunderscore** [comment]
あー　UIから作成した時のみ初期設定を変える、なんてことできないかな…

**Comment by nekobako** [comment]
手元でできたっぽいのがあるので pullreq 送ります！

**Comment by bdunderscore** [comment]
旅行に出てて対応できないので助かります！
