### ISSUE TITLE
BUG: MA menu item can break avatar build (from code remnants)

### ISSUE THREAD

**Issue by Rei-57645** [bdunderscore/modular-avatar#1127]
Unity 2022 seems to leave its trash from deleted and changed object in YAML files of the scene / prefabs.
If you used a parameter inside a "MA Menu Item" component, now change to another parameter and delete the original param from your ava (or not genegrate it anymore with the params object) then the build will break and VRC SDK will complain, that the old parameter was added to an expression menu even though it does not exist on the avatar.

In this case, you are not able to fix the "MA Menu Item" component, but you have to remove it and create it new - using the exact same settings. Now the avatar builds again, even though, you made no visible changes

**Comment by bdunderscore** [comment]
Is this still an issue with the latest test build?
https://modular-avatar.nadena.dev/dev/docs/intro#prerelease-versions
