### ISSUE TITLE
`1.10.0-rc.2`以上のバージョンでUnity Sceneのオブジェクトを変更すると、Update Sceneウィンドウがなくならない

### ISSUE THREAD

**Issue by noridev** [bdunderscore/modular-avatar#1129]
タイトルと同じです。
1.10.0-rc.2以上にアップデートすると、問題が発生しています。

一般的なオブジェクトのON/OFFなどの動作にはすぐに反応しますが、アバターのON/OFFをすると、下のようなウィンドウが表示され、いくら待っても消えません。

![image](https://github.com/user-attachments/assets/3b38ac96-dfa3-46e7-ba21-942fdc642ee9)

そのため、バージョンだけアップデートしてアップロードしようとしても、このウィンドウがずっと消えないため、アップロードも不可能な状態です。

最初はndmfの関数を呼び出した後、問題が発生してndmfの問題だと思いましたが、ndmfだけModular Avatar `1.10.0-rc.4`に対応する`1.5.0-rc.5`にアップデートした時には問題が生じませんでした。

アバターに服や頭などがたくさん入っているほど、発生確率が高くなるようです。
何も入れていないアバターのPrefabを取り出すと問題ありませんが、何か入ったアバターは発生周期がだんだん長くなり、オブジェクトが非常に多く入っているアバター(EditorOnlyを含む)では問題が発生します。

よろしければこの問題を確認していただけますか？

**Comment by bdunderscore** [comment]
> 何か入ったアバターは発生周期がだんだん長くなり

これは、UpdateSceneウィンドウは出るけどしばらく待てば消える場合があるということですか？
完全に固まってる状態で何が起きてるかを調べるにはデバッガーを使う必用があるのですが、もし「重い！」という感じだけならデータがとりやすいです。こちらのコメントにご参照ください。

https://github.com/bdunderscore/modular-avatar/issues/1055#issuecomment-2322646824

**Comment by bdunderscore** [comment]
こちらの環境で再現できました。

**Comment by bdunderscore** [comment]
1.10.0-rc.5 で直っているはずですが、もしまだ発生するようでしたら報告をお願いします。
