### ISSUE TITLE
When using"MA Merge Animator" and setting the Path Mode to "Relative to this object," you cannot modify the "Source Path" of the "VRC Animator Play Audio" to be a relative path.

### ISSUE THREAD

**Issue by NONAME-2121237** [bdunderscore/modular-avatar#1138]
When using"MA Merge Animator" and setting the Path Mode to "Relative to this object," you cannot modify the "Source Path" of the "VRC Animator Play Audio" to be a relative path.
![image](https://github.com/user-attachments/assets/a5edb274-3f5f-40b3-9b5a-a573926a56a5)

**Comment by bdunderscore** [comment]
Have you tested with 1.10.0-rc.4?

**Comment by bdunderscore** [comment]
https://github.com/bdunderscore/modular-avatar/issues/935 リリース待ちです。もう少しお待ちください・・・
