### ISSUE TITLE
Reactive Components が生成する State から Exit への Transition が多い

### ISSUE THREAD

**Issue by nekobako** [bdunderscore/modular-avatar#1160]
同じパラメーターを参照する Reactive Components が複数あるとき、AnimatorController の Layer に複数の State が生成されますが、それらの State から Exit への Transition に不要なものがあるように思います。

例としてパラメーター値 1、2、3 が設定された Menu Item と Reactive Components があるとき、

- `Entry`
  - Default Entry Transition --> `<default>`
  - X > 0.995 && X < 1.005 --> `State 1`
  - X > 1.995 && X < 2.005 --> `State 2`
  - X > 2.995 && X < 3.005 --> `State 3`
- `<default>`
  - X > 0.995 && X < 1.005 --> `Exit`
  - X > 1.995 && X < 2.005 --> `Exit`
  - X > 2.995 && X < 3.005 --> `Exit`
- `State 1`
  - X < 0.995 --> `Exit`
  - X > 1.005 --> `Exit`
  - X > 1.995 && X < 2.005 --> `Exit` (不要)
  - X > 2.995 && X < 3.005 --> `Exit` (不要)
- `State 2`
  - X < 1.995 --> `Exit`
  - X > 2.005 --> `Exit`
  - X > 2.995 && X < 3.005 --> `Exit` (不要)
- `State 3`
  - X < 2.995 --> `Exit`
  - X > 3.005 --> `Exit`

となっています。

**Comment by bdunderscore** [comment]
RCのアニメーター構造は「とりあえずリリースしたい」という感じの実装で、今後BlendTree主体に変えたいと考えています。トランジションの負荷は比較的に少ないらしいのでこの辺の無駄を減らすのは優先度が低いが、PRがあるなら（仕事のあとで）見ます
