### ISSUE TITLE
1.10.0-rc.5で特定のGameObjectを選択するとEditor.Unknown.OnInspectorGUIが発生しInspectorが操作できなくなる

### ISSUE THREAD

**Issue by kxn4t** [bdunderscore/modular-avatar#1165]
## 事象
1.10.0-rc.5で特定のGameObjectを選択するとEditor.Unknown.OnInspectorGUIが発生しInspectorが操作できなくなる（動作が異常に重くなる）

- 発生するGameObject
  - MA Menu Itemを複数子に持つSub MenuのGameobject

例として、このようなExtract Menuで展開したもので、「MANUKA_costume」「MANUKA_option」を選択すると発生
![image](https://github.com/user-attachments/assets/ab140b16-ae52-4049-a005-fd2573e3c800)

## 備考
ちょっとよくわからないのですが、切り分けた結果を記載しておきます…。

- 1.9.16から1.10.0-rc.5にアップデートすると発生するようになった
- **[PVLController](https://pogapoganyaa.booth.pm/items/5245784)がアバター内に存在する場合に発生する**
- 自分のPCの場合、子のMenu Itemが5個以上になると異常に重くなりInspectorの操作ができない状態になる
  - パラメータ値が設定されている場合のみ重く、設定されていない場合は軽い

**Comment by ReinaS-64892** [comment]
適当に試したら症状再現したから Profiler で調べたら ParameterInfo.ForUI.GetParameterRemappingsAt が重たいっぽくて、一時的に外したらまともなパフォーマンスになるようですね...パラメーターが設定されていない場合に軽いというのとも合致しそうですね！

https://github.com/bdunderscore/modular-avatar/blob/3648348184bad2e304b031766293eda4fa616ca4/Editor/Inspector/Menu/MenuItemGUI.cs#L630-L633
