### ISSUE TITLE
SkinnedMeshRendererをオンオフするとScaleAdjusterのプレビューが止まる

### ISSUE THREAD

**Issue by Rerigferl** [bdunderscore/modular-avatar#1177]
アバター内にある何らかのSMRのアクティブ状態を変えるたびにプレビューが動いたり止まったりする感じです

**Comment by bdunderscore** [comment]
NDMF 1.5.0-rc.7でも再現可能ですか？

**Comment by Rerigferl** [comment]
1.5.0-rc.7で再現しました。rc.8に上げてみたら再現しなかったので大丈夫そうですかね・・・？

**Comment by Rerigferl** [comment]
NDMF 1.5.0-rc.8でも同様に再現しました・・・

**Comment by bdunderscore** [comment]
rc.9にこれっぽいバグを修正したので再確認お願いします 🙏

**Comment by Rerigferl** [comment]
確認してみましたがまだ発生しますね・・・
一応動画撮ってみたので添付しておきます

https://github.com/user-attachments/assets/306bb7af-3685-4cee-aec4-848809ecc6de

**Comment by bdunderscore** [comment]
再現できました（操作されるRendererがトグルされていると勘違いしてました）
