### ISSUE TITLE
[1.10.0-rc.7] リアクティブコンポーネントを利用するとアニメーションを破壊する場合がある

### ISSUE THREAD

**Issue by meronmks** [bdunderscore/modular-avatar#1199]
[しなのちゃん](https://booth.pm/ja/items/6106863) で事象を確認。

この子は配布されているPrefabの状態でExメニューより目のエフェクト（キラキラとかぐるぐる目とか）の表示非表示を制御できるようになっているのですが、
リアクティブコンポーネント（確認したのは[Object Toggle](https://modular-avatar.nadena.dev/dev/ja/docs/reference/reaction/object-toggle)と[Shape Changer](https://modular-avatar.nadena.dev/dev/ja/docs/reference/reaction/shape-changer)ですがおそらく[Material Setter](https://modular-avatar.nadena.dev/dev/ja/docs/reference/reaction/material-setter)でも再現すると思われます）を利用しているとこのメニューの機能を破壊し、ONにはできるがOFFにしてもエフェクトが消えなくなってしまうようです。

Write DefaultsがONのAnimatorなのでもしかしたらWrite DefaultsがONの場合に発生するバグかもしれません。

**Comment by bdunderscore** [comment]
WD ONに依存するアバターでWD OFFのステートを生成しているのが原因っぽいので、Match WD Stateみたいな挙動にいったん変えます（1.11当たりで全部BTで再実装する予定です）

**Comment by meronmks** [comment]
1.10.0-rc.8で修正を確認できました。念のため報告まで
