### ISSUE TITLE
リアクションデバッグツールが反応しなくなる

### ISSUE THREAD

**Issue by nekobako** [bdunderscore/modular-avatar#1201]
リアクションデバッグを操作していると反応しなくなることがあります。
Repaint が行われていないだけ (マウスカーソルをシーンビューに移動すると切り替わる) の場合と、そもそもプレビュー内容が変化していない (マウスカーソルをシーンビューに移動しても切り替わらない) 場合の両方がありそうです。

- Repaint が行われていないだけの場合

https://github.com/user-attachments/assets/304c305b-e5f7-4e53-8899-02cae77eff65

- プレビュー内容が変化していない場合

https://github.com/user-attachments/assets/15aa5bca-389b-4b78-8a1f-afa0b522ccd2

再現シーンです。
[ROSim.zip](https://github.com/user-attachments/files/17105995/ROSim.zip)

NDMF: main (ebb523d) / MA: main (fd3de6e)

**Comment by nekobako** [comment]
最新の NDMF f0a6980 / MA b866628 で確認しましたところ、Repaint が行われない問題は発生しなくなっていましたが、プレビュー内容が変化しない問題はまだ発生しているようでした。

https://github.com/user-attachments/assets/4448f6e6-76d5-48cd-9d05-eafe1cf5ced6

**Comment by bdunderscore** [comment]
確認できました。ComputeContext内部のレースコンディションだった模様です（デバッグ機能制作込みで５時間ぐらいかかった 🫠 ）

**Comment by nekobako** [comment]
修正されていることを確認しました！ありがとうございます。
