### ISSUE TITLE
Update document related to 1.10.0 changes (e.g. Set Or Inherit mode)

### ISSUE THREAD

**Issue by Sayamame-beans** [bdunderscore/modular-avatar#1207]
幾らか更新が抜けていそうな気がしました

**Comment by bdunderscore** [comment]
ほかに気づいたところを具体的に教えてくれると助かります（Set Or Inheritは更新します）

**Comment by Sayamame-beans** [comment]
用語のズレ(ブレンドシェープ → ブレンドシェイプ や 翻訳前の文章が書かれているなど)はありますが…思ったより大丈夫そうですね
あ、でも https://github.com/bdunderscore/modular-avatar/pull/961 は明確に忘れられてますね。Android不可って書いたままになっています。
related: https://github.com/bdunderscore/modular-avatar/issues/784#issuecomment-2367428748 
https://crowdin.com/editor/modular-avatar/42/enus-ja?view=comfortable&filter=basic&value=0#q=android
類似でいうと、World FixedはConstraint利用ですが、3.7.0以降ではVRCConstraintがあるので動くはずです。その点は(処理も含め)大丈夫ですか?
