### ISSUE TITLE
Merge Animator - Exclusive Option

### ISSUE THREAD

**Issue by Spokeek** [bdunderscore/modular-avatar#1217]
This is a request from issues i have with the GoGoLoco project. https://www.gogoloco.net

It is based on the use of dedicated animators for Base, Action and Sitting layers, but will break if any other animator is merged are present.

As a feature request, i would see a "Exclusive" option to add on the "Merge Animator" component that would merge the animator, but ensure that the component is the only one that can merge (and will remove any in the base configuration).

We could warn the user of the impact and if we detect multiple exclusive components targeting a specific layer, we can raise an error in the NDMF error pannel.

A partial option is the use of Haï Prefabulous component with "Blank FX Animator" https://docs.hai-vr.dev/docs/products/prefabulous/vrchat/blank-fx-animator but that only works for specific layers, and i believe that could be a good thing to MA.as a

**Comment by Sayamame-beans** [comment]
maybe duplicate of #330

**Comment by Spokeek** [comment]
Agreed.
