### ISSUE TITLE
[1.10.0-rc.9] MA Object toggleで初期状態でオブジェクトをオンかつパラメータがTrueとなるようにした場合動作しない

### ISSUE THREAD

**Issue by kxn4t** [bdunderscore/modular-avatar#1221]
![image](https://github.com/user-attachments/assets/e8c1ece4-429b-40af-b6c3-97b00f6716b0)

パラメータをTrueにすることでオブジェクトをオフにする方向はうまく切り替わりますが、
このように初期状態でオブジェクトをオンかつパラメータがTrueとなるように組んだ時、オブジェクトのオンオフが切り替わらないようです。

初期状態でオブジェクトを表示、かつトグルがオンになっていて、トグルをオフにするとオブジェクトが非表示になるように組めると嬉しいです。

**Comment by nekobako** [comment]
「条件を反転」をオンにして、その下のオブジェクトの横のチェックボックスを外すとできます…！
![image](https://github.com/user-attachments/assets/eeafba87-eba1-4232-976b-fb1e40505041)

**Comment by kxn4t** [comment]
出来ました！！ありがとうございます！！

ただ、ドキュメントを読んでなぜそうなるかは理解できるのですが、先の画像のようにチェックを入れても動くのが自然な気がしました…。

**Comment by nekobako** [comment]
私も初め全く同じことをやったので少し分かりづらい気はしますね…。

オブジェクト設定欄のチェックボックスは「条件を満たしたときにオブジェクトをどういう状態にするか」の設定で、「初期状態でオンのオブジェクトをオンにしても何も起こらない」ということなのだと思いますが、仕様としてそれで合っているのであれば UI をもう少し分かりやすくしたいところです。

**Comment by nekobako** [comment]
> 先の画像のようにチェックを入れても動くのが自然な気がしました…。

Object Toggle に関しては操作対象が表示/非表示の 2 状態しかないため、

- 初期状態でオブジェクトが表示
- Menu Item の「初期設定にする」のチェックボックスがオン
- Object Toggle のオブジェクト設定欄のチェックボックスがオン
- → 初期状態でメニューがオンかつオブジェクトが表示
- → メニューをオフにしたらオブジェクトが非表示になってほしい

という気持ちは分かるのですが、たとえば Material Setter で同じことを考えたとき、

- 初期状態でマテリアルが Mat_A
- Menu Item の「初期設定にする」のチェックボックスがオン
- Material Setter の「変更先のマテリアル」が Mat_A
- → 初期状態でメニューがオンかつマテリアルが Mat_A
- → メニューをオフにしたらマテリアルが…？

となってしまうように思います。

**Comment by kxn4t** [comment]
説明ありがとうございます！
なるほど…リアクティブコンポーネント全体を通した設計なんですね。
そこがあまりよくわかっていなかったのでObject Toggle目線で考えてしまっていました。

> オブジェクト設定欄のチェックボックスは「条件を満たしたときにオブジェクトをどういう状態にするか」の設定で、「初期状態でオンのオブジェクトをオンにしても何も起こらない」ということなのだと思いますが、仕様としてそれで合っているのであれば UI をもう少し分かりやすくしたいところです。

そうですね、ちょっとすぐには咀嚼できない感じがあるので何かしらわかりやすくなると助かる人は多いかなと思います。
自分みたいな人は山程出てきそう…。

**Comment by nekobako** [comment]
あくまで私の考えなので、実際のところは bd_ さんの回答待ちということで・・！

**Comment by bdunderscore** [comment]
マージしました 👍

**Comment by bdunderscore** [comment]
実際のバグではなく、UIの問題で対処済みなのでクローズします。
