### ISSUE TITLE
Inspectorから表示したPrefabのMA Menu Itemの表示が崩れる

### ISSUE THREAD

**Issue by kesera2** [bdunderscore/modular-avatar#1255]
## 概要
MA Menu Itemが付与されているGameObjectをプレハブ化すると一部条件でプレハブを選択したときのInspectorの表示が乱れるようです。Inspecotrの枠の幅を変えても乱れています。
![image](https://github.com/user-attachments/assets/4868d79a-a36c-4e59-9e11-e4afea6af1a3)
![image](https://github.com/user-attachments/assets/53d79480-fd95-4d8c-9154-5b8cbf0ac0cf)

## 環境
- 2022.3.22f1
- VRChat SDK - Avatars/Base 3.7.1
- Non-Destructive Modular Framework 1.5.0
- Modular Avatar 1.10.0

## ファイル
再現したunitypackageをzipにしましたので参考にいただければと思います。
Assets/Modular Avatar 不具合報告/Parent.prefabが問題の対象です。
[MAでプレハブのInspectorの表示が乱れる.zip](https://github.com/user-attachments/files/17250540/MA.Inspector.zip)

## 再現手順
1. MA Menu GroupをGameObject(MA Object)に追加
2. SubMenu(Parent) > Toggle(Child)のメニューを作る
3. 2で作ったメニューにアイコンを設定する
4.  Toggle(Child)パラメーター名に値を設定する（ここが原因？）
5. GameObject(MA Object)ではなくSubMenu(Parent)の方をプレハブ化する
6. ProjectからプレハブをInspectorで確認すると表示が乱れる

なお、パラメーターを設定しない場合、正しく表示されていました。
![image](https://github.com/user-attachments/assets/4900f368-8879-4960-8ce8-5ce73c3a1806)

特殊なユースケースなのですが、念の為報告させていただきました！

**Comment by bdunderscore** [comment]
1.10.1で似たようなバグを修正してますが、更新したら直りますか？

**Comment by kesera2** [comment]
@bdunderscore 
ありがとうございます、1.10.1に更新したら治りました！1.10.0で既知の不具合だったんですね...お手数おかけしました><
![image](https://github.com/user-attachments/assets/d951e134-afd7-4531-b73e-a6c25e229733)
