### ISSUE TITLE
docs: strange "button group" on top page header

### ISSUE THREAD

**Issue by Tsukina-7mochi** [bdunderscore/modular-avatar#1260]
## Oveview

A class `button-group` is set on the group of buttons on header "ダウンロード (VCC 経由)", "説明書" and "チュートリアル." However there are still `gap`s between buttons, so the look is strange. The link to discord below also has `button-group` class which seems not to be necessary.

| PC | mobile |
| --- | --- |
| ![header-pc](https://github.com/user-attachments/assets/27bc4d65-beb5-404c-88fb-bfd2547d36ca) |![header-mobile](https://github.com/user-attachments/assets/9d8b6d1a-9dca-47b1-8152-9c436a9386cf) |

## Suggested Action

Just remove `button-group` classes and set some margins (same as before):

| PC | mobile |
| --- | --- |
| ![header-pc-no-group](https://github.com/user-attachments/assets/2df2c5b0-6807-43c1-a680-23a69ea488bd) | ![header-mobile-no-group](https://github.com/user-attachments/assets/81de75ef-721e-494c-991b-8b8b04821d34) |

or narrow (or remove) `gap`s between buttons:

| PC | mobile|
| --- | --- |
| ![header-pc-group](https://github.com/user-attachments/assets/ce84322e-c78f-4fec-a03d-16d3b9fb4deb) | ![header-mobile-group](https://github.com/user-attachments/assets/8ea7a1a1-597d-4b4c-ab5c-929523012b74) |

 I think the former looks nice.

**Comment by Tsukina-7mochi** [comment]
I can make PR.

**Comment by bdunderscore** [comment]
Sure, please feel free to submit a PR
