### ISSUE TITLE
Unity上でShoulderにRotation Constraintを使用すると追従しますが、VRChat上では追従しません

### ISSUE THREAD

**Issue by kaguyahao** [bdunderscore/modular-avatar#1261]
Modular Avatarを使用させていただき、Shoulderのみが服に追従しなかったため(体全身は追従する)、Rotation Constraintを服側に導入し、そこにアバターのShoulderをそれぞれ入れ、有効にしてみました。するとUnity上でShoulderの部分が体に服は追従するのですが、VRChatでアップロードすると追従しない状態になってしまいます。ボーン名も揃えてみましたがダメでした。解決策ありましたらよろしくお願いします。

**Comment by bdunderscore** [comment]
アバターに右クリックし、Modular Avatar -> Manual Bake Avatarを選択すれば、ビルド後の状態を確認できます。
そのうえで、処理前と処理後のConstraintの設定と周辺ヒエラルキーを見せてください。

**Comment by kaguyahao** [comment]
処理前
![01_L](https://github.com/user-attachments/assets/e4c2b486-2784-4765-834d-bc6d16677a66)
![02_L](https://github.com/user-attachments/assets/420fdeb1-b8ca-403a-b592-8aef2b87bbe0)
処理後
![01_R](https://github.com/user-attachments/assets/e2a37305-b531-4703-b438-973b61f2cd44)
![02_R](https://github.com/user-attachments/assets/435dd0d8-dafb-4724-9440-53f6188cd858)

**Comment by kaguyahao** [comment]
処理前
![03_L](https://github.com/user-attachments/assets/6348bd61-e864-4dcb-93d7-fb3080ca6f5a)
![01_L](https://github.com/user-attachments/assets/7d9bb924-709a-4ef7-9100-6e10bdac516d)
処理後
![04_2](https://github.com/user-attachments/assets/13e102df-1d8f-4c04-b290-a5a061681ed8)
![04](https://github.com/user-attachments/assets/318ebd20-7978-4caa-a575-fe5e8f04b2ad)

**Comment by bdunderscore** [comment]
処理前の画像では、SourcesがNoneになっていますが、どのような意図でその設定をしていますか？

それで、この衣装の問題ですが、アバター側にUpperChestが設定されているが、衣装側にUpperChestがないのが問題かと思います。この状態はウェイトペイントまで調整しないと根本的な対応が難しいので自動対応はないのですが、VRChatでのみ使うなら、RotationConstraintではなく、Merge ArmatureをShoulder_L、Neck、Shoulder_Rにつけて、それぞれアバター素体の該当ボーンに割り当てるとある程度追従すると思います。

**Comment by kaguyahao** [comment]
解決しました。ありがとうございました。
