### ISSUE TITLE
Animation編集を切り替える際にObjectChangeEventsのHoldOnが発生する

### ISSUE THREAD

**Issue by clay8201** [bdunderscore/modular-avatar#1279]
ModularAvator1.9.16から1.10.3へアップデートした後、
UnityでAnimationを編集(play)した後、Animationを切り替えるとObjectChangeEventsのHoldOnが20秒ほど発生します

![image](https://github.com/user-attachments/assets/8e289daa-167a-4728-a1c1-954ea08b3969)
![image](https://github.com/user-attachments/assets/33470808-f01b-4e89-9185-3726da9652f1)

1.9.16のプロジェクトでは発生しませんでした

**Comment by bdunderscore** [comment]
再現できませんでした。プロファイルを取っていただけると助かります。手順としては

①　Ctrl-7でプロファイルウィンドウを開く
②　右上の、？マークの→の「⋮」からPreferencesを開く
③　Frame Countを900ぐらいにする
④　左上のPlay ModeをEdit Modeに変更（いろいろと流れ始めます）
⑤　重たい操作を行う
⑥　即座にRECボタンを押して記録停止（すぐ流れてしまうので）

そのあと、右上？マークの左のセーブアイコンでプロファイルデータを保存して、アップしてください。

**Comment by clay8201** [comment]
ご確認ありがとうございます
[20241013-02.zip](https://github.com/user-attachments/files/17352562/20241013-02.zip)

**Comment by bdunderscore** [comment]
情報ありがとうございました！NDM Framework 1.5.5で対策を入れてみましたので、再確認お願いいたします 🙏

**Comment by clay8201** [comment]
ご対応ありがとうございます
NDM Framework 1.5.5で確認したところ、ObjectChangeEventsのHoldOnウィンドウは表示されず、待ち時間も解消しました。
迅速なご対応ありがとうございます

**Comment by bdunderscore** [comment]
確認ありがとうございます！
