### ISSUE TITLE
Scale Adjuster not previewing in Game view until play mode is active

### ISSUE THREAD

**Issue by CrestSapphire** [bdunderscore/modular-avatar#1286]
I used to be able to preview changes from scale adjuster in game view without entering play mode, however it won't preview outside of play mode.
(I posted this issue earlier today and it for some reason got deleted)

**Comment by Tliks** [comment]
Your issue has been moved to NDMF.
https://github.com/bdunderscore/ndmf/issues/449

**Comment by bdunderscore** [comment]
Issue was moved as it's an issue with NDMF, not Modular Avatar per se. I should be able to get to it in the next NDMF release, I think. Closing as duplicate.
