### ISSUE TITLE
MA Menu Installer "Extract menu to objects" creates an empty object that causes an empty menu

### ISSUE THREAD

**Issue by inkuxuan** [bdunderscore/modular-avatar#1297]
Steps:
1. Create an empty object and add MA Menu Installer
2. D&D a simple menu into "Menu to Install"

![Snipaste_2024-10-19_16-25-48](https://github.com/user-attachments/assets/4955c905-6278-4c80-ad58-0908d1301a91)
![Snipaste_2024-10-19_16-25-52](https://github.com/user-attachments/assets/aa9ed09e-6c17-4d0a-9f0c-fb9b15f9b069)

3. "Extract menu to objects"

It creates a strange hirarchy that contains an empty "Menu" object that causes the menu to not appear in avatar expression menu.

![Snipaste_2024-10-19_16-26-23](https://github.com/user-attachments/assets/46979284-0053-4d2e-ad49-e9d0bbbf7d09)
![Snipaste_2024-10-19_16-26-01](https://github.com/user-attachments/assets/fca88af6-893b-47cb-b058-455b4e7ad6ad)

**Comment by bdunderscore** [comment]
The creation of the sub-object is intentional; this is to avoid polluting the hierarchy if you extract menu on an object with lots of items but which already has child objects. However, there is a bug here; the menu group needs to specify this child object.
