### ISSUE TITLE
Update Mesh Settings JP documentation

### ISSUE THREAD

**Issue by bdunderscore** [bdunderscore/modular-avatar#1314]
> Mesh Settingsのドキュメントページの Mesh Settingsの手動設定 の項にて実際には
> "親で指定されている時は継承、それ以外では設定"
> と表示されている部分が、ページ内では
> "親が継承された時は継承、または設定"
> となっています。

**Comment by Uttu209** [comment]
修正なのですが、

> 親が継承された時は継承…

の部分がまだ修正されていないようです。
正しくは

> 親で指定されているときは継承…

となっているはずです。

**Comment by bdunderscore** [comment]
https://modular-avatar.nadena.dev/dev/ja/docs/reference/mesh-settings 開発版ドキュメンテーションはこちらです。次のリリースを出すと自動的に通常版が更新されます。

**Comment by Uttu209** [comment]
すでに上で言ってる通りで繰り返しになりますが、まだ修正しきれていません。

> ***親で指定されている時は継承***、それ以外では設定

が正しいです。
強調している箇所を再度ご確認お願いします。
