### ISSUE TITLE
Switching scenes breaks MA Merge Armature

### ISSUE THREAD

**Issue by IlexisTheMadcat** [bdunderscore/modular-avatar#1316]
For as long as I've used modular avatar, I've encountered a bug that's annoyed me. When I switch scenes in Unity, all MA Merge Armature components in my scene (i.e. avatar) break or reset themselves. When they break, they're still set to lock, but they don't track the target armature, even when re-locked. When they reset themselves (primarily from pre-1.10.4), they become unlocked and it's a bit of a gamble whether they work or not after locking. 
A possible solution would be to fully initialize MA Merge Armature components on scene load, since before 1.10.4 I had to lock them manually, but now I _have_ to either restart unity or reimport Modular Avatar to fix the issue if I'm lucky.

**Comment by IlexisTheMadcat** [comment]
Part of the proposed initialization process could be to unlock locked mergers, then relock them. This shouldn't apply to ones that are unlocked.

**Comment by IlexisTheMadcat** [comment]
Also, another change I'd love to see with the MA Merge Armature component is the ability to edit multiple of them at once. Sometimes I have the objects as children of an organizer object, as shown, other times I search `modularavatarmergearmature` to fix them.
![image](https://github.com/user-attachments/assets/1fe3d8ec-c8a9-4aa6-8bb8-3491cdf1ce5f)

**Comment by bdunderscore** [comment]
Hi! I tried to reproduce the issue on my test project, but didn't have this issue. Can you please confirm:

1. What version of Modular Avatar are you running?
2. Does this happen in a scene with only one avatar and outfit? Or does there need to be multiple avatars?
3. Are there any errors on the console when you are changing scenes?

**Comment by IlexisTheMadcat** [comment]
1. I am using latest, 1.10.5
2. My scenes are usually with just one avatar and some number of armature mergers, I don't put more than one. I do use one project for all my avatars and addons, but just one scene per.
3. Upon starting Unity and trying to recreate it myself, I couldn't cause it to happen. I wasn't getting any errors.
It seems like one of those bugs that happens in the background, which I also get is annoying, but it seems only related to the initializing of the armature merge component, as all I have to do is re-lock the armature and it works again. Often times background bugs are caused by unreliable code blocks, which can be hard to find until you notice it and think "hey there's a better way to do this". I get that a lot. I think the armature merger could use some more debug strings though, it'll probably help. But yeah sorry to return negative...

**Comment by bdunderscore** [comment]
Have you reproed this with 1.10.x at any point? There were a bunch of changes put in to try to improve these issues in the 1.10.0 release...

**Comment by IlexisTheMadcat** [comment]
I know it was an issue pre 1.10.4, the issue was prominent when switching scenes and some of the merge armatures would be set to Not Locked despite having been locked before
and when I'd go into them and lock them they'd set themselves back to Not Locked. The remedy was to just restart unity and some would actually go back to locked as it should be, or still be in Not Locked but I could actually change it this time.

**Comment by IlexisTheMadcat** [comment]
and even pre 1.10.4 it was occasional for the most part, although I had encountered it several times

**Comment by bdunderscore** [comment]
To clarify: Is it happening with 1.10.4?

**Comment by bdunderscore** [comment]
Or 1.10.5?

**Comment by IlexisTheMadcat** [comment]
When I made the issue it was 1.10.5
