### ISSUE TITLE
Always Add Mesh Settings in Setup Outfit

### ISSUE THREAD

**Issue by Tliks** [bdunderscore/modular-avatar#1318]
タイトル通りです。
現在Setup Outfitを実行した際、認識に間違いがなければ親にMesh Settingsが存在する場合はMesh Settingsを追加しない動作になっていると把握していますが、1.10.0で「親で指定された場合は継承、それ以外では設定」モードが追加されデフォルトとなったため、親のMesh Settingsの有無に関わらず追加して良いように思います。恩恵が得られるケースは限定的ですが、親の効果をオーバーライドしなくなった以上、逆に追加しない理由もないように感じます。

**Comment by anatawa12** [comment]
衣装作者が設定済として出す際のセットアップの際にSetup Outfitする際についてたほうが手順が減って嬉しい例はありそうですね

**Comment by Tliks** [comment]
確かに親にMesh Settingsがついているアバターで衣装製作者がSetup Outfitした場合、そのままだと配布物についてないという話はありますね
あとは何らかの理由で親からMesh Settingsが消えた場合やMesh Settingsがついていないアバターに移動させた場合でも統一できるとかですかね…
