### ISSUE TITLE
MA Menu Item w/Auto Value broken if bool is true by default

### ISSUE THREAD

**Issue by ZenithVal** [bdunderscore/modular-avatar#1331]
![image](https://github.com/user-attachments/assets/e252360d-610c-4227-912c-df79e3a98ef3)

![image](https://github.com/user-attachments/assets/a8dff961-c3c7-4cca-bb76-1337767fae1b)

The generated menu will have an unusable bool toggle with a value of `2` instead of `1`.

![image](https://github.com/user-attachments/assets/743afb7f-6fda-4555-856d-8c381dfb9598)

**Comment by nekobako** [comment]
Related: #1158
