### ISSUE TITLE
1.10.6 causes long or indefinite play mode load times

### ISSUE THREAD

**Issue by IlexisTheMadcat** [bdunderscore/modular-avatar#1332]
I upgraded to 1.10.6 but when going to test my posing system I experienced wait times that frankly I didn't want to wait on because it was much longer than it was before. With my current build, it takes about 2 minutes to enter play mode in 1.10.5, but in 1.10.6 that figure reached over 15 minutes. I wasn't able to recover any debugs, but maybe something was stuck in a loop?

**Comment by bdunderscore** [comment]
Do you experience longer build times, or only play mode load times?
Are you using Avatar 3.0 emulator, Gesture Manager, both, or neither? Does disabling them avoid the long delay?

**Comment by IlexisTheMadcat** [comment]
I haven't tried building, and I use GestureManager for my testing. I always thought that entering play mode counted as building the avatar, but I might be wrong.

**Comment by bdunderscore** [comment]
There are some slight differences that might be relevant. Can you please check on those questions? They help narrow down where the problem might be.
