### ISSUE TITLE
MAMIによりパラメータ型不整合が発生する

### ISSUE THREAD

**Issue by UnisakiStudio** [bdunderscore/modular-avatar#1335]
可愛い座りポーズツールにて、不具合が発生しています。
ギミック側で用意したInt型のExpressionParameterがあり、これを使用するAnimationStateのTransitionのConditionsをスクリプトで生成しています。
```
            InPhase(BuildPhase.Transforming)
                .AfterPlugin("nadena.dev.modular-avatar")
```
このフェーズにてVRCAvatarDescriptorのbaseAnimationLayersのAnimLayerType.BaseのAnimationControllerに対して、transitionを追加しています。

ParameterAssignerPassにてModularAvatarMenuItemを精査して、存在するパラメータをFXにFloat型で追加するためのMergeAnimatorをアバターに追加する処理がVer.1.10.6より追加されています。
https://github.com/bdunderscore/modular-avatar/commit/07b648dcc1256ed490356e2e4cebe976555f98ba

さらに、AnimatorCombinerのMergeTypesでは、各AnimatorControllerで同名パラメータの型が同じでない場合、Floatに変更する処理が行われています。

そのあとで、ギミックで直接AnimatorControllerに追加しているパラメータはInt型で、追加しているtransitionもIntとBool型でしか使えない「AnimatorConditionMode.Equals」を使っています。

そうすると、Float型のパラメータに「AnimatorConditionMode.Equals」を使おうとしたことにより、AnimatorControllerのStateのTransitionが正しく動作しなくなり、ギミックに不具合が発生します。

https://github.com/bdunderscore/modular-avatar/commit/07b648dcc1256ed490356e2e4cebe976555f98ba
この処理の目的を汲めていないので、的外れな指摘かもしれませんが、
ModularAvatarMenuItemに使われているパラメータをFXレイヤーのAnimatorControllerにFloat型固定で流し込むのは、その後の処理でそのパラメータがすべてFloatとしてAnimatorControllerに設定されてしまうため、問題を多く発生させかねないのではないかと思っています。
せめて、ExpressionParametersに登録してある型を参照して、FXに設定するパラメータの型を決めるなどした方が良いかと思います。

**Comment by UnisakiStudio** [comment]
現象の再現を行えるソースコードを準備します

**Comment by bdunderscore** [comment]
この変更はShape ChangerなどのRCと非RCアニメーターが同じパラメーターを使うときの衝突を回避するための変更ですが、影響範囲が広すぎた可能性がありますね。調整を入れます。

とはいえ、同じMenu Itemで複数のギミックが操作される場合はfloat型になっていることに対応してないとやっぱり壊れるので、基本的にfloat型を使うことをお勧めします。

なお、この手の問題を回避するためのアニメーター統合ＡＰＩを用意している最中です。たぶん、次のＮＤＭＦに入るかと思います。

**Comment by UnisakiStudio** [comment]
念のため、再現のためのソースコードです。
プロジェクトに追加の上、アバターの適当なMeshRendererに「UnisakiParameterBug」コンポーネントをつけると、
ExpressionsMenuに、そのオブジェクトをオンオフするためのItemが追加されます。
ですが、EqualsがFloat型に使われるため正しく遷移せずに、表示できなくなります。
https://gist.github.com/UnisakiStudio/ee7144df2b4b44923ca2d441011b799a
