### ISSUE TITLE
MA Bone Proxy オブジェに Skinned Mesh Renderer がある場合、親オブジェの Active がビルド時に無視される

### ISSUE THREAD

**Issue by inkuxuan** [bdunderscore/modular-avatar#1339]
再現ステップ：

1. アバターにこんな構造のオブジェクトを作る
```
.
└── Avatar
    ├── Bodyなど...
    └── Accessories
        ├── Hand Nails (Inactive)
        │   ├── LThumb Nail (MA Bone Proxy & Skinned Mesh Renderer)
        │   ├── LIndex Nail (MA Bone Proxy & Skinned Mesh Renderer)
        │   ├── LMiddle Nail (MA Bone Proxy & Skinned Mesh Renderer)
        │   └── ...
        └── Foot Nails
            └── ...
```
2. Hand Nails (Inactive) を無効化させる
3. Gesture Managerか、Av3Emulator で Playすると、アバターがビルドされ、Hand Nails直下の全部のオブジェが有効化されている

これは想定された挙動でしょうか？

Version情報：
com.vrchat.base 3.7.1
com.vrchat.avatars 3.7.1
vrchat.blackstartx.gesture-manager 3.9.2
nadena.dev.modular-avatar 1.10.7
nadena.dev.ndmf 1.5.6

**Comment by anatawa12** [comment]
今となってはなんか怪しい動作であることは確実ですが、v1.0.0の時点でこの動作だった記憶がありますね。

**Comment by bdunderscore** [comment]
v1.0.0からの仕様ですね…変えたら互換性的に大変なことになりそうなので、Object Toggleで対応することをお勧めします
