### ISSUE TITLE
VirtualLens2のUnsynced parameterをMA Parametersで追加するとSynced parameterになってしまう

### ISSUE THREAD

**Issue by shirasu256** [bdunderscore/modular-avatar#1342]
Non-Destructive SetupでセットアップしたVirtual Lens2のUnsynced parameter( `VirtualLens2 Enable` や `VirtualLens2 Zoom` など)を、MA ParametersでType: Animator Only、つまりUnsynced parameterとして追加しようとした場合、ビルド後にそれらのパラメータがなぜかUnsyncedではなくSynced parameterとして登録され、Expression Parametersのbit数を意図せず消費してしまいます。
さらに、このパラメーターはMA Information上ではAnimator Onlyとしてカウントされているためか、MA Information上で表示される消費bit数とビルド後に実際に消費されるbit数が一致しなくなっています。
(VirtualLens2側の問題な気もしますが、MAも絡むためこちらにIssueを作成しました)

<br>

![image](https://github.com/user-attachments/assets/9f056548-b756-4cfe-a07a-64afd7254b0f)
VirtualLens2がアバターにセットアップされている状態で、Animator Onlyとしてパラメータを追加すると…

![image](https://github.com/user-attachments/assets/e1c5f52b-6ef1-4c41-9354-46c55955fdd5)
MA Information上では5bit余裕があるはずが…

![スクリーンショット 2024-11-10 132827](https://github.com/user-attachments/assets/a458dade-5aa1-49bf-b008-47151b9447d8)
Av3Emuで確認するとSyncedパラメータとして登録されており、EX Paramの256bit制限も超過している

**Comment by shirasu256** [comment]
単純な回避策はMA ParametersでそのパラメータをAnimator Onlyとしても登録せず、Unregistreted Parameterにしておくだけです

**Comment by logicmachine** [comment]
VirtualLens2 の開発者です。
VirtualLens2 ではビルド時に MA Parameters で Int (もしくは Float) かつ Not Synced な要素を持つ MA Parameters を追加してパラメータを追加しています。
2つの MA Parameters コンポーネントを同一アバター内に用意し、それぞれに同名パラメータで片方は Animator Only、 他方は Int + not synced のようにしてやると VirtualLens2 なしでもこの問題を再現することができます。

Animator Only 側の MA Parameters で、一度 Int にして Synced のチェックを外して再度 Animator Only に戻すと発生しなくなるので、おそらくパラメータをマージする際に Animator Only の場合は参照するべきではない Synced を参照してしまっているのではないかと思われます。ご確認いただけないでしょうか?

現バージョンでユーザー側でできる回避策としては、明示的に Int や Float + not synced と指定するのがベターかと思います。
