### ISSUE TITLE
InvalidCastException occurs when setting AnimatorOverrideController to MergeAnimator

### ISSUE THREAD

**Issue by raiti-chan** [bdunderscore/modular-avatar#138]
The property that sets the AnimatorController of MergeAnimator is of type RuntimeAnimatorController, so it can set AnimatorOverrideController.

InvalidCastException occurs in [(AnimatorController) merge.animator](https://github.com/bdunderscore/modular-avatar/blob/main/Packages/nadena.dev.modular-avatar/Editor/MergeAnimatorProcessor.cs#L90) when AnimatorOverrideController is set.

To work around this, either prevent the Inspector from setting AnimatorOverrideController or support AnimatorOverrideController.

**Comment by bdunderscore** [comment]
Merged and will go out with the next release. Thanks for the contribution!
