### ISSUE TITLE
ScaleAdjuster components don't preview in Prefab Edit Mode

### ISSUE THREAD

**Issue by kb10uy** [bdunderscore/modular-avatar#1385]
## 概要
* Prefab Edit Mode で Prefab を編集しているときに ScaleAdjuster のプレビューが動作していない。
* Prefab Edit Mode での表示:
    - <img width="640" alt="Unity_1733412866_TgTrs" src="https://github.com/user-attachments/assets/cf388837-7e32-4624-b055-e6ae01c5b135">
* 上の Prefab (Variant) を Scene View で Scene に配置した際の表示:
    - <img width="640" alt="Unity_1733412882_dAEMS" src="https://github.com/user-attachments/assets/f14cfad1-2c9f-442b-9b16-7871d9feb50a">

## 再現方法
1. Prefab Edit Mode に入り、適当なアバターの Prefab で ScaleAdjuster を追加する。
2. この時点で、 ScaleAdjuster はプレビューによる変形が適用されていない。
3. Scene View に戻り、適当な Scene で 1. の Prefab を配置する。
4. この Scene 上では ScaleAdjuster のプレビューによる変形が適用されている。

## 備考
* **NDMF Preview が Prefab Edit Mode で適用されない** というより一般的な事象の可能性がある。
    - AAO Remove Mesh By BlendShape や TTT Atlas Texture も NDMF Preview の効力が Prefab Edit Mode で適用されていないのを観測しているため。

**Comment by bdunderscore** [comment]
https://github.com/bdunderscore/ndmf/issues/326 これ待ちですね・・・重複なのでクローズしますが、そのうち治したいところです
