### ISSUE TITLE
Unable to use Modular Avatar

### ISSUE THREAD

**Issue by lancettechen** [bdunderscore/modular-avatar#166]
I'm currently using a fresh project to test this out. I've only installed VRC SDK3->Install Modular Avatar(latest unitypackage from Github) and Newton Json(via package manager)->Reboot Unity->Import shaders, avatar, and a costume. However, righht-clicking on the avatar/costume shows a greyed out button for costume setup. Manually baking created a clone that has a clickable costume setup button that doesn't work. I also tried pre-exisintg projects and none of them work

Am I missing any prerequisite packages or something?

**Comment by bdunderscore** [comment]
Please check that:

1. Your outfit does not have an avatar descriptor attached
2. Your avatar _does_ have an avatar descriptor attached
3. Your outfit's bone naming convention is similar to the base avatar.

If that doesn't help, please post a screenshot of the avatar and outfit armatures.

**Comment by lancettechen** [comment]
> Please check that:
> 
> 1. Your outfit does not have an avatar descriptor attached
> 2. Your avatar _does_ have an avatar descriptor attached
> 3. Your outfit's bone naming convention is similar to the base avatar.
> 
> If that doesn't help, please post a screenshot of the avatar and outfit armatures.

Sorry for getting back to you late thanks to COVID. I just tested with the latest release. It works now. I'm not sure what was causing the issue in the previous release though. But since the latest version is working, I think the issue is fixed
