### ISSUE TITLE
I would like a mechanism to specify the order of execution in MergeAnimator.

### ISSUE THREAD

**Issue by raiti-chan** [bdunderscore/modular-avatar#175]
MergeAnimatorで統合されるコントローラのレイヤーは実行順で決まり、Hierarchyによって指定できますが、逆にそれで悩む場合があります。
レイヤーの前後で結果が変わってしまうアニメーションがり、複数のアセットに分かれている場合、配置する順序を間違えると動作しない場合があります。
本来、レイヤー順序が厳密なコントローラは分けずにまとめる方が正しいのかもしれませんが、少なからずとも分けたい場合があります。
その場合hierarchyで順序を決めるのが大変なため、処理順を決める何かしら別の方法が欲しいです。

例えば、アセット作成者が指定できるデフォルトのプライオリティと、
アセット使用者がもしもの時に上書きできるプライオリティ(上級者向け設定)等を用意したらどうでしょうか。

**Comment by bdunderscore** [comment]
ん－　今の仕様になっている理由の一つとしては、異なる作者のアセットを混ぜると数値により処理準にするとその数値を決める基準がなかなか決まらない問題があるからなので、プライオリティによるものは避けたいですね。実装するとしたら、コンポーネントのリストを入れて、リストに入ってるコンポーネント同士の相互順番を決める方針かな。

問題としては、複数の順番決めコンポーネントに同じコンポーネントが登録されてる場合は不定になるので、エラー報告システムを実装した後に回したいですね。

**Comment by bdunderscore** [comment]
1.9で実装
