### ISSUE TITLE
Add functionality to specify the menu install position

### ISSUE THREAD

**Issue by ScrapW** [bdunderscore/modular-avatar#177]
Currently, the menu installation location is by default at the end of the selected expression menu.
But sometimes I want to install the menu in between some non-modular menu options, which currently doesn't seem to be possible.

Please add this feature if possible. I think this could be done by letting the user create indicators in the menu with parameter None and replacing them at menu install time.
Also, if possible, could you add an option to Menu Installer to install as Submenu? It feels like this would save some work.

**Comment by bdunderscore** [comment]
I'd like to expand on the current menu functionality, maybe making it look something like Hai~'s [Expressions Menu Hierarchy Editor](https://github.com/hai-vr/av3-expressions-menu-hierarchy-editor); I'll keep this request in mind when it comes time for that.
