### ISSUE TITLE
Odd locomotion issue on 1.4.0

### ISSUE THREAD

**Issue by Bullace** [bdunderscore/modular-avatar#187]
Hey,
I just updated to 1.4.0 and now my avatar has locomotion issues. It doesn't happen on 1.3.0. My avatar is a Kikyo and uses the default Kikyo_Locomotion controller. I looked for errors in the console but saw nothing out of the ordinary. I checked out the Base layer in play mode and see the setup is a bit different from 1.3.0 but when clicking and inspecting it, it appears the same. If I remove the Kikyo_Locomotion from the Base and reupload then the avatar works fine but of course now it's using the default VRChat animations.

Demonstration: https://mega.nz/file/2ZwRTAZQ#cOrgX7eLz-hKVwb438rJimzDbH0M9CKHOyb5QHvn2fc

**Comment by bdunderscore** [comment]
Are you using the unitypackage version of the VRCSDK or the VCC version?

**Comment by Bullace** [comment]
I was still on the old SDK. I was unaware it was no longer maintained and have just updated to VCC. Installed 1.4.1 and the issue seems to be gone now.

**Comment by bdunderscore** [comment]
The unitypackage version is _intended_ to be supported - at least until VRChat officially drops support. I'll try to repro the issue.
