### ISSUE TITLE
統合されたAnimatorの中を確認できない。

### ISSUE THREAD

**Issue by takecccc** [bdunderscore/modular-avatar#199]
Play modeに入った際に統合されたAnimatorが生成されるが、Animator Windowにて中の構造が表示されず、デバッグ用途などで中の構造を確認することができない。

**Comment by bdunderscore** [comment]
これはUnityの謎仕様で、適当なアセットを複製(Ctrl-D)すると中身が見れるようになると思います。しかし自動的に見れるようにする対策を探したほうがよさそうですね・・・（こっちもデバッグがめんどくさい）

**Comment by bdunderscore** [comment]
1.4.4で修正しました
