### ISSUE TITLE
VRCのメニュー設定からMAparameterが認識されない（ので値を変更できない）

### ISSUE THREAD

**Issue by ni1chigo2115** [bdunderscore/modular-avatar#204]
タイトル通りです。
プレイモードに入りビルドすると、適切に設定自体は機能はします
しかしメニューコンポネートからメニューのパラメーターを弄ることができません。
このままだと、メニューの編集に一度パラメーターファイルを用意する必要があります。
後々のアセットの追加のメンテナンスの事を考えると、何かしらの対策が必要に思います。

**Comment by bdunderscore** [comment]
長期的には独自のメニュー編集UIを用意したいとは思っていますので、その過程で解決すると思います。
なお、現状のVRCのメニュー設定ＵＩの仕様では、リストから選択できなくても手打ちでパラメーター名を入れることができます。

**Comment by ni1chigo2115** [comment]
入力したいのはparameter名よりも各メニューアイテムで代入される数値なんですよね
（INTで数値代入しての切り替えの設定がMA経由だと難しい）
独自の編集UIの方楽しみにしています
