### ISSUE TITLE
MA Parameters: Component inspector is extremely slow with many parameters

### ISSUE THREAD

**Issue by rrazgriz** [bdunderscore/modular-avatar#217]
I'm using MA to merge a face tracking controller in, which uses a large number of boolean and float parameters, and contains proxy parameters for processing. There's around 168 in total. 

The MA Parameters inspector is exceedingly slow in this condition, making it difficult to work with.

https://user-images.githubusercontent.com/47901762/220505007-f8429a9d-777a-4e15-a24a-efbdf5f27d52.mp4

**Comment by bdunderscore** [comment]
This appears to be a performance bottleneck in Unity's ReorderableList when using variable-height list items. The function to obtain an element's Y offset is O(n^2):

https://github.com/Unity-Technologies/UnityCsReference/blob/2019.4/Editor/Mono/GUI/ReorderableList.cs#L355-L359

Fixing this would require either redoing the UI to avoid variable height fields, or reimplementing ReorderableList manually. Or maybe using Harmony to patch this function? Will need some thought.

**Comment by bdunderscore** [comment]
Adding a cache for element height (to reduce the reflection overhead) seems to bring things within the realm of being slow but not unusably so.

**Comment by bdunderscore** [comment]
Leaving open as the improvement doesn't really put perf where I'd like it to be.

**Comment by rrazgriz** [comment]
Thank you! Fixed version is at least usable - previously, it could take a few tries to press checkboxes, but it's reliable now, just slow.
