### ISSUE TITLE
Creating a Parameters object but no Menu object

### ISSUE THREAD

**Issue by float3** [bdunderscore/modular-avatar#238]
Initial State:
![image](https://user-images.githubusercontent.com/86748455/224946919-9dab1008-bc3b-4044-88db-cb09a401ed84.png)

After Manual Bake: (The Expressions tab is not folded out but if you do fold it out it will reveal only a Parameters object and no Menu object)
![image](https://user-images.githubusercontent.com/86748455/224947530-87a2aa9a-ee24-4a99-b5b0-19ff222abcec.png)
![image](https://user-images.githubusercontent.com/86748455/224947131-a50a3e91-a5ac-42e0-baee-e7d636b697a8.png)

this is happening on be654074d9443a109fa34528ea4db160daa3aed8 on the main branch

**Comment by camegone** [comment]
I had encounted a similar problem, but in my case, both Menu and Prameters are not created.
![image](https://user-images.githubusercontent.com/121595305/230381062-afd9bbd8-099e-41ad-afb8-727fe301f4f1.png)

**Comment by bdunderscore** [comment]
Can you verify if this happens with `1.5.0-beta-2`?

**Comment by float3** [comment]
on d1288fd3357128aaa6faae82e45a336f2207c054 the "Setup Outfit" button doesn't work with the avatar I've been using to test anymore.

**Comment by bdunderscore** [comment]
Please also make sure you’re using the latest VRCSDK (3.1.13)

**Comment by float3** [comment]
the button is just grayed out, I'll let you know when I have time to test a different avatar
