### ISSUE TITLE
rootBone override is not retargeted

### ISSUE THREAD

**Issue by anatawa12** [bdunderscore/modular-avatar#240]
m_RootBone is not retargeted (if no bones are set to the SkinnedMeshRenderer).

This is general case for AvatarOptimizer.

**Comment by bdunderscore** [comment]
Looking at your PR, it looks like you're handling cases where the mesh is null on a renderer, but those cases would normally result in a broken renderer that doesn't render anything. Do you have an example or test case where this happens?

**Comment by anatawa12** [comment]
AvatarOptimizer will assign mesh for SkinnedMeshRenderer after Modular Avatar so I want MA to retarget bones even if mesh is None.
