### ISSUE TITLE
argumentNullexception when setting up outfit

### ISSUE THREAD

**Issue by evaunit01berserk** [bdunderscore/modular-avatar#254]
ArgumentNullException: Value cannot be null.
Parameter name: value
System.String.StartsWith (System.String value) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
nadena.dev.modular_avatar.core.editor.HeuristicBoneMapper.AssignBoneMappings (nadena.dev.modular_avatar.core.ModularAvatarMergeArmature config, UnityEngine.GameObject src, UnityEngine.GameObject newParent) (at Packages/nadena.dev.modular-avatar/Editor/HeuristicBoneMapper.cs:139)
nadena.dev.modular_avatar.core.editor.HeuristicBoneMapper.<RenameBonesByHeuristic>g__Traverse|6_0 (UnityEngine.Transform src, UnityEngine.Transform dst, nadena.dev.modular_avatar.core.editor.HeuristicBoneMapper+<>c__DisplayClass6_0& ) (at Packages/nadena.dev.modular-avatar/Editor/HeuristicBoneMapper.cs:199)
nadena.dev.modular_avatar.core.editor.HeuristicBoneMapper.RenameBonesByHeuristic (nadena.dev.modular_avatar.core.ModularAvatarMergeArmature config) (at Packages/nadena.dev.modular-avatar/Editor/HeuristicBoneMapper.cs:195)
nadena.dev.modular_avatar.core.editor.EasySetupOutfit.SetupOutfit (UnityEditor.MenuCommand cmd) (at Packages/nadena.dev.modular-avatar/Editor/EasySetupOutfit.cs:27)
UnityEditor.GenericMenu:CatchMenu(Object, String[], Int32)

Can't seem to find what value in nulled

**Comment by evaunit01berserk** [comment]
Was a version issue

**Comment by evaunit01berserk** [comment]
Issue is occuring again.

**Comment by bdunderscore** [comment]
This appears to be from a very old version and I'm not sure what line that corresponds to. If this recurs with recent versions of MA, please post the specific version you're using with an updated stack trace.
