### ISSUE TITLE
Moving objects with MA Bone Proxy has unintended consequences in certain hierarchy configurations.（特定の階層構成において、MA Bone Proxyによるオブジェクトの移動が意図しない結果となる）

### ISSUE THREAD

**Issue by nashikan** [bdunderscore/modular-avatar#259]
I want to put the head of Avatar_B into Avatar_A.
However, the accessory was originally set up on Avatar_B's head by MA Bone Proxy.
After putting Avatar_B's head into Avatar_A, the accessory moves to Avatar_A's Head.

I think we need an additional rule for the processing rules.
Currently, it seems that everything is processed flat, both inside and outside the Prefab.

[Current procedure (guess)]
・Processing from the terminal MA component, such as children and grandchildren.

[Procedure after change]
・If there is a Prefab, first process the inside of that Prefab.　<=Additional rule
・MA components in a Prefab are processed within that Prefab.　<=Additional rule
・ Processing from the terminal MA component, such as children and grandchildren. <= keep this rule

Avatar_Bの頭をAvatar_Aに入れたいです。
ただし、アクセサリはもともと MA Bone Proxy によって Avatar_B の頭に設定されていました。
Avatar_B の頭を Avatar_A に入れた後、アクセサリは Avatar_A の頭に移動してしまいます。

処理に関するルールに、追加のルールが必要と思います。
現状は、Prefab内も外も全てフラットに処理していると思われます。

【現状の手順（推測）】
・子や孫など、末端のMAコンポーネントから処理

【変更後の手順】
・Prefabがある場合、先にそのPrefab内を処理する　＜＝追加ルール
・Prefab内にあるMAコンポーネントは、そのPrefab内において処理する　＜＝追加ルール
・子や孫など、末端のMAコンポーネントから処理　＜＝このルールはそのまま

![a](https://user-images.githubusercontent.com/129356895/229341404-04082043-b681-4c90-b9de-d7d7caa5a9a1.png)

**Comment by bdunderscore** [comment]
まず、Prefab状態を参照することはPrefabを強要することになるので不適切だと考えられます。また、VRCSDKの構造上、ビルド時Modular Avatarが実行する前に完全にUnpackされるので実装も困難です。

問題を精査すると、「頭を移植して、（書いてないけど）Avatar BのArmatureを併合したあと、Headに追従するアクセサリーをAvatar BのHeadにくっつけるべき」という風になりそうですが、指摘した通り「ワールド位置と向きを維持」しているので相対位置が変わりません。また、Avatar BのHeadボーンもこの時点でAvatar AのHeadボーンに併合されているはずです（もともとのAvatar Bのボーンが動かないというわけです）

なので、実質の問題として「アクセを位置保持しないモードにすると初期位置がずれる」ということになるけど、どのみち非対応のアバターに入れるなら位置調整が必要と思われます。なので、あまり問題が見られませんが、何か見落としているでしょうか？

**Comment by nashikan** [comment]
> まず、Prefab状態を参照することはPrefabを強要することになるので不適切だと考えられます。また、VRCSDKの構造上、ビルド時Modular Avatarが実行する前に完全にUnpackされるので実装も困難です。

なるほどです、それだとツール側からはどこがPrefabの境界かわからないですね・・・。
「Prefab状態を参照することはPrefabを強要する」については、すみません、理解できていません。

> Avatar BのArmatureを併合

これはしていません。Avatar_BのHeadにMA Bone Proxyを付けて、Avatar_AのHead下に移動させています。
（Headは併合されず入れ子になりますが諦めています。また、Avatar_AとBではHeadの位置も異なり単純併合はできないと想像します）
MA Merge Armatureを使用しない理由は、Head以下のボーン以外（腕とか足とかは）不要であり、他の余分なボーンについている余計なコンポーネントが併合されるのを避ける意図です。

> あまり問題が見られません

今回のアクセサリーの例では実質問題なく動作するため、あまり問題視していません。
ModularAvatarの目指すところのモジュール化という点について、
MAコンポーネントを内包したPrefabが、さらに別のPrefabに配置されるような多重構造において、
「Prefab内ごとにMA処理を完結する」ことがよりモジュール化を意識した仕組みになるかと想像しましたが、
最初に説明いただいたように「VRCSDKの構造上、ビルド時Modular Avatarが実行する前に完全にUnpackされる」ということであれば、確かに実装上難しそうと思います。（長々すみません）
