### ISSUE TITLE
[Modular Avatar] Setup Outfit Button Greyed Out.

### ISSUE THREAD

**Issue by Drakensin** [bdunderscore/modular-avatar#266]
Just recently found out about this tool and i wanted to five it a try. I have downloaded Version 1.4.5 (Latest). Unfortunately the Setup Outfit button is greyed out and i cant seem to use the tool. any workarounds/fixes?

**Comment by TumbleFoxXYZ** [comment]
Yo i was running into the same problem, as i found out, you need to drag it under the avatar you are wanting to apply the items to, so the item is a child of the avatar. Hope this helps
![Screenshot 2023-04-06 211451](https://user-images.githubusercontent.com/130045830/230332235-c4ca5940-3358-49c3-974c-c6c0540fc923.png)

**Comment by Drakensin** [comment]
> 

Still same issue
![MA Issue](https://user-images.githubusercontent.com/26281394/230392104-1929f2c5-f0a6-4d8e-ba53-612998c15857.png)

**Comment by bdunderscore** [comment]
Please make sure your top-level avatar has an avatar descriptor configured, and that the armature on your clothes is compatible with the top-level avatar.

**Comment by bdunderscore** [comment]
Setup Outfit now shows an error instead of disabling the menu item
