### ISSUE TITLE
[beta] MA Menu Installer のインストール先が空のメニューアセットである場合、メニューが反映されない。

### ISSUE THREAD

**Issue by Narazaka** [bdunderscore/modular-avatar#285]
1.5.0-beta-2においてエンバグしている模様です。
1.4.5においては意図通りに動作していました。

MA Menu Installerのインストール先を空のメニューアセットにし、そのメニューアセットをSubMenuとして参照するルートメニューアセットをMAでアバターに統合する設定にした場合、実際には統合されず空のメニューのままになってしまう（Gesture Manager等エディタおよびVRChat上いずれでも再現）。
![image](https://user-images.githubusercontent.com/1712548/234274204-3f887a63-5a8a-4c0f-93de-3581daea2af3.png)
![image](https://user-images.githubusercontent.com/1712548/234274274-54bdf974-faca-4476-b660-fce297f11237.png)
![image](https://user-images.githubusercontent.com/1712548/234274309-d958fa38-a260-4b42-aef3-b461d69d0bce.png)
![image](https://user-images.githubusercontent.com/1712548/234274374-f25ed791-a8ea-491c-b427-ac3d761ea61e.png)
![image](https://user-images.githubusercontent.com/1712548/234274879-5dc2dfb5-777a-457a-b039-bf3c1d560121.png)

**Comment by Narazaka** [comment]
![image](https://user-images.githubusercontent.com/1712548/234276470-4934fcc2-6f7f-4a14-9c0e-3027be950b2e.png)
なお統合先のルートメニューを一段階Extract to objectsしてMA Menu Itemにした状態では正常に結合されました。（エディタ上のみで確認）

**Comment by bdunderscore** [comment]
現時点では直ってるっぽいのでクローズします。まだ再現できるなら詳細とともにリオープンお願いします
