### ISSUE TITLE
MA Menu Itemのnameがオブジェクト名に同期しないようにしたい

### ISSUE THREAD

**Issue by Narazaka** [bdunderscore/modular-avatar#286]
既存prefabから展開したときにオブジェクト名を変更しないといけなくなるので

**Comment by bdunderscore** [comment]
うーん、プレハブの子にすることで迂回はできないのかな？

**Comment by Narazaka** [comment]
- まあ子にして回避できなくはない
  - が、それはそれでちょい気持ち悪い
- nameを同期する意図はよく分かる
  - なので主張出来てオプトアウトかなあと思っているが、まあ微妙かも知れない

**Comment by bdunderscore** [comment]
必要がない場合の選択・オプトアウトがあると、ドキュメンテーションやテスト、そしてユーザーが理解するための負担が増えるので、簡単に回避できる限りはちょっと避けたいかなーと思ったりしてますね

**Comment by Narazaka** [comment]
なるほどです。
