### ISSUE TITLE
Error reporting UI does not show any errors

### ISSUE THREAD

**Issue by logicmachine** [bdunderscore/modular-avatar#291]
The error reporting window will appear when MA has detected build-time errors but it will not show any detail of the errors.

![image](https://user-images.githubusercontent.com/1937211/235296492-0ef7577b-93cb-44f4-95ff-66fb8ed68fd5.png)

## How to reproduce
- Create an empty scene.
- Create an avatar.
- Attach following objects for the avatar.
    - `A`: has MA Merge Animator with a controller that has an int parameter `X`.
    - `B`: has MA Merge Animator with a controller that has a float parameter `X`.
    - They cause an error `error.merge_animator.param_type_mismatch` and it should be reported.
- Build the avatar.

## Environment
- VRCSDK 3.1.13
- Modular Avatar 1.4.5 and 1.5.0-beta-3

**Comment by bdunderscore** [comment]
Replaced by a new error reporting system, please open a new issue if this is still a problem.
