### ISSUE TITLE
multi-option-toggles should be able to turn the component off and on.

### ISSUE THREAD

**Issue by HotKonti** [bdunderscore/modular-avatar#298]
https://modular-avatar.nadena.dev/dev/docs/tutorials/menu/#multi-option-toggles

If you upload with Object turned off in VRChat, the light is not applied normally, so there is a phenomenon that only certain clothes come out dark or bright for each world.

This is because VRChat does not modify the lights in the Mesh Renderer and Skinned Mesh Renderer if the object is uploaded with it turned off.

Therefore, the closet system must be implemented by turning off and on the Mesh Renderer and Skinned Mesh Renderer.

https://arca.live/b/vrchat/70316200

**Comment by bdunderscore** [comment]
Fixed by VRChat, I think?
