### ISSUE TITLE
MergeArmature実行時、Colliderが消失する

### ISSUE THREAD

**Issue by Azukimochi** [bdunderscore/modular-avatar#321]
**バグ内容**
MargeArmatureでボーンをマージすると、Colliderなどの付随したボーンもマージされてしまい、Box/Sphere/CapsuleなどUnity標準のColliderが消失する。

Clothコンポーネント設定時に対象コライダーが消失(Missing)していることを確認しました。

実行前：
![image](https://github.com/bdunderscore/modular-avatar/assets/103747350/b58c3d69-617a-4633-afed-6e072729c372)

実行後：
![image](https://github.com/bdunderscore/modular-avatar/assets/103747350/a7fe9d96-adf2-42b2-80b3-66cb57eccadd)

**Comment by bdunderscore** [comment]
再現できる衣装を紹介できますか？

**Comment by Azukimochi** [comment]
マージ動作でコライダーが消失するという動作自体は衣装を問わず、空オブジェクトを用いることでも動作再現可能です。
なお、本動作は最新版の1.5.1で確認しています

こちらの例ですが、アバターに空オブジェクト　[Armature] [Hips] [GameObject] を作成し、
[Armature] にはMA MergeArmatureコンポーネント
[Hips] にCapsul Colliderコンポーネント
[GameObject] にClothコンポーネントを追加、Capsul Collidersに [Hips] オブジェクトを追加
![image](https://github.com/bdunderscore/modular-avatar/assets/103747350/c1ada52b-6ba7-460f-a946-e83deebd9529)

これを実行すると [Hips] に追加していたCapsul Colliderが消滅し、[GameObject]に設定したClothコンポーネントからMissingの扱いを受けるというものです 
![image](https://github.com/bdunderscore/modular-avatar/assets/103747350/3ce1d24d-1cf3-477e-8ff9-1c48de46a496)

**Comment by Azukimochi** [comment]
なお、[Armature]配下にアバターボーンと同名の[Hips]ではなく[Hips_Collider]のような名前に変更することでマージされず、コライダーが存在することが確認できます。
これによってマージ動作で消滅していると判断しました。

[Armature]配下に[Hips_Collider]を作成し、同様にCapsule ColliderコンポーネントとClothコンポーネントへの割当
![image](https://github.com/bdunderscore/modular-avatar/assets/103747350/e96ec26c-a7f8-4ae2-86a2-ced7335ae1f1)

実行後
アバターArmature配下に[Hips_Collider$6b01e....]オブジェクトが生成されClothコンポーネントでのColliderの生存を確認
![image](https://github.com/bdunderscore/modular-avatar/assets/103747350/69f68ed7-08da-4823-9c2a-b4762b19f2c2)

**Comment by bdunderscore** [comment]
再現できました。次のバージョンで修正する予定です。
