### ISSUE TITLE
Error after imported

### ISSUE THREAD

**Issue by KusadaKusaba** [bdunderscore/modular-avatar#322]
Error after imported in my new project,
Packages\nadena.dev.modular-avatar\Runtime\AvatarTagComponent.cs(35,63): error CS0246: The type or namespace name 'IEditorOnly' could not be found (are you missing a using directive or an assembly reference?)

**Comment by bdunderscore** [comment]
Please ensure you are running the latest version of VRCSDK. If you install using the VRChat Creator Companion this will automatically be upgraded to the necessary version.
