### ISSUE TITLE
MA Parametersで「内部値」とした値がMA Menu Installerの値と連携されない2

### ISSUE THREAD

**Issue by Narazaka** [bdunderscore/modular-avatar#326]
部分的に残っているっぽいので
https://github.com/bdunderscore/modular-avatar/issues/305#issuecomment-1566700004

**Comment by Narazaka** [comment]
1.6.0において
以下の構成においてLyuma AV3EmulatorでのテストおよびManual Bakeにおいて
FX AnimatorとVRCExpressionParametersでは`nahuda_show$$Internal_0`とリネームされているが、当該のVRCExpressionsMenuにおいては`nahuda_show`のままになっており、メニューが機能しない。

シーン上のオブジェクト（いちからMAセットアップした）
![image](https://github.com/bdunderscore/modular-avatar/assets/1712548/6f75f821-4852-4679-8b6f-e80b3b1e6b06)
ルートオブジェクト
![image](https://github.com/bdunderscore/modular-avatar/assets/1712548/8cc1b774-b5c7-4e0c-8cfa-867d74c23a18)
メニューのオブジェクト（MA Menu Itemを使いつつSubMenuに子のメニューアセットを指定）
![image](https://github.com/bdunderscore/modular-avatar/assets/1712548/8da1d5bd-fbfd-4697-87a3-ecda13c5606e)
子のメニューアセット
![image](https://github.com/bdunderscore/modular-avatar/assets/1712548/16961199-63e2-4bc8-a70e-bca124bd97f5)

**Comment by Narazaka** [comment]
恐らく再現可能なprefabを添付します
[MeMenuTest.zip](https://github.com/bdunderscore/modular-avatar/files/12211704/MeMenuTest.zip)

**Comment by bdunderscore** [comment]
@Narazaka 再現プレハブありがとうございます。 PR #371 を更新しまて、今度こそおそらく直ってるはずなので確認お願いします 🙏
