### ISSUE TITLE
[bug] endボーンを削除すべきでない

### ISSUE THREAD

**Issue by Narazaka** [bdunderscore/modular-avatar#332]
Modular Avatarを利用したアバターをmanual bakeしたものをVRMモデルとして利用する場合、VRMSpringBoneがendボーンを見て方向を決定する挙動であるためendボーンを削除すると挙動が狂います。

現状PhysBonesやHumanoidのendボーンであるかなどを判定して挙動を決定しているようだが、いかなる場合でもendボーンを削除しないという挙動の方が適切だと思います。

**Comment by bdunderscore** [comment]
endボーンの判定基準が難しいですね・・・何とかしてみます。

**Comment by Narazaka** [comment]
実際難しいため自分のツールでは名前一致でやったりしており、その程度でも良いかも……
https://github.com/Narazaka/BoneSelector/blob/master/BoneReference.cs#L11
