### ISSUE TITLE
GestureManagerでDebugした際にボーンのLocalTransformがおかしくなる

### ISSUE THREAD

**Issue by takecccc** [bdunderscore/modular-avatar#337]
VRC Phys Bone Colliderを設定しているため追加されているボーンについて、
普通にPlayModeに入る分には問題ないのですが、GestureManagerでDebugしようとするとボーンの位置が乱れます。

普通にPlayModeに入った場合は結合時のボーンの位置を維持しているのですが、
GestureManagerを選択した時点で親のLocalTransformと同じ値が追加したボーンのLocalTransformに適用されてしまいます。

![image](https://github.com/bdunderscore/modular-avatar/assets/81757117/e1242902-8388-4716-b673-08f9e792e717)

親
![image](https://github.com/bdunderscore/modular-avatar/assets/81757117/83edebf0-11c5-4bb6-b493-88f1edb5046a)

子(GestureManager未選択時)
![image](https://github.com/bdunderscore/modular-avatar/assets/81757117/607d208e-5017-4b8d-a268-a72acc728ae9)

子(GestureManager選択時)
![image](https://github.com/bdunderscore/modular-avatar/assets/81757117/fceac116-73cc-4747-a6a6-fb51a2bb0bc5)

**Comment by takecccc** [comment]
衣装側のFBXもHumanoidとしてセットアップしていたことが原因のようです。

**Comment by anatawa12** [comment]
第三者が失礼します

Play時に実行される非破壊ツールとGesture Manegeの互換性に関してはGM側に修正要求を一つ送っています。 https://github.com/BlackStartx/VRC-Gesture-Manager/issues/26

GMの作者さんの

> Meanwhile I would suggest to start playmode without the Gesture Manager GameObject selected so you can delay the initialization manually~
> 回避策として、初期化を手動で遅らせるために、GestureManager GameObjectを選択せず​​にプレイモードを開始することをお勧めします〜

で回避可能であればGM側の修正にて修正されると思います

**Comment by takecccc** [comment]
情報ありがとうございます。
GestureManagerを選択しない場合は問題なく動作していました。
また、今回のケースは衣装のAnimatorコンポーネントを削除することで回避することができました。

**Comment by bdunderscore** [comment]
初期化順の問題でGestureManager側で対策されるとのことですので、このIssueをCloseさせていただきます。
なお、衣装側のAnimatorは本来削除したほうが軽量化につながるので推奨です（とはいえ、非対応衣装導入補助として参照する仕様を導入するかもしれないので、ＭＡ側で不要のAnimatorを削除させたほうがいいかもしれません・・・）
