### ISSUE TITLE
衣装のArmature内のスケールを本体に統一する機能

### ISSUE THREAD

**Issue by SnowFairy1109** [bdunderscore/modular-avatar#343]
MergeArmatureを使ってボーンを統合する際、
ボーンのスケールを弄って改変している場合に、
チェック式で
衣装のボーンのスケールを合わせてくれる機能があると便利だなと思いました。
現状は衣装のボーンのスケールも手で合わせていじっているので
マージしたあとスケールを1に統一してくれると便利だなと思いました。
ただまあ、改変でボーンのスケールまでいじってる人はかなりわかってる人だと思いますし、
衣装のボーンのスケール手で直してあげればいいだけではあるので　優先度は低いかと思いますが
一応要望として掲載させていただければと思います。

**Comment by bdunderscore** [comment]
対応服の場合は「位置を固定」という設定を入れることでスケールを合わせるようになりますが、非対応服の話でしょうか？

**Comment by SnowFairy1109** [comment]
あ、すみません
位置を固定　の機能を誤認してました
取り下げますm(_ _)m
