### ISSUE TITLE
Mesh Settings are not reflected on objects with Bone Proxy component

### ISSUE THREAD

**Issue by kxn4t** [bdunderscore/modular-avatar#354]
The documentation says that the settings are applied to all meshes under the object for which the Mesh Settings are set, but it does not seem to be applied to objects for which the Bone Proxy component is set.
Is this a specification?

If it is a specification, I would like to add it to the document.

I have always found Modular Avatar useful and I love it so much that I can't live without it. 
Thanks!

**Comment by bdunderscore** [comment]
This is a bug - mesh settings should affect objects underneath it in edit mode, but it's applied too late in processing.
