### ISSUE TITLE
Error occured in Play Mode

### ISSUE THREAD

**Issue by YukihoAA** [bdunderscore/modular-avatar#361]
![image](https://github.com/bdunderscore/modular-avatar/assets/20253131/21be218f-0985-4e05-a8b6-8800629c3068)

I couldn't found a reason why,

It happend when merging animaor

**Comment by bdunderscore** [comment]
This is typically caused by having missing scripts on your avatar (for example, dynamic bone components when you don't have DB installed)

**Comment by YukihoAA** [comment]
The reason was my Locomotion Animation Controller.

after i removed it, it worked fine.

thanks.
