### ISSUE TITLE
1.7.0Beta版 MAReplaceオブジェクトがうまく動いていない

### ISSUE THREAD

**Issue by ni1chigo2115** [bdunderscore/modular-avatar#377]
こんな感じで
今のところどういう風に使うかわかってないというのもありますが、選択ができないのであればそもそも交換しようがない感じがします
![20230805_MA](https://github.com/bdunderscore/modular-avatar/assets/23652237/2fd661be-4d3f-4e6a-8f00-0c596cc330e4)

**Comment by bdunderscore** [comment]
上書き先が指定されていないのですが、何を上書きしようとしたのでしょうか？

**Comment by bdunderscore** [comment]
ちなみにドキュメンテーションページはこちらです
https://modular-avatar.nadena.dev/dev/ja/docs/reference/replace-object/

**Comment by ni1chigo2115** [comment]
一応、HairプレハブのGroundPBCから、ヒエルラキーの上にあるGroundPBCに対して置き換えを行おうと思いましたが、そもそも選択すらできない、反映されないという感じでした。

**Comment by bdunderscore** [comment]
確認しました。どうやらUIを仕上げたところに見落としがあったようです。beta.2で修正します。

**Comment by ni1chigo2115** [comment]
こちらも修正を確認しました。
今のところ、書き換え先を認識しているのを確認しました。
二つ以上の置き換えは競合するということで非推奨のようですが、さらにもう一つ追加できないか（一つのPBCにまとめられないか）試してみます。
もしうまくいくのであれば、modular marshmallowの地面コライダーの置き換えにも対応できそうですね
