### ISSUE TITLE
Combine parameter asset instead of auto detected parameters

### ISSUE THREAD

**Issue by jerryzmtz** [bdunderscore/modular-avatar#410]
Is it possible to add a function to combine certain parameter assests instead of installing detected parameters? This function is specifically expected because of FaceTracking FX layer and parameters. Synced paramters are limited but too many internal parameters are detected while editing in editors is really slow. 

![detected parameters](https://github.com/bdunderscore/modular-avatar/assets/26083118/62ca4807-6ef2-4584-816f-2881ec8232f0)
![Parameters](https://github.com/bdunderscore/modular-avatar/assets/26083118/299a7d9c-534f-4146-8590-1da97b641be4)

**Comment by bdunderscore** [comment]
このUIに関してはUnity 2022移行後にUI Toolkitsに移行した際に見直す予定です。

**Comment by bdunderscore** [comment]
正確にいうと、2019ではUI Toolkitがちょっと未完成すぎるけど、2022ではかなり進歩してるらしいのでUI見直しはそれまで見送りたいと考えています。

**Comment by bdunderscore** [comment]
Oh, I guess it would be better to reply in English on this one. I’ll look into this after the Unity 2022 upgrade is fully released for VRChat itself, as I’ll need to use UI Elements to address the performance issues with this UI, and UI Elements is a lot more powerful in 2022.
