### ISSUE TITLE
衣装セットアップが出来ない

### ISSUE THREAD

**Issue by tetranotto** [bdunderscore/modular-avatar#411]
チュートリアル通りに着せ替えをしようとしたのですがアバター下に衣装を入れてるのにも関わらずsetup outfitがグレーの状態で出来ません
![1HzQguhU](https://github.com/bdunderscore/modular-avatar/assets/143814473/64ff0d49-f1b3-46f4-af27-3c5dba09bfce)

**Comment by Alexandre-Belhomme** [comment]
I'm not japanese, so i won't try to translate my english to japanese myself.
Can you verify that you have an avatar descriptor on your root avatar ?

If not, Modular Avatar won't be able to setup the outfit for you.

**Comment by bdunderscore** [comment]
1.7.5にて、setup outfitが動作しない場合に理由を表示するUIを追加しましたので、もう一度お試しください
