### ISSUE TITLE
Add UI to show preview of parameter bit count

### ISSUE THREAD

**Issue by bdunderscore** [bdunderscore/modular-avatar#424]

**Comment by Alexandre-Belhomme** [comment]
What would be the context of such UI ?
- would it be on a global avatar
- or more on the MA Parameter object ?
- Something else ?

**Comment by bdunderscore** [comment]
Not sure yet! This was a request I received on my discord and recorded here so I don’t forget.

**Comment by Sayamame-beans** [comment]
related: #303
