### ISSUE TITLE
MA Parametersのパラメータ名リネーム操作によるエラー、および、意図しない動作

### ISSUE THREAD

**Issue by nashikan** [bdunderscore/modular-avatar#426]
---------------------------------------------------------------------------

■ 背景

    test.unitypackageを添付します。

    いわゆる、"衣装変更のExMenu"を作りたく、
    1つのIntパラメータをExMenuから変更すると"衣装A"、"衣装B"、"衣装C"を切り替えるモジュールを実装していました。

    上記はあくまで"参考に添付するパッケージが何をしているか"の概要程度の説明で、
    その実装の途中でMA Parametersの挙動に気になる点があったため、その報告が主な目的となります。

    ※衣装変更の実装方法は多々あるため、そこはこの報告の主題ではありません。

    問題は"問題1"と"問題2"の2つあり、それぞれ発生手順を示します。
    また、"問題2"については発生しない場合の手順例も参考として示します。

---------------------------------------------------------------------------
■ 問題1の発生手順

    1-1."衣装切り替え(MA Parameters内包)"をアバター直下に配置
    1-2."衣装切り替え(MA Parameters内包)"の子として"衣装A"、"衣装B"、"衣装C"を配置
    1-3."衣装切り替え(MA Parameters内包)"のMA Parametersに次の変更を適用
        1-3-1."衣装A"を"衣装Aリネーム"に変更
        1-3-2."Cos_Item_0(default)"を"衣装Aリネーム"に変更
        1-3-3."衣装B"を"衣装Bリネーム"に変更
        1-3-4."Cos_Item_1"を"衣装Bリネーム"に変更
        1-3-5."衣装C"を"衣装Cリネーム"に変更
        1-3-6."Cos_Item_2"を"衣装Cリネーム"に変更

        ここで問題発生。エラーが発生しました。以下、エラーログ。
        ArgumentOutOfRangeException: Index must be within the bounds of the List.
        Parameter name: index
        System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
        System.Collections.Generic.List`1[T].Insert (System.Int32 index, T item) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
        nadena.dev.modular_avatar.core.editor.AvatarParametersEditor.DrawElement (UnityEngine.Rect rect, System.Int32 index, System.Boolean isactive, System.Boolean isfocused) (at Packages/nadena.dev.modular-avatar/Editor/Inspector/AvatarParametersEditor.cs:437)
        UnityEditorInternal.ReorderableList.DoListElements (UnityEngine.Rect listRect) (at <a259d3c004024353a2c217da97495055>:0)
        UnityEditorInternal.ReorderableList.DoLayoutList () (at <a259d3c004024353a2c217da97495055>:0)
        nadena.dev.modular_avatar.core.editor.AvatarParametersEditor.OnInnerInspectorGUI () (at Packages/nadena.dev.modular-avatar/Editor/Inspector/AvatarParametersEditor.cs:471)
        nadena.dev.modular_avatar.core.editor.MAEditorBase.OnInspectorGUI () (at Packages/nadena.dev.modular-avatar/Editor/Inspector/MAEditorBase.cs:126)
        UnityEditor.UIElements.InspectorElement+<>c__DisplayClass58_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <a259d3c004024353a2c217da97495055>:0)
        UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
---------------------------------------------------------------------------
■ 問題2の発生手順

    2-1."衣装切り替え(MA Parameters内包)"をアバター直下に配置
    2-2."衣装切り替え(MA Parameters内包)"の子として"衣装A"、"衣装B"、"衣装C"を配置
    2-3."衣装切り替え(MA Parameters内包)"のMA Menu Itemに次の変更を適用
        2-3-1."衣装B"のパラメータ値を1に変更    ※今回の問題に直接は関係ない操作ですが、このPrefabの本来意図する動作には必要な変更です。
        2-3-2."衣装C"のパラメータ値を2に変更    ※今回の問題に直接は関係ない操作ですが、このPrefabの本来意図する動作には必要な変更です。
    2-4."衣装切り替え(MA Parameters内包)"のMA Parametersに次の変更を適用
        2-4-1."衣装A"を"衣装Aリネーム"に変更
        2-4-2."Cos_Item_0(default)"を"衣装Aリネーム"に変更
        2-4-3."衣装B"を"衣装Bリネーム"に変更
        2-4-4."Cos_Item_1"を"衣装Bリネーム"に変更
        ※全てリネームすると"問題1"が発生するため、ここでは衣装Cをリネームしません。
    2-5.Playモードに入る
    
    ここで問題発生。
    FXのパラメータリストに、
    "衣装A"、"Cos_Item_0(default)"、"衣装B"、"Cos_Item_1"が残っています。
    これらは全て、"衣装Aリネーム"と"衣装Bリネーム"に置き換わると予想していました。

    さらに手順続きます。

    2-6.Editモードに戻る
    
    ここで問題発生。
    "衣装切り替え(MA Parameters内包)"のMA Parametersで、
    リネームしたパラメータが消えており、空欄だけが残った状態となっています。
---------------------------------------------------------------------------
■ 問題2が発生"しない"手順（その1）

    3-1."衣装切り替え(MA Parameters後付)"をアバター直下に配置
    3-2."衣装切り替え(MA Parameters後付)"の子として"衣装A"、"衣装B"、"衣装C"を配置
    3-3."衣装切り替え(MA Parameters後付)"のMA Menu Itemに次の変更を適用
        3-3-1."衣装B"のパラメータ値を1に変更    ※今回の問題に直接は関係ない操作ですが、このPrefabの本来意図する動作には必要な変更です。
        3-3-2."衣装C"のパラメータ値を2に変更    ※今回の問題に直接は関係ない操作ですが、このPrefabの本来意図する動作には必要な変更です。
    3-4."衣装切り替え(MA Parameters後付)"にAdd ComponentでMA Parametersを追加
    3-5."プレハブ開発者むけ設定を表示"にチェック
        3-5-1."True"の内部値にチェック    ※今回の問題に直接は関係ない操作ですが、このPrefabの本来意図する動作には必要な変更です。
        3-5-2."Cos_Menu"のパラメータ型をIntに設定、保存するにチェック    ※今回の問題に直接は関係ない操作ですが、このPrefabの本来意図する動作には必要な変更です。
    3-6."プレハブ開発者むけ設定を表示"のチェックを外す
    3-7."衣装切り替え(MA Parameters後付)"のMA Parametersに次の変更を適用
        3-7-1."衣装A"を"衣装Aリネーム"に変更
        3-7-2."Cos_Item_0(default)"を"衣装Aリネーム"に変更
        3-7-3."衣装B"を"衣装Bリネーム"に変更
        3-7-4."Cos_Item_1"を"衣装Bリネーム"に変更
        ※全てリネームすると"問題1"が発生するため、ここでは衣装Cをリネームしません。
    3-8.Playモードに入る

    問題は発生しません。すなわち、
    FXのパラメータリストに"衣装Aリネーム"と"衣装Bリネーム"のみがあり、
    "衣装A"、"Cos_Item_0(default)"、"衣装B"、"Cos_Item_1"が残っておらず、意図通りです。

    さらに手順続きます。

    3-9.Editモードに戻る

    ここでも問題は発生しません。すなわち、
    "衣装切り替え(MA Parameters後付)"のMA Parametersで、
    リネームしたパラメータがそのまま残っています。

    この手順では、MA Parametersが元々Prefabに入っていると問題発生し、
    ヒエラルキー上のインスタンスへ直接MA Parametersを追加した場合は問題が発生しないことを示しています。

---------------------------------------------------------------------------
■ 問題2が発生"しない"手順（その2）

    4-1."衣装切り替え(MA Parameters内包)"をアバター直下に配置
    4-2."衣装切り替え(MA Parameters内包)"の子として"衣装A"、"衣装B"、"衣装C"を配置
    4-3."衣装切り替え(MA Parameters内包)"のMA Menu Itemに次の変更を適用
        4-3-1."衣装B"のパラメータ値を1に変更    ※今回の問題に直接は関係ない操作ですが、このPrefabの本来意図する動作には必要な変更です。
        4-3-2."衣装C"のパラメータ値を2に変更    ※今回の問題に直接は関係ない操作ですが、このPrefabの本来意図する動作には必要な変更です。
    4-4."衣装切り替え(MA Parameters内包)"のMA Parametersに次の変更を適用
        4-4-1."衣装A"を"衣装Aリネーム"に変更
        4-4-2."Cos_Item_0(default)"を"衣装Aリネーム"に変更
        4-4-3."衣装B"を"衣装Bリネーム"に変更
        4-4-4."Cos_Item_1"を"衣装Bリネーム"に変更
        ※全てリネームすると"問題1"が発生するため、ここでは衣装Cをリネームしません。
    4-5."衣装切り替え(MA Parameters内包)"をAssetsフォルダにドロップし、Variant化
    4-6.Playモードに入る
    
    問題は発生しません。すなわち、
    FXのパラメータリストに"衣装Aリネーム"と"衣装Bリネーム"のみがあり、
    "衣装A"、"Cos_Item_0(default)"、"衣装B"、"Cos_Item_1"が残っておらず、意図通りです。

    さらに手順続きます。

    4-7.Editモードに戻る

    ここでも問題は発生しません。すなわち、
    "衣装切り替え(MA Parameters後付)"のMA Parametersで、
    リネームしたパラメータがそのまま残っています。

    さらに手順続きます。

    4-8."衣装切り替え(MA Parameters内包)"を右クリックからUnpack Prefabする
    
    ここで、リネームしたパラメータ名が太字になっており、Inspectorの左端には変更状態を表す色の付いたラインが表示されています。
    この後、Playモードに入ると問題発生しませんし、Editモードに戻っても問題発生しません。

    この手順では、Variant化したことにより問題が発生しないことを示しています。
    というよりは、リネームがインスタンスに対する"変更扱い"になっていることが、発生しない条件のような気がします。（私の想像です）
    Dirtyフラグ関連の問題のような気がします。
    4-4-1～4-4-4の手順で、リネームがインスタンスへの変更扱いになっていない
    （リネームした文字が太字になっておらず、変更を示すラインの表示もない）
    ことが原因のヒントのように想像します。
---------------------------------------------------------------------------

[test.zip](https://github.com/bdunderscore/modular-avatar/files/12566541/test.zip)

**Comment by bdunderscore** [comment]
詳しい再現例、ありがとうございます。Unity 2022移行後でこのUIを作り直す予定なので、その時対処しようと考えています。
