### ISSUE TITLE
Setup Outfitでのボーン検知にHumanoidも利用する?

### ISSUE THREAD

**Issue by Sayamame-beans** [bdunderscore/modular-avatar#429]
キセテネでは着せられて、MAのSetup Outfitでは正しく着せられない例として、ボーン名にtypoがあるなどのケースがあるようです。
(衣装で`Foot_R_01`が想定されていそうなボーン名が`Foo_R_01`とtypoされていました。ちなみにアバター側のボーン名は`Foot.R.001`)
ボーン名だけで考えれば、キセテネもこれを着せることは出来ないのですが、キセテネはボーン名による確認より先にHumanoidのボーン情報を取得する処理があります。(当該衣装がAnimator付きでHumanoidである場合、Humanoidからボーン情報を取得し、足りない分をボーン名で探す、という感じです)
これにより、ボーン名が正しくなくてもHumanoidの設定が正しければキセテネは着せることが出来る、ということのようでした。

MAのSetup Outfitでもこのような処理を含んでも良いのではないか?と思ったため、issueを書きました。

参考: KiseteNe for MAでの当該処理部分です。
`<= (int)HumanBodyBones.RightToes`の部分は恐らく`< (int)HumanBodyBones.LastBone`と読み替えても特に問題ないはずです。
https://github.com/Sayamame-beans/KiseteNe-for-MA/blob/5a5d4674dc6befc4c946207757f9b4b6bf87bef1/Editor/KisekaeEditor.cs#L374-L379

**Comment by bdunderscore** [comment]
1.8.0 移行の実装となりそうです（1.7.xは緊急のバグ修正のみにし、なでもふの仕上げに集中していますので）

**Comment by KisaragiEffective** [comment]
別方面での需要: FBX形式のポータビリティが欠けるためDAE形式でエクスポートした際にHipsボーンがトップに来てしまい不都合らしい ([にりらみすきー部](https://misskey.niri.la/notes/9s0lwfn7uz))
