### ISSUE TITLE
MA Mesh Settingsの設定の細分化

### ISSUE THREAD

**Issue by nashikan** [bdunderscore/modular-avatar#432]
MA Mesh Settingsの"Bounds 設定"で"設定/継承/設定しない"の切り替えをすると
"Root Bone"と"Bounds(Center/Extent)"に対して影響しますが、
"Root Bone"と"Bounds(Center/Extent)"に対して個別に"設定/継承/設定しない"の切り替えができるとよいと思いました。

■ ユースケース

"もっちりシェーダー"では、導入手順で指示されたプレハブをRoot Boneにセットする必要があります。
このとき、アバタールートにMA Mesh Settingsを配置し"Bounds 設定"を"設定"にすると、
Play時の"Root Bone"はセットしたプレハブではなく、アバタールートのMA Mesh Settingsで設定したボーン(例えばHip)で上書きされてしまいます。
"Bounds 設定"を"設定しない"にすると"Root Bone"はプレハブがセットされますが、今度は"Bounds(Center/Extent)"を上書きすることができません。

現状の対応としては、
"もっちりシェーダー"を導入したいSMRの付いたオブジェクトに追加でMA Mesh Settingsを配置、"Bounds 設定"を"設定"にして
"Root Bone"にプレハブをセットして"Bounds(Center/Extent)"は任意の値(基本的にはアバタールートのMA Mesh Settingsと同じ値)とします。(ここで"Bounds(Center/Extent)"を改めて値指定するのが手間という程度の話ではあります。)

**Comment by bdunderscore** [comment]
Bounds Center/ExtentはRoot BoneのTransformを基準とする値なので、特殊な事情がない限り一括で設定する必要があると思いこの使用にしてました。特に、スケールが設定されてる場合はバウンズの大きさが大幅に変動して事故につながりかねないです。この辺の事故を回避する代わりにこのようなレアケースの手数が多少増えても仕方ないかなと考えています。

なお、ワールドスペースで指定するというてもありますが、スケール・回転などの事情で必ずランタイムでずれるので、あたかも同じバウンズになってるかのように見せるのもどうかなと思いますのでそのような実装にしなかった。したがってこのissueに関しては申し訳ないけど採用できません。

ただし、プラグインシステムの開発が進んでいますので、それがでたら「もっちりシェーダー」の作者さん側でMAのセットアップを簡易化するロジックを組むことも可能になるかと思います。

もう一つの対策としては、あえてアバター全体でその指定のプレハブをroot boneにする、という対策もできます。
