### ISSUE TITLE
アクセスしたURLの末尾に`/`が含まれると、ドキュメントの一部リンクが繋がらなくなる

### ISSUE THREAD

**Issue by Sayamame-beans** [bdunderscore/modular-avatar#443]
例
https://modular-avatar.nadena.dev/ja/docs/reference/menu-item/
> `[こちらのチュートリアル](https://modular-avatar.nadena.dev/ja/docs/reference/tutorials/menu)`
実際にはhttps://modular-avatar.nadena.dev/ja/docs/tutorials/menu/

> `[Menu-Installer](https://modular-avatar.nadena.dev/ja/docs/reference/menu-item/menu-installer)`
実際にはhttps://modular-avatar.nadena.dev/ja/docs/reference/menu-installer/

(相対パスで1つ上がり忘れている?)

**Comment by Sayamame-beans** [comment]
どうやら、アクセスした際のURLの末尾に`/`があるかどうかで結果が変わってしまっているみたいです

**Comment by bdunderscore** [comment]
Fixed in https://github.com/bdunderscore/modular-avatar/commit/587084ffb7bec6ff818fb48ac0984dfd10bbd9a7

**Comment by Sayamame-beans** [comment]
まだ全ては直っていないようです。
https://github.com/bdunderscore/modular-avatar/blob/af7a9c03bae716bc85779c5a6df8ffba07b3ffe3/docs/docs/reference/menu-item.md?plain=1#L9
https://github.com/bdunderscore/modular-avatar/blob/af7a9c03bae716bc85779c5a6df8ffba07b3ffe3/docs/docs/reference/menu-item.md?plain=1#L34-L35
などは実際に直っていないことを確認しています。(日本語版も同様)

**Comment by bdunderscore** [comment]
設定変更で、末端に/のURLが404になるようにしました。
