### ISSUE TITLE
1.8.0-beta.0におけるアバターアップロード時のエラー

### ISSUE THREAD

**Issue by amehuri** [bdunderscore/modular-avatar#453]
Modular Avatarを1.7.7→1.8.0-beta.0に更新してアバターをアップロードしようとすると以下のエラーが出てアップロードに失敗します。1.7.7に戻すとアップロード可能です。

- Packages\nadena.dev.modular-avatar\Runtime\ArmatureAwase\TransformState.cs(30,13): error CS0103: The name 'Undo' does not exist in the current context
- Packages\nadena.dev.modular-avatar\Runtime\ArmatureAwase\TransformState.cs(30,37): error CS0103: The name 'Undo' does not exist in the current context
- Packages\nadena.dev.modular-avatar\Runtime\ArmatureAwase\ArmatureLockController.cs(77,13): error CS0103: The name 'AssemblyReloadEvents' does not exist in the current context
- Packages\nadena.dev.modular-avatar\Runtime\MAMoveIndependently.cs(125,25): error CS0103: The name 'Undo' does not exist in the current context
- Packages\nadena.dev.modular-avatar\Runtime\MAMoveIndependently.cs(125,50): error CS0103: The name 'Undo' does not exist in the current context

VCCで併用しているツール群はこちらになります。

![image](https://github.com/bdunderscore/modular-avatar/assets/110208161/5a571a01-da68-4bd7-acf5-675c10d8258d)

その他、以下のツールを導入しています。
- VRCHierarchyHighlighter
https://booth.pm/ja/items/1326573

- Unity高画質スクショツール
https://booth.pm/ja/items/4364665

- Lightbox Viewer
https://booth.pm/ja/items/3870813

- Animation Viewer
https://booth.pm/ja/items/3625699

- Unity / AnimationClipPathReplaceTool
https://booth.pm/ja/items/4445453

- [ACT]AnimationClipTools
https://booth.pm/ja/items/4840483

- PhysBoneを骨から抜くやつ(PBReplacer)
https://booth.pm/ja/items/3815413

- VRCLensをModularAvatarで導入するやつ
https://booth.pm/ja/items/4885661

- VRCLens
https://hirabiki.gumroad.com/l/rpnel

- unity-overwriter
https://github.com/ina-amagami/unity-overwriter

**Comment by anatawa12** [comment]
#449 と同一でしょうか

**Comment by amehuri** [comment]
同じですね。既にissueありましたか、失礼しました。

**Comment by bdunderscore** [comment]
beta.1で修正済み
