### ISSUE TITLE
Modular Avatar isn't working on arms of avatar.

### ISSUE THREAD

**Issue by Resmae** [bdunderscore/modular-avatar#460]
Hi, so far I have been using Modular Avatar to add different outfits to my avi and it has been working great without issue. However when I tried to add this outfit, it does not animate the arms correctly. I am using Gogoloco and Gesture manager to test and it has worked with all the other outfits I have used modular avatar on, and it's half working on this one. The torso works great with no issues but for whatever reason the arms are not. I've also made sure the bone names are the same as all the other outfits that have worked but still no luck. Any advice on how to better debug or fix this would be amazing. 
Thank you!!
![image](https://github.com/bdunderscore/modular-avatar/assets/128424748/08c5e383-a0d5-42d9-9f99-a85631c40b0e)

**Comment by bdunderscore** [comment]
Can you please show the hierarchy of your avatar and your ourfit?

**Comment by Resmae** [comment]
Hierarchy of Avi
![image](https://github.com/bdunderscore/modular-avatar/assets/128424748/5b15b4ee-d0ee-45e5-8847-8ad2371848f8)
![image](https://github.com/bdunderscore/modular-avatar/assets/128424748/8beb04b4-6afc-4754-a3fe-49eedc450338)

Hierarchy of working outfit
![image](https://github.com/bdunderscore/modular-avatar/assets/128424748/0c5c2470-73a0-4f09-9859-a5a761a754e0)

Hierarchy of not working outfit
![image](https://github.com/bdunderscore/modular-avatar/assets/128424748/0a513f11-319c-46da-bda0-8210c71efc56)

**Comment by bdunderscore** [comment]
It looks like MA didn't recognize the base armature's shoulder due to it being named "Sholder" and wasn't able to match it up with the outfit as a result. If you rename the bones of the outfit to match the base armature things should work.
