### ISSUE TITLE
BlendShape Syncのアニメーション生成機能が動いてない

### ISSUE THREAD

**Issue by anatawa12** [bdunderscore/modular-avatar#461]
anatawa12/AvatarOptimizer#521 の調査の最中に発覚しました。

`MAContext(context).AnimationDatabase.Commit();`がBlendshapeSyncAnimationPluginPassいこうに呼ばれてないのが原因な気がします。

1.8.0-beta.1

**Comment by bdunderscore** [comment]
長期的にはExtensionContextに変えたいけど、TrackObjectRenamesContextとの関係は要検討ですね…
