### ISSUE TITLE
衣装側で PhysBone の影響下にあるボーンは、アバター側に同名のボーンがあっても統合すべきではない

### ISSUE THREAD

**Issue by nekobako** [bdunderscore/modular-avatar#464]
衣装側で PhysBone の影響下にあるボーンは、アバター側に同名のボーンがあっても統合すべきではないと思います。
例として以下のような構造で、衣装側の Skirt_Root の PhysBone にアバター側の Skirt_Root の PhysBone とは異なるパラメータが設定されていることがあります。

```
- アバター
  - Armature
    - Hips
      - Skirt_Root (PhysBone)
        - Skirt_0
        - Skirt_1
        - ...
  - 衣装
    - Armature (MAMergeArmature)
      - Hips
        - Skirt_Root (PhysBone)
          - Skirt_0
          - Skirt_1
          - ...
```

この場合、衣装製作者はおそらく衣装を手作業で着せることを想定しており、Hips まではアバター側の同名のボーンに入れ子にして欲しいが、Skirt_Root は元の Hips の下から移動させないで欲しいという (暗黙の) 意図があるはずです。
現在の MA では、衣装側の Skirt_Root はアバター側の Skirt_Root に統合され、そのあと重複した PhysBone を削除するようになっていますが、これにより衣装側の PhysBone の設定が失われてしまいます。

最近では、ライムちゃん用の「おはツイメイド」が以下のような構造でした。

```
- アバター
  - Armature
    - Hips
      - Skirt_Root (PhysBone)
        - Skirt_0
        - Skirt_1
        - ...
  - 衣装
    - Armature (MAMergeArmature)
      - Hips
        - Skirt_Root
          - Skirt_0 (PhysBone)
          - Skirt_1 (PhysBone)
          - ...
```

この場合も同様に、Skirt_N が統合されて衣装側の PhysBone の設定が失われてしまいます。

**Comment by bdunderscore** [comment]
これについてはよい変更ですが、ヒューマノイドボーンの場合はエラーを表示するべきかなと考えています

**Comment by nekobako** [comment]
Humanoid ボーンに影響する PhysBone が存在する状況があまり思い付かないですが、もしそのような状況があればなぜ統合されなかったか分からなくなるので、たしかにエラーはあった方がいいですね。
