### ISSUE TITLE
Global toggle for ArmatureLockController

### ISSUE THREAD

**Issue by GotoFinal** [bdunderscore/modular-avatar#484]
While the sync in editor is very useful, with a lot of armatures it causes quite high load in editor, would be great to have some kind of global toggle so you can quickly go between the modes without visiting every armature

**Comment by bdunderscore** [comment]
How many armatures are you merging? With 11 armatures I measured this taking about 1.3 ms per editor frame, which seems acceptable still.

**Comment by GotoFinal** [comment]
20-30 with many duplicates of bigger armatures that are not actually getting fully used after build, its nothing horrible, but multiple ms going into single addon per frame that is always active is a bit much, as seems that the cost is there even if im not currently moving bones. So its not a serious issue so far, but i feel like this feature is heavy enough that should be easier to toggle on global level.

**Comment by bdunderscore** [comment]
I'll also note that I've observed a number of users having issues with accidentally (?) toggling off "apply on play" and getting confused about why things aren't working. I'd prefer to avoid adding more global toggles that might cause similar problems.
