### ISSUE TITLE
1.8.0 Stuck on build

### ISSUE THREAD

**Issue by Dartv** [bdunderscore/modular-avatar#485]
![](https://i.gyazo.com/b482dab97579d1d7e228809de8521aee.png)

Whenever I try to build & upload an avatar it gets stuck on "Building Avatar". No errors in console, it just creates a duplicate object in hierarchy and never deletes it.
Downgrading to 1.7.7 fixes the issue.
Tried different versions of avatar, same issue.

**Comment by bdunderscore** [comment]
What other editor extensions do you have installed? And what version of the VRCSDK do you have installed?

**Comment by Dartv** [comment]
Eliminated down to a single VCC package. After removing it, builds fine. Closing
