### ISSUE TITLE
アバター側の Transform の Scale が均一でないと、衣装側の PhysBoneCollider の位置がずれる場合がある

### ISSUE THREAD

**Issue by nekobako** [bdunderscore/modular-avatar#498]
下記の条件をすべて満たすとき、衣装側の PhysBoneCollider の位置がずれるようです。
- アバター側のオブジェクト A と衣装側のオブジェクト A' のパスと名前が一致している
- A の Transform の Scale が均一でない (X/Y/Z が一致していない)
- A' に PhysBoneCollider がアタッチされており、その Shape の Position が (0, 0, 0) でない

例として、こまどさんのカリンちゃんと公式衣装であるシュガリーブティックのフリルビキニにはどちらも PhysBoneCollider がアタッチされた `PBCollider_UpperLeg_(L|R)` というオブジェクトがありますが、カリンちゃん側は Transform の Scale の X が 0 になっており、フリルビキニ側は PhysBoneCollider の Shape の Position が (0, 0, 0) ではないため、衣装を着せたときに PhysBoneCollider の位置がずれてしまいます。

アバター側のオブジェクトのスケールが均一でないのがおかしいため対応しない、ということであれば Close してください。

**Comment by bdunderscore** [comment]
スケールが均一でない場合はそもそもUnity、PhysBoneの挙動が怪しくなりますので非推奨にしたいところですが、非対応衣装を導入するときなどは確かに袖の太さをいじるなどの調整がしたいですね・・・

マージ前にメッシュに適用してスケールをただすという処理が必要になりそうなのですが、それだと副作用もでそうなので少し考えさせてください。

**Comment by bdunderscore** [comment]
1.9 に追加された Scale Adjuster を使って均一でないスケール調整ならうまくいくかもしれませんので、そっちのほうをお試しください。
