### ISSUE TITLE
サブメニューからメニューの展開ボタンを押したとき、itemの名前が"menu"だと展開に失敗する

### ISSUE THREAD

**Issue by ni1chigo2115** [bdunderscore/modular-avatar#499]
https://booth.pm/ja/items/4908254
こちらの支援ツールを使ったときに問題が発覚しました。
編集の為にメニューファイルへの依存を減らすため展開していたのですが、どうもうまくいかなかったので・・・

**Comment by bdunderscore** [comment]
![image](https://github.com/bdunderscore/modular-avatar/assets/64174065/d207bf8f-7603-4e64-815b-17be23897787)
再現してみたところ、無事に展開できましたが、何かエラーなどでましたか？

**Comment by ni1chigo2115** [comment]
確認してみます
しばらくお時間使いますね
