### ISSUE TITLE
Marge Armatureの"位置を固定"機能が消えている

### ISSUE THREAD

**Issue by RsFlux1710** [bdunderscore/modular-avatar#507]
1.8.0以降、Merge Armatureに新機能が追加されましたが、以前の"位置を固定"に当たるものが存在しない為、Issueを立てさせて頂きました。
この変更により、"位置を固定"で可能だった「ボーンスケールを弄ったアバターに対して、衣装側のボーンスケールを統一する」ことができなくなっており、困っています。
"位置を固定"機能の復活、もしくは代替機能の実装を検討していただけると幸いです。

**Comment by bdunderscore** [comment]
![image](https://github.com/bdunderscore/modular-avatar/assets/64174065/e788647a-b53b-472f-8e81-8125f0c9b961)

この設定にしてみてください。以前の挙動と同じになるはずです（もし挙動が違ったら対処します）
