### ISSUE TITLE
メニューのインストール順がランダムに生成される

### ISSUE THREAD

**Issue by Narazaka** [bdunderscore/modular-avatar#508]
下記のように個別でMenu ItemとInstallerをセットで設定し、インストール先を単一の親メニューに設定した場合……
![image](https://github.com/bdunderscore/modular-avatar/assets/1712548/4b5263f7-1cec-485b-bdea-347d0198ce6d)
![image](https://github.com/bdunderscore/modular-avatar/assets/1712548/2d1d38d9-f383-4f8e-848c-cad57a758621)

メニューの順序がランダムになってしまう。
![image](https://github.com/bdunderscore/modular-avatar/assets/1712548/7304cafd-24a4-48ba-83c1-12d41a650e34)

現状メニューの順序はprefabの置いた順である程度決まってくるが、これがランダムになるとなるとメニュー構築に支障がある。

理想的には俯瞰可能で順序を弄れるメニューマネージャーなどがあると良いが、目下困るのでとりあえず立てる。

- そもそもなぜ個別にinstallerをアタッチしているのか
  - これは大量の選択肢を自動生成するようなアセットで、そのメニュー階層を自由に組み替えたい需要に応えるためにこうしています。　（ https://github.com/Narazaka/AvatarParametersSaver ）

**Comment by Narazaka** [comment]
アー自動で作られるインストールターゲットというのを動かせば一応イケるのか……
その自動生成時にランダムになるって感じですね

**Comment by bdunderscore** [comment]
以下のユニットテストで再現してみたところ、再現できませんでした。再現できるプレハブを用意できますか？

```
        [Test]
        public void MenuInstallerPreservesVisitOrder()
        {
            var root = CreateRoot("root");

            for (int i = 0; i < 4; i++)
            {
                var child = CreateChild(root, "C_" + i);
                var installer = child.AddComponent<ModularAvatarMenuInstaller>();
                var item = child.AddComponent<ModularAvatarMenuItem>();
                item.Control.name = child.name;
            }

            var insertion = CreateChild(root, "Inserted");
            var i_installer = insertion.AddComponent<ModularAvatarMenuInstaller>();
            var i_item = insertion.AddComponent<ModularAvatarMenuItem>();
            i_item.Control.name = insertion.name;
            insertion.transform.SetSiblingIndex(2);
            
            var virtualMenu = VirtualMenu.ForAvatar(root.GetComponent<VRCAvatarDescriptor>());

            var itemNames = virtualMenu.RootMenuNode.Controls.Select(c => c.name).ToArray();
            Assert.AreEqual(itemNames, new[] {"C_0", "C_1", "Inserted", "C_2", "C_3"});
        }
```

**Comment by Narazaka** [comment]
[tes.zip](https://github.com/bdunderscore/modular-avatar/files/13330891/tes.zip)

ごく一般的な感じでparent(submenu)と子メニューどちらもmenu itemで、menu itemをヒエラルキー上で一括選択して「メニューを選択」から設定するとオブジェクト順とは無関係な順序でinstall targetが生成されます
![image](https://github.com/bdunderscore/modular-avatar/assets/1712548/cacb582e-8885-4c7d-9b07-13d23dec9261)

**Comment by bdunderscore** [comment]
理解しました。複数選択したときのSelect Menuのほうの挙動ですね（ビルド時の処理の問題かと勘違いしてました）
