### ISSUE TITLE
Expression Parametersを未指定の場合、128bit予約されてしまう

### ISSUE THREAD

**Issue by Narazaka** [bdunderscore/modular-avatar#510]
Expression Parametersを未指定で全てMAのみでメニュー等を構築した場合、VRCデフォルトのパラメーターをもってくるために`VRCEmote`をはじめとする空のIntまでの無駄パラメーターが冒頭についてしまう。

空のパラメーターファイルを指定することで回避可能ではあり、また理解可能ではあるが、地味に混乱する挙動だと思います。

**Comment by bdunderscore** [comment]
VRChatアバターにおいて、Expression ParametersとExpression Menuを設定しない場合はデフォルト設定が採用されます。MA を導入し追加した場合はこの設定を維持する意図的な使用です。

とはいえエラーリポートに注意ぐらいは出した方がよさそうですね。
