### ISSUE TITLE
Visible Head Accessory が ビルドターゲットがQuestの時にも動作する

### ISSUE THREAD

**Issue by ReinaS-64892** [bdunderscore/modular-avatar#513]
ドキュメントには
> 技術的な制約により、Quest単体では動作できません。Quest向けのビルドはつけたままにしてもいいが、効果は発揮しません。

とありますが、ビルドターゲットが Quest (Android) の時の マニュアルベイク で動作していて、コンストレイントが生成されてしまいます。

望ましい挙動としては、ビルドターゲットが Quest (Android) の時に動作せず、コンストレイントが生成されないことだと思います。

**Comment by bdunderscore** [comment]
あれれ、これQuestで無効化するつもりで作って実はできてなかったのか・・・指摘ありがとうございます！
