### ISSUE TITLE
MA World Fixed Object使用時、正常にアニメーションしない場合がある

### ISSUE THREAD

**Issue by wwr-alliance** [bdunderscore/modular-avatar#519]
「MA World Fixed Object」を付けた同名のGameObjectが複数存在する場合、パスが重複して正常にアニメーションができなくなってしまう場合があるようです。

**Comment by bdunderscore** [comment]
具体的な例はありますか？
元々同名になっている場合、もともとのアニメーションでも参照ができないように思えますので、具体的な例と、期待される効果を教えていただけると幸いです。

**Comment by wwr-alliance** [comment]
【具体例】
「Item_A」「Item_B」という2つのPrefabをアバター直下に配置します。
![image](https://github.com/bdunderscore/modular-avatar/assets/149392059/201af515-613f-4075-a15f-26b7ac6adc54)
- Item_A, Item_B: 「MA Merge Animator」が付いています
- World: 「MA World Fixed Object」が付いています
- Local: 「MA Merge Animator」でアニメーションさせたいオブジェクトです

上記の状態で実行（適用）すると、下記のような構造に変わります。
![image](https://github.com/bdunderscore/modular-avatar/assets/149392059/94569e13-5878-4e47-b599-56fa09e01584)
同名オブジェクトが(MA WorldFixedRoot)の下に移動された事により、パスが重複してしまう問題が発生します。
