### ISSUE TITLE
Setup Outfit等で利用されるHeuristicBoneMapperにおいて、breast系に対応して欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [bdunderscore/modular-avatar#523]
話題元: https://twitter.com/comyui_211vt/status/1722973592114139527
> そいえばMAでbreast.LがLeftBreastに統合されなかったりする

現在、breast系はHeuristicBoneMapperでサポートされていません。
anatawa12氏によると、HeuristicBoneMapperではそもそも非Humanoidが想定されていないとのこと…?
( https://twitter.com/anatawa12_vrc/status/1722979233671061508 )
そのため、アバターでよく用いられる一部の非Humanoidなオブジェクトもサポートして欲しいと思いました。
よく用いられる非Humanoidなオブジェクトはbreast系以外特に思いつかなかったので、一旦それのみのリクエストとなります。

breast系の名前に含まれていた記憶がある文字列は、(ignorecaseで)
`breast, bust`
左右の識別はarm, leg系と同様に行われていると推測します。
https://twitter.com/comyui_211vt/status/1722982287090851924 によれば、`LeftBreast, LeftBreast_01, breast.L` その後に`.001, _end`。
推測ですが、Breast_Leftみたいなのもあり得そうな気がします。

**Comment by bdunderscore** [comment]
んー非対応衣装向けかな？
元々ヒューマノイドボーン以外はおそらく位置などが合わないだろうという想定でマッチングしてなかったけど、対応衣装でもこういうパターンありますか？

**Comment by bdunderscore** [comment]
あと胸の場合、複数ボーンに分けられてる場合も多いので、ルートだけでは正しく揺れない可能性が高いように思えます・・・

**Comment by Sayamame-beans** [comment]
追記を忘れていたので: https://twitter.com/comyui_211vt/status/1724053026871386252

また、[キセテネ改良版](https://booth.pm/ja/items/3952537)や[キセテネ v1.0]()には胸ボーンへの対応が入っているようで、(アバター個別の対応は流石に必要ないと考えますが、)他のHumanoidボーンと同程度の扱いはしても良いように感じています。
(キセテネで着せられる衣装がMAで着せられない、という現象の原因の1つだと考えます)

**Comment by bdunderscore** [comment]
現時点では、壊れるケースのほうが多そうなので見送らせていただきます。

**Comment by anatawa12** [comment]
FYI: 「非対応衣装を着せようとするとキセテネでは上手くいくのにMAでは胸ボーンが統合されない」というのがまぁ言われる模様です。胸ボーンの数が同じ場合とか何かしら条件有りであると嬉しそうなきはしています

https://x.com/KinoriaVR/status/1748279088325042598?s=20
