### ISSUE TITLE
Scale value sync of Lock Position (Position Sync mode)

### ISSUE THREAD

**Issue by 5drake** [bdunderscore/modular-avatar#524]
In versions up to ~1.7.4, the Lock Position of the MA armature would sync the scale value of the avatar's bones, but in later versions, the scale value is not sync.
If this is the intended change, it would be nice to have the option to sync scale values again.

**Comment by bdunderscore** [comment]
This is a bug, not an intended change

**Comment by 5drake** [comment]
If so, will this be fixed in a future version?

**Comment by bdunderscore** [comment]
I just went and tested this - in both bidirectional and unidirectional sync modes, scale was properly synced in my test case (Kikyo + Blanchir outfit). Can you provide more specifics about what you're doing?

**Comment by 5drake** [comment]
I fixed the scale value of my avatar's both leg (Manuka, but other avatars have the same problem) to 0.9, but when I use setup outfit, the scale value of the outfit doesn't change.

**Comment by bdunderscore** [comment]
Got it. The lock mode in the current version tries to avoid making changes to your outfit and avatar when it's initially enabled. A new feature is being added to the next version which will let you do that initial sync, and then if you want you can enable unidirectional or bidirectional lock mode afterward: https://modular-avatar.nadena.dev/dev/docs/reference/merge-armature#reset-position-to-base-avatar

**Comment by 5drake** [comment]
Thank you so much
The vrchat users are benefiting greatly from your efforts.

**Comment by bdunderscore** [comment]
Closing as fixed by #521
