### ISSUE TITLE
Replace Object breaks Armatures when replacing bones

### ISSUE THREAD

**Issue by konsti219** [bdunderscore/modular-avatar#547]
I have a prefab that needs to replace humanoid bones (like `UpperLeg`) to add constraints to those bones. The `Replace Object` MA components works perfectly for that.

However, this now breaks when I have another prefab (outfit) that uses `Merge Armature` to attach bones. This outfit includes new Phys Bone chains that are attached to the humanoid bone (like `UpperLeg`) being replaced by the other prefab.

Both prefabs work fine when used individually, but when used on the same avatar the following happens (my best guess):
`Merge Armature` [runs first](https://github.com/bdunderscore/modular-avatar/issues/308#issuecomment-1657120913) and correctly combines the two armatures. The `Replace Object` runs and replaces the humanoid bone. At this point, the connection between the mesh of the outfit and the moved bone under the replaced object seems to get lost. Then the remove useless object pass entirely removes the object for the new phys bone chain. This results in missing transforms on anything that was referencing the bones, and more importantly, anything that was weighted to the bones is now stuck at 0,0,0.

**Comment by bdunderscore** [comment]
Can you provide more details of your use case? I'm not sure why you would attach a physbone chain to a humanoid bone like UpperLeg. Ideally, some screenshots of the objects and heirarchy in question would be good (if you can distribute a unitypackage based on a CC0 avatar or something that would be even better!)

**Comment by konsti219** [comment]
> attach a physbone chain to a humanoid bone like UpperLeg

Attach as in just have child bones which are used as phys bones. The hierarchy of the outfit looks like this:

```
UpperLeg
  PhysBoneChain_Root
    PhysBoneChain_0
      ...
  LowerLeg
    ...
```

**Comment by konsti219** [comment]
I looked into it a bit more and found that `Replace Object` seems to act totally unpredictably when replacing any kind of bone and `Merge Armature` is not actually relevant.

**Comment by konsti219** [comment]
I found the issue! [Here](https://github.com/bdunderscore/modular-avatar/blob/aa698565abbdeb9d135bd817cd9459c4448fcebe/Editor/ReplaceObjectPass.cs#L87) the children are being iterated while the children are being modified. This causes half of the children to get dropped. I'm going to make a PR.
