### ISSUE TITLE
Using Merge Animator with 0 weight layers

### ISSUE THREAD

**Issue by ZenithVal** [bdunderscore/modular-avatar#554]
The first layer in an animator is forced to have a weight of 1. This is a problem if you'd like to use Merge Animator on a single Parameter driver Layer, which in some cases will have a weight other than 1.

When the driver layer is alone and the first in the list, you can not change it's weight from 1.
![image](https://github.com/bdunderscore/modular-avatar/assets/88603991/6ef201d8-78e3-4456-be48-7a0592065840)

When an empty placeholder layer is placed at the top, we can freely adjust the driver layer.
![image](https://github.com/bdunderscore/modular-avatar/assets/88603991/cb16c25f-2a10-45c3-adc1-db271f36caa9)

Possible solutions:
- Remove/Ignore any layers with no states. That way "Base" in the above example would be removed.
- Remove any layers of a specific name such as "Ignore."

**Comment by bdunderscore** [comment]
1.9.0 will add an optimization pass to prune empty layers.
