### ISSUE TITLE
Unity 2022 no Modular avatar in menu

### ISSUE THREAD

**Issue by Tsagu** [bdunderscore/modular-avatar#556]
After updating to the new Unity 2022 build Modular Avatar is not appearing for me in the context menu any longer.

**Comment by bdunderscore** [comment]
Please check whether you have any red compile errors in your console window. They should stick around if you click "clear", so this should help you find them. If an unrelated asset isn't compiling, it will also break Modular Avatar.

**Comment by Tsagu** [comment]
Yeah I feel stupid, apparently VCC despite saying it was loading, only loaded the framework, not the actual modular avatar. Got it working.
