### ISSUE TITLE
[BUG?] [Unity2022] Setup Outfit後、その操作をUndoするとUnityがクラッシュする

### ISSUE THREAD

**Issue by Sayamame-beans** [bdunderscore/modular-avatar#571]
タイトル通りです。通常のRedo/Undoでは問題がなく、Setup OutfitをUndoしようとするとクラッシュが発生します。

## Environment
Unity: 2022.3.6f1
VRChat Package Resolver Tool: 0.1.27
VRChat SDK - Base/Avatars: 3.5.0
Modular Avatar: 1.8.4
ndmf: 1.2.5

**Comment by bdunderscore** [comment]
Unity 2022.3.15f1 で再現したのでUnityにバグ報告を投げます。

**Comment by bdunderscore** [comment]
IN-64465

**Comment by bdunderscore** [comment]
https://issuetracker.unity3d.com/issues/crash-on-transformaccessclearcallback-when-undoing-modularavatar-setup-outfit
