### ISSUE TITLE
World Fixed ObjectがQuest向けビルドで無効になっていない

### ISSUE THREAD

**Issue by kurotu** [bdunderscore/modular-avatar#581]
ビルド中にParentConstraintが生成されるため、VRCSDKのバリデーションによってエラーとなりアップロードに失敗します。
Visible Head Accessoryと同様にビルド時に何もしないのが期待動作かと思います。

- Modular Avatar: 1.8.4

**Comment by bdunderscore** [comment]
うーん、World Fixed ObjectはQuestだとどう動作するべきかですね。該当オブジェクトを削除するべきか、それともワールド固定処理を省略するべきか・・・？

**Comment by kurotu** [comment]
該当オブジェクトを削除してしまうと、オブジェクトを出したときに表示されない原因の切り分けが難しくなってしまうように思います。以下の前提知識が必要になるためです。

- ワールド固定がQuestでは不可能である (Constraint使用不可)
- World Fixed ObjectがQuestビルドではオブジェクトを削除する

そのため、固定処理の省略にとどめた方が良いのではないかと思います。

あるいは、#586 によって動作とドキュメントが一致するようになったので、ビルド時にエラーを表示するだけというのも選択肢の一つかと思います。
現状だとWorld Fixed Objectが原因でアップロードできないことに気付くにはVRCSDKのエラー出力を読むしかないですが、非常に読みにくいです。
