### ISSUE TITLE
Move Independentlyは、微調整された時には発動しない

### ISSUE THREAD

**Issue by Sayamame-beans** [bdunderscore/modular-avatar#582]
メモ的なissue
> 浮動小数点は完全一致比較が通常色々と望ましくないので一定以上の動きで補正していますが、規定値の見直し、もしくは完全一致比較のテストをしてみてもいいかも
> https://misskey.niri.la/notes/9nqqfkz6p0
> あ、それと、補正を細かくすると、これも浮動小数点でエラーが蓄積する問題が起きるのでその対策も必要だったりします
> https://misskey.niri.la/notes/9nqqkk10go

**Comment by bdunderscore** [comment]
微調整の場合は浮動小数点のエラー蓄積を避けるためにこの仕様にしました。
とはいえ最適解ではないのはわかるので、調整前の状態を保存することでエラー蓄積を避けることを1.10をめどに視野に入れましょう。

**Comment by bdunderscore** [comment]
@Sayamame-beans 1.9.0-rc.0で治っているか、確認お願いします

**Comment by Sayamame-beans** [comment]
私が検証した際に微調整で反応しないことがあったのは、Move Independentlyが付いているボーンより親の方にあるボーンのscaleが100だったために発生しやすくなっていたことが分かりました。
その上で、1.9.0-rc.0では改善が見られませんでした。(特に変化が無いように見えます)
そのため、このscaleによるlocalの変化幅の小ささに原因があると考えられます。
対策があるとすれば…globalの方もorで追加確認するとかでしょうかね…?

**Comment by Sayamame-beans** [comment]
(参照用メモ) 動画はこちら
https://misskey.niri.la/notes/9nrc6swgts
https://misskey.niri.la/notes/9nrcdogdh9
