### ISSUE TITLE
Add a method to set humanoid bone as constraint source?

### ISSUE THREAD

**Issue by Sayamame-beans** [bdunderscore/modular-avatar#590]
#563 を見てて頭を過ぎったので一応? (意味が無さそうならcloseしてください)

**Comment by bdunderscore** [comment]
Bone proxyで連動するものを指定することはできないですか？

**Comment by Sayamame-beans** [comment]
対象が1つで、weightも1固定なのであればBoneProxyと同じだと思います。
対象が複数だったり、weightがバラバラな(或いはweightをアニメーションで変更するような)ケースは使い方としてあり得そうかな?と思います。

**Comment by bdunderscore** [comment]
サンプルの「ClapSample」に参照
