### ISSUE TITLE
Looking for Legacy Packages to Upgrade by Scanning Folders within nadena.dev.modular-avatar

### ISSUE THREAD

**Issue by kriomi** [bdunderscore/modular-avatar#605]
how should I deal with the issue?

**Comment by bdunderscore** [comment]
I'm not sure what the issue is. Can you please provide more details? Specifically:

1. What you were attempting to accomplish
2. What you tried
3. What you expected to have happen
4. What actually happened
5. Any logs or screenshots of the issue

**Comment by bdunderscore** [comment]
No response after three weeks, closing issue.
