### ISSUE TITLE
プレハブ開発者向け設定を表示時、MA Parameterの設定が保存されない場合があります

### ISSUE THREAD

**Issue by kakuchrome** [bdunderscore/modular-avatar#631]
複数のMerge Animatorを一つのObjectに設定されているPrefabをSceneでの編集時、MA Parameterの設定が保存されない場合があります
Merge Animatorをネスト下のObjectに分離すれば、ルート側のMA Parameterでは発生しないようです。

Environment
Unity: 2022.3.6f1
VRChat Package Resolver Tool: 0.1.27
VRChat SDK - Base/Avatars: 3.5.0
Modular Avatar: 1.8.4
ndmf: 1.2.5

--再現手段--
1.一つのGameObject内に二つのMA Animatorを設定した状態で、MA parameterを「プレハブ開発者向け設定を表示」をチェック。
2.MA parameter内の設定を変更し、プレイモードに入ってから編集モードに戻ると、Hierarchy上該当Prefabのパラメータが保存されない、もしくは空白欄として表示されます。

例：Scene内の「Rere_EarsEyeTracking_Debug」オブジェクト内のMA parameter「FT/v2/EyeY」を「Float・同期する」に変更し、
そのままレイモードに入ってから編集モードに戻ると、該当パラメータが保存されていない

問題をPrefabをApplyすると該当の現象が再現できなかったため、こちらSceneとしての状態でUnitypackegeを同梱いたします。

[ma_oarameter_debug.zip](https://github.com/bdunderscore/modular-avatar/files/14044000/ma_oarameter_debug.zip)

**Comment by bdunderscore** [comment]
Merge AnimatorのUIを書き直してる最中なので、それで解決されると思います。
ただし、書き直し版はUnity 2022以降のみ採用されます（Unity 2019は現行のUIで、深刻なバグを除き手つかずになると思います）

**Comment by bdunderscore** [comment]
開発ブランチで(Unity 2022では)書き直し済みなのでクローズします。
