### ISSUE TITLE
Feature request: Merge Parameters

### ISSUE THREAD

**Issue by IlexisTheMadcat** [bdunderscore/modular-avatar#668]
I love the Merge Animator feature and menu items that can unpack menu asset files, but I've had to manually define which parameters in an animator had to be synced using MA Parameters.

I have two inspectors while I make them match. Can we get an MA Merge Parameters component that takes a parameters asset as an input? Maybe to replace the existing MA Parameters component? Or both, I could see the latter still having a use. 
![image](https://github.com/bdunderscore/modular-avatar/assets/50256109/936ab2b1-992d-4865-bbd1-107abb17598e)

**Comment by bdunderscore** [comment]
There's some extra settings in MA Parameters, so we'll never get rid of it entirely. I'll consider this for 1.9.1 or 1.10.

**Comment by hazre** [comment]
I was trying to convert some prefabs from VRCFury to MA and this is the only blocker of it.

**Comment by IlexisTheMadcat** [comment]
Gonna bump this, as it was a planned feature but I never saw it. Keep up the great work though!
