### ISSUE TITLE
アニメーター間でパラメーター型が一致しているのにFloatへ変換してしまう / トランジションの調整に失敗している

### ISSUE THREAD

**Issue by Rerigferl** [bdunderscore/modular-avatar#669]
1.9.0-rc.1に [Siromori Eye Pointer](https://siromori.booth.pm/items/4742883) と FaceEmo を導入した時に発生するのを確認

`GestureLeft` / `GestureRight` をFloatで登録しているアニメーターが存在していないのにFloatに変換してしまっている？

また、トランジションの調整にも失敗していそう
![image](https://github.com/bdunderscore/modular-avatar/assets/70315656/0b090bd2-ed64-4794-89d0-f183fbc92f3a)

`Equals`の変換ができてなさそう（`NotEquals`の変換は正常にできてそうでした）

**Comment by bdunderscore** [comment]
報告ありがとうございます。サブステートマシンのエントリー・Anyステートトランジションが正しく処理されてないようです。
