### ISSUE TITLE
missing bunch of meshs

### ISSUE THREAD

**Issue by sakada3** [bdunderscore/modular-avatar#672]
when i juse Git or SVN, for working on avatar in some multiple PCs..
MA relative Mesh`s are gone.

am i have to edit my .gitignore?

**Comment by bdunderscore** [comment]
Can you please describe your workflow in more detail? I’m not sure what you mean by relative meshes.

**Comment by sakada3** [comment]
I have 4pcs for working on avatars.
And I use nas with git for project.

My workflow is..
1. pull project
2. Edit(I use manual bake in merge some times)
3. Push project.

When I pull the project and trying to edit project on other pc,
Most meshs state are missing.

I think .gitignore make some temp "retargeted mesh" to ignore when push project.
Anyone can help me for how to set gitignore for including temp meshes?

**Comment by bdunderscore** [comment]
If you need to retain temporary meshes, you can find the asset containing them in the ZZZ_GeneratedAssets folder in the root of your Assets directory. I'd recommend you move them to some other location as each time you run manual back it'll overwrite the file with the same name as your avatar. That being said, you should probably think of these post-bake avatars as being like compiled output - typically you'd put the inputs into your VCS instead.

**Comment by sakada3** [comment]
Yes, I'm using the manual function by unpacking and organizing the assets that are generated each time I use it.

Is there any place other than the subfolder of the Assets folder where the mesh files are created?

Thanks for the answer!

**Comment by bdunderscore** [comment]
They should be embedded in the ZZZ_GeneratedAssets file. You can find where they are by clicking on the mesh in question in the field in the SkinnedMeshRenderer inspector; it'll ping it in the project window.
