### ISSUE TITLE
Scale Adjusterが無限ループを起こす

### ISSUE THREAD

**Issue by Rerigferl** [bdunderscore/modular-avatar#676]
環境: Unity 2022.3.6f1 + MA 1.9.0-rc.2

発生する原因がイマイチ特定できなかったのですが、

- Avatar
  - Armature
    - Hips ✔️ 
      - UpperLeg.L ✔️ 
      - UpperLeg.R ✔️ 
  - Costumes
    -  Costume (これと同じような構造の物が複数)
       - Armature.1
         - Hips ✔️ 
           - UpperLeg.L ✔️ 
           - UpperLeg.R ✔️ 
    
（✔️付きの場所にScale Adjusterを設定）

上記のようにScale Adjusterを複数個設定した後、Playモードから戻ってきたりUnityを再起動したりすると、Scale AdjusterのUpdateが繰り返されて最終的に操作が出来なくなってしまいます

**Comment by bdunderscore** [comment]
上記の構成を作ったところ再現できませんでしたが、Scale Adjuster自体がプレハブに入ってたりしていますか？

**Comment by bdunderscore** [comment]
（たぶん）再現できました。いまいち発生条件がわからないけど、プレハブ修正ロジックは全体的に見直しが必要っぽい・・・

**Comment by bdunderscore** [comment]
@Rerigferl #677 のPRで再度再現していただけませんか？実装がごっそり変わっているけど、（たぶん）設定は保持される。はず。
![image](https://github.com/bdunderscore/modular-avatar/assets/64174065/953d99a7-4071-4bbf-9408-b7200f099132)

**Comment by Rerigferl** [comment]
@bdunderscore 確認してみましたが直ってそうです！ありがとうございます🙏
