### ISSUE TITLE
アバターのアップロード方法

### ISSUE THREAD

**Issue by UnisakiStudio** [bdunderscore/modular-avatar#68]
AvatarModularのコンポーネントを追加した状態のアバターはVRChatのControlPanelのBuilderで、
「The following component types are found on the Avatar and will be removed by the client: ModularAvatarParameters, ModularAvatarMenuInstaller, ModularAvatarMergeAnimator」と表示され、ビルドができません。
正しいアバターのビルド方法は「メニュー→Tools→AvatarModular→Apply to current avatar」でビルド用のアバターを生成する方法以外ないでしょうか。
このやり方ですとApplyのたびにオブジェクトが増え、Apply後のアバターをいじるユーザーが出てきて非破壊であるという良い点が損なわれそうです。
またメニューの位置が分かりにくく「Apply to current avatar」をすることが分からないユーザーから「あなたの衣装を入れたらアバターがアップロードできないのだけれども」という問い合わせが多く届きそうです。

また、もし毎回アバターアップロード時に結合されるというイメージではなく、
アバターに服やツールを導入する際に一回だけPrefabをくっつけてApplyして着せるという使用イメージの場合は、
その後ずっとそのアバターのデータをユーザーが使用し続けることを考慮して、自動生成されるAnimatorControllerやMenu,Parameterのファイル名を読みやすくわかりやすいものにして欲しいです。
また、PrefabVariant等を使った管理をしにくいので、Unpackされたクローンを作成するのではなく、Prefabから変更されている状態を保持したままオブジェクトをコピーし、分かりやすい名前に変更して欲しいです。（「(Clone)」が付くのが不格好だと思うので）

（Unpackせずにクローンする方法は難しいのですが、選択状態の制限さえクリアできれば以下のURLのSendEventを使ったやり方でできるはずです）
https://answers.unity.com/questions/168580/how-do-i-properly-duplicate-an-object-in-a-editor.html

**Comment by bdunderscore** [comment]
> The following component types are found on the Avatar ~

これについては対策してそのままアップロードできるようになっているはずですが、どうやら対策がうまく行ってないっぽい？VRCSDKのバージョンとインストール方法（VCCかunitypackageか）を教えてください。

(Clone)になる点ですが、適用ボタンはあくまでもデバッグ用を想定していますので現時点は名前が適当ですね…

**Comment by bdunderscore** [comment]
確認しました。最新SDKで内部仕様変更が入ったようです。次のバージョンで修正します（その影響でv3.1.9以降のSDKが必須になります）

https://feedback.vrchat.com/feature-requests/p/sdk-offer-an-officially-supported-base-class-for-editor-only-components このキャニーにてより安定な実装方法を提案していますので良ければ投票をお願いします。
