### ISSUE TITLE
"error.rename_params.duplicate_parameter"に対応するローカライゼーションがない

### ISSUE THREAD

**Issue by anatawa12** [bdunderscore/modular-avatar#694]
"error.rename_params.duplicate_parameter"に対応するローカライゼーションがないため何も表示されなくなり情報が見えなくなる

![gtyhuhh](https://github.com/bdunderscore/modular-avatar/assets/22656849/5b0ba4f1-1617-45fa-83b7-790b888371b4)

**Comment by bdunderscore** [comment]
見直したらエラーではなく挙動を定義するべきと判断したのでその方針で修正します。
