### ISSUE TITLE
Armature Merge Error

### ISSUE THREAD

**Issue by milkboy77** [bdunderscore/modular-avatar#770]
![image](https://github.com/bdunderscore/modular-avatar/assets/106000834/fe68e73d-2d96-4043-b53c-8b3994c82a50)
This error is reported when I use Armature Merge with a merge target of Head, which never occurs in version 1.9.4.

Unity: 2022.3.6f1
NDMF: 1.3.7
MA: 1.9.7

Exception: Segment not found in FreeSegment
nadena.dev.modular_avatar.core.armature_lock.AllocationMap.FreeSegment (nadena.dev.modular_avatar.core.armature_lock.ISegment inputSegment) (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/AllocationMap.cs:117)
nadena.dev.modular_avatar.core.armature_lock.NativeMemoryManager.Free (nadena.dev.modular_avatar.core.armature_lock.ISegment segment) (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/NativeMemoryManager.cs:215)
nadena.dev.modular_avatar.core.armature_lock.ArmatureLockOperator`1[T].RemoveJob (nadena.dev.modular_avatar.core.armature_lock.ArmatureLockJob job) (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/ArmatureLockOperator.cs:230)
nadena.dev.modular_avatar.core.armature_lock.ArmatureLockOperator`1+<>c__DisplayClass41_0[T].<RegisterLock>b__0 () (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/ArmatureLockOperator.cs:169)
nadena.dev.modular_avatar.core.armature_lock.ArmatureLockJob.Dispose () (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/ArmatureLockJob.cs:78)
nadena.dev.modular_avatar.core.armature_lock.ArmatureLockController.RebuildLock () (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/ArmatureLockController.cs:175)
nadena.dev.modular_avatar.core.armature_lock.ArmatureLockController.set_Enabled (System.Boolean value) (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/ArmatureLockController.cs:121)
nadena.dev.modular_avatar.core.ModularAvatarMergeArmature.SetLockMode () (at ./Packages/nadena.dev.modular-avatar/Runtime/ModularAvatarMergeArmature.cs:129)
nadena.dev.modular_avatar.core.ModularAvatarMergeArmature.OnEnable () (at ./Packages/nadena.dev.modular-avatar/Runtime/ModularAvatarMergeArmature.cs:149)

**Comment by bdunderscore** [comment]
1.9.8で対策入れてみました。修正されたかご確認ください。

**Comment by milkboy77** [comment]
![image](https://github.com/bdunderscore/modular-avatar/assets/106000834/8fecef0a-b653-44b9-8353-6ca193e2bd0e)
Still report that...

Error Message:
```Exception: Segment not found in FreeSegment
nadena.dev.modular_avatar.core.armature_lock.AllocationMap.FreeSegment (nadena.dev.modular_avatar.core.armature_lock.ISegment inputSegment) (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/AllocationMap.cs:117)
nadena.dev.modular_avatar.core.armature_lock.NativeMemoryManager.Free (nadena.dev.modular_avatar.core.armature_lock.ISegment segment) (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/NativeMemoryManager.cs:215)
nadena.dev.modular_avatar.core.armature_lock.ArmatureLockOperator`1[T].RemoveJob (nadena.dev.modular_avatar.core.armature_lock.ArmatureLockJob job) (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/ArmatureLockOperator.cs:230)
nadena.dev.modular_avatar.core.armature_lock.ArmatureLockOperator`1+<>c__DisplayClass41_0[T].<RegisterLock>b__0 () (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/ArmatureLockOperator.cs:169)
nadena.dev.modular_avatar.core.armature_lock.ArmatureLockJob.Dispose () (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/ArmatureLockJob.cs:78)
nadena.dev.modular_avatar.core.armature_lock.ArmatureLockController.RebuildLock () (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/ArmatureLockController.cs:175)
nadena.dev.modular_avatar.core.armature_lock.ArmatureLockController.set_Enabled (System.Boolean value) (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/ArmatureLockController.cs:121)
nadena.dev.modular_avatar.core.ModularAvatarMergeArmature.SetLockMode () (at ./Packages/nadena.dev.modular-avatar/Runtime/ModularAvatarMergeArmature.cs:129)
UnityEditor.EditorApplication.Internal_CallDelayFunctions () (at <347e3e2bef8c4deb82c9790c6e198135>:0)``

**Comment by milkboy77** [comment]
![image](https://github.com/bdunderscore/modular-avatar/assets/106000834/cb842bf1-75e8-410e-bba9-536dac51c818)
Still Report that...

Error Message:
```Exception: Segment not found in FreeSegment
nadena.dev.modular_avatar.core.armature_lock.AllocationMap.FreeSegment (nadena.dev.modular_avatar.core.armature_lock.ISegment inputSegment) (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/AllocationMap.cs:127)
nadena.dev.modular_avatar.core.armature_lock.AllocationMap+Segment.Dispose () (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/AllocationMap.cs:43)
nadena.dev.modular_avatar.core.armature_lock.ArmatureLockOperator`1[T].RemoveJob (nadena.dev.modular_avatar.core.armature_lock.ArmatureLockJob job) (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/ArmatureLockOperator.cs:230)
nadena.dev.modular_avatar.core.armature_lock.ArmatureLockOperator`1+<>c__DisplayClass41_0[T].<RegisterLock>b__0 () (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/ArmatureLockOperator.cs:169)
nadena.dev.modular_avatar.core.armature_lock.ArmatureLockJob.Dispose () (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/ArmatureLockJob.cs:78)
nadena.dev.modular_avatar.core.armature_lock.ArmatureLockController.RebuildLock () (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/ArmatureLockController.cs:175)
nadena.dev.modular_avatar.core.armature_lock.ArmatureLockController.set_Enabled (System.Boolean value) (at ./Packages/nadena.dev.modular-avatar/Runtime/ArmatureAwase/ArmatureLockController.cs:121)
nadena.dev.modular_avatar.core.ModularAvatarMergeArmature.SetLockMode () (at ./Packages/nadena.dev.modular-avatar/Runtime/ModularAvatarMergeArmature.cs:129)
UnityEditor.EditorApplication.Internal_CallDelayFunctions () (at <347e3e2bef8c4deb82c9790c6e198135>:0)
``

**Comment by milkboy77** [comment]
Fixed
