### ISSUE TITLE
VRCF Unlimited Params colliding with MA's error checking

### ISSUE THREAD

**Issue by krista-chan** [bdunderscore/modular-avatar#806]
Due to the recent addition of VRCFury's "Unlimited Params" beta object, the number of parameters during upload can be significantly reduced in comparison to the amount of params at preupload. This is an issue because MA throws an error during the build of the avatar if there are too many params present, before VRCFury manages to actually optimize the amount (see https://imgur.com/a/9CrNk5x).

I'm not completely sure on how this issue can be approached as it's a matter of compatibility, however, I can offer a possible solution:
MA could provide a checkbox that stops a parameter overflow from halting the build process.

I have brought this up in the VRCFury discord server as I'm unsure whether or not this is concretely worth opening an issue on the VRCF GitHub repo – please do let me know if it is.

**Comment by SenkyDragon** [comment]
If MA fails the build due to this error, it should probably happen at the end of NDMF's optimization phase.

**Comment by VictorBrek** [comment]
Same issue

**Comment by bdunderscore** [comment]
Disabling the check for now: https://github.com/bdunderscore/modular-avatar/commit/8d64c63f492c568c31b001c3e986039bd38c9359

I'll re-enable it when I have the infrastructure in place to make things more compatible.

**Comment by Narazaka** [comment]
also IntParameterCompressor https://booth.pm/ja/items/5575099
