### ISSUE TITLE
Enable or Disenabled GameObject cause a big lag

### ISSUE THREAD

**Issue by milkboy77** [bdunderscore/modular-avatar#807]
![image](https://github.com/bdunderscore/modular-avatar/assets/106000834/915dedcf-8507-439c-9e89-1a9d089af45d)
When i Enable or Disenabled GameObject cause a big lag(?

**Comment by milkboy77** [comment]
Especially after unfolding the parameter occupancy calculation

**Comment by bdunderscore** [comment]
Is this an issue only when the parameter view is open?

**Comment by milkboy77** [comment]
> Is this an issue only when the parameter view is open
Expand the View for a while...
Everything Got a big lag

**Comment by milkboy77** [comment]
Expand the View for a while...
Everything Got a big lag

**Comment by bdunderscore** [comment]
Please try again with 1.9.12, I fixed a major bug with the parameter view that would cause this behavior.
