### ISSUE TITLE
アバターのビルド時にInsufficientExecutionStackExceptionエラーが発生する

### ISSUE THREAD

**Issue by snowWolf22** [bdunderscore/modular-avatar#810]
アバターのビルド時にInsufficientExecutionStackExceptionエラーが発生しビルドが出来ません。

## 使用バージョン

Modular Avatarのバージョン: 1.9.10
NDMFのバージョン: 1.4.0

## エラーログ

エラーログのURL: https://gist.github.com/snowWolf22/cad2e87b7aeaefc9c03297e335a93211

## エラーの再現手順
* 使用アバター: [オリジナル3Dモデル「セレスティア」ver1.02](https://booth.pm/ja/items/4035411)
* 使用衣装: [天照の浄衣【対応アバター:萌・セレスティア・桔梗】](https://booth.pm/ja/items/4938397)

1. アバターと衣装の`.unitypackage`をUnityへインポート
2. ヒエラルキーへアバターをドラッグアンドドロップ
3. 衣装をアバターのルートにドラッグアンドドロップ
4. VRCSDKのBuilderタブから`Build & Publish`をクリック
5. エラー表示ウィンドウが表示される
6. 右下のテストビルドを実行
7. 再度エラー発生のためビルドに失敗

**Comment by bdunderscore** [comment]
テストプロジェクトに該当のアバターと衣装を入れてみたけど、再現できませんでした。何もないプロジェクトで再現できますか？
