### ISSUE TITLE
Do not automatically attach Modular Avatar Information.

### ISSUE THREAD

**Issue by sakuraimikoto33** [bdunderscore/modular-avatar#815]
Please add an option to prevent adding Modular Avatar Information to game objects.

I know it can be folded, but I don't think it should be "automatically" attached just by adding a package.

**Comment by bdunderscore** [comment]
One challenge with adding an option is there's a risk that users might turn it off and forget that they've done so (this was a problem with apply on play, to the point where I made the setting reset when the editor was closed). Would limiting this to only be displayed when there is relevant information to show address your concerns?
