### ISSUE TITLE
ExpressionMenuにループが存在するアバターのビルド時にInsufficientExecutionStackExceptionが発生する

### ISSUE THREAD

**Issue by PancakeTorto1se** [bdunderscore/modular-avatar#826]
## 使用バージョン

Unity : 2022.3.6f1
VRCSDK : 3.5.2
Modular Avatar : 1.9.10
NDMF : 1.4.0

## エラーの状況

Modular Avatarの各コンポーネントを付けた衣装などを含んでいない素の状態のアバターで、
ExpressionMenuのSubMenuがループ状態になっているとInsufficientExecutionStackExceptionが発生する。

## エラーの再現手順

最低限のアバターということでSDKについているサンプルアバターを使用します。

1. VCCで適当なアバタープロジェクトを作成する。その際にModular Avatarもインストールする。
1. `Packages/com.vrchat.avatars/Samples/Dynamics/Robot Avatar/Avatar Dynamics Robot Avatar PC.unity` を開く。
1. ヒエラルキーのアバターで`Packages/com.vrchat.avatars/Samples/AV3 Demo Assets/Expressions Menu`に存在する
DefaultExpressionsMenu/Parametersファイルを使用するように設定する。
1. DefaultExpressionsMenuファイルでSub Menuを追加し、移動先のSub Menuに自分自身を設定する。
![image](https://github.com/bdunderscore/modular-avatar/assets/109996943/524ae1c4-c53e-4084-a4b1-1b810fc31de8)
1. 再生モードに入ったり、アバターのビルドを行うと、InsufficientExecutionStackExceptionが発生する。

また、この状態でModular Avatarをアンインストールするとビルド時のエラーは発生しなくなります。
なお、本件と同様のエラーが出るものとして #810 が報告されていますが、
確認した限り、こちらで使用されている衣装のようにMA Menu Installerが付いている衣装の場合はこの不具合は発生しないようです。

## エラーログ

anatawa12様の[Console Log Saver](https://github.com/anatawa12/ConsoleLogSaver)で取得したログを添付します。

[logfile.txt](https://github.com/bdunderscore/modular-avatar/files/14981985/logfile.txt)

## その他

* そもそもExpressionMenuにループが存在するというのが微妙な状態なのでバグかといわれると難しいところですが
メニューをループさせるユースケースもあまり思い浮かばないので、エラーや警告を出すのはありかなと思いました。
(ちなみに、ビルドが通る状態だと実際にVRC上ではExpressionMenuはループされて表示されるようです)

**Comment by bdunderscore** [comment]
詳しい再現手順ありがとうございます！
