### ISSUE TITLE
MA Move IndependentlyはUndo等でコンポーネントが外れるとRedoしてもオブジェクト選択が復活しない

### ISSUE THREAD

**Issue by Sayamame-beans** [bdunderscore/modular-avatar#842]
恐らくオブジェクトの選択はUndoに記録されておらず、Undoでコンポーネントが外れると、Redoでコンポーネントを付け直してもオブジェクト選択がやり直しになってしまいます。

Unity 2022.3.6f1
NDMF 1.4.0
MA 1.9.12

**Comment by bdunderscore** [comment]
うーん・・・Undo.RecordObjectはちゃんと呼び出してるんだけどなぁ・・・

**Comment by bdunderscore** [comment]
そもそも設定を保存してない模様

**Comment by bdunderscore** [comment]
問題は特定できたけど、保存するようにすると 1) 保存形式の変更になる 2) カスタムエディターを回すためにはObjectChangeEventStreamが必要になりそうなので、1.10まで保留です。
