### ISSUE TITLE
Could Modular Parameter Old interface back?

### ISSUE THREAD

**Issue by milkboy77** [bdunderscore/modular-avatar#860]
When i want to change GoGoloco to Modular mode to install, there are lots of parameter.
With the new version of the interface I need to tap on these parameters one by one to change their sync mode and modify their properties, which is quite a hassle. I have also asked friends around me and they have all said that this interface is a bit more cumbersome than the previous one.
I'd like to be able to implement a switch to toggle the new version of the Modular Parameter interface with the old one.
[>w<]
Hope you will accept my comments! ^ ^

**Comment by milkboy77** [comment]
Or just change it back to Old interface(?
TAT

**Comment by bdunderscore** [comment]
![image](https://github.com/user-attachments/assets/e8cb4f6d-0aa8-4fb4-86c6-ebe414430461)
