### ISSUE TITLE
Feature Suggestion: Add an option to remove/overwrite default layers when merging animators

### ISSUE THREAD

**Issue by JLChnToZ** [bdunderscore/modular-avatar#886]
I would like to use Modular Avatar to auto installs animators that overwrites built-in locomotion and gestures, but according to current specification, MA Merge Animator only capable to append animator layers to the existing/built-in ones.

Therefore, I suggests to add a toggle to make an animator be the new base of other animators to be merged, overwriting the exists one.

I think this will be useful to other creators who wants to distribute custom locomotion state machines etc.

**Comment by bdunderscore** [comment]
Duplicate of https://github.com/bdunderscore/modular-avatar/issues/330
