### ISSUE TITLE
PBで動くボーンにScale Adjusterを付けるとPBが動かなくなる

### ISSUE THREAD

**Issue by Narazaka** [bdunderscore/modular-avatar#937]
![image](https://github.com/user-attachments/assets/6140db62-610e-4eac-9099-0213abd344d2)

ScaleProxyなるオブジェクトが付与されるためにmulti childで動かなくなる
Firstにすると回避可能そうだが、原因が分かりづらい

**Comment by bdunderscore** [comment]
https://github.com/bdunderscore/modular-avatar/issues/924 (1.10で修正予定)
