### ISSUE TITLE
`PathMapping.ApplyMappingsToClip` doesn't copy `wrapMode`, `legacy`, `frameRate`, `localBounds` from `originalClip`

### ISSUE THREAD

**Issue by ColorlessColor** [bdunderscore/modular-avatar#949]
https://github.com/bdunderscore/modular-avatar/blob/0806c621c5298fa2ec89d2590e8015f6a84fcf3a/Editor/Animation/PathMappings.cs#L264-L267

Maybe the rvalue should be `originalClip`?

**Comment by bdunderscore** [comment]
Oops. Good catch!
