### ISSUE TITLE
MA Object Toggle 単体だと何も起こらないことは仕様でしょうか？

### ISSUE THREAD

**Issue by ReinaS-64892** [bdunderscore/modular-avatar#963]
まず、MA Shape Changer は、アニメーションなどで何も操作されていない衣装のメッシュに付与し、素体側のシェイプキーをDeleteする挙動(ポリゴンの削除)が動いています。
なので、同じくくりになっている MA Object Toggle でも 衣装のメッシュ(アニメーションなどで全く操作されていない)に付与し、 素体側(下着など)のレンダラーを無効化する(GameObjectの無効化) が可能だと予想したのですが特に動作しません。
どうやらアニメーションは生成されているようでAAOの自動マージから除外されている状態にはなっているようです。

少しいじったところ...MA MenuItem と MA Parameters があった場合動くことは確認しましたが、アニメーションによる制御がない場合 MA Shape Changer とは違って動作しないのは...仕様かバグなのかが気になります！

NDMF - v1.5.0-beta.3
MA - 7d5860654a675086bd5a0aa84597e00763af5ebd

**Comment by bdunderscore** [comment]
詳しく設定を見せてください🙏

**Comment by ReinaS-64892** [comment]
Limeのプレハブをそのまま投げるわけにもいかないのでとりあえず最小構成で再現できたのでそれを投げますね！
内容的にはシリンダーにスフィアの無効化を付けたものになります。
![image](https://github.com/user-attachments/assets/7955244a-5986-46e1-b8a7-96c703235055)
[OT-Test.zip](https://github.com/user-attachments/files/16537281/OT-Test.zip)

**Comment by bdunderscore** [comment]
![image](https://github.com/user-attachments/assets/6f747b66-fd91-4378-aff7-a4977809e016)
たぶん #964 で直ってるかも

**Comment by ReinaS-64892** [comment]
正しく消えてる！いい感じなの！
