### ISSUE TITLE
ScaleAdjusterを使用するとシーンでの非表示が無効になる（1.10.0-beta.1）

### ISSUE THREAD

**Issue by Rerigferl** [bdunderscore/modular-avatar#971]
https://docs.unity3d.com/2021.3/Documentation/Manual/SceneVisibility.html
![image](https://github.com/user-attachments/assets/5efc63a4-939e-40b8-a47a-5ca11192ac21)

**Comment by bdunderscore** [comment]
https://github.com/bdunderscore/ndmf/pull/334 / NDMF 1.5.0-beta.4 で解決済み
