### ISSUE TITLE
[Reactive Component] Object Toggle のみコンポーネント名の末尾が er で終わらない

### ISSUE THREAD

**Issue by nekobako** [bdunderscore/modular-avatar#991]
Material Setter と Shape Changer は末尾が er で終わっているのに対し、Object Toggle だけそうなっていないのが気になりました。
(動作に支障はないです)

**Comment by bdunderscore** [comment]
Object Togglerがなんかごろ悪いので・・・
何か他の提案ありますか？

**Comment by nekobako** [comment]
lilycalInventory の `LI Item Toggler` に特に違和感を持っていなかったのでこちらも `MA Object Toggler` でいいのかなと思っていましたが、英語話者だとごろ悪く感じるということであれば無理に変える必要はないです…！

他のコンポーネントを `MA Material Change` や `MA Blendshape Change` のようにして揃えるのもありかもですが、絶対揃っていないと変というわけでもないので特に気にならないようでしたら Close しちゃってください。

**Comment by bdunderscore** [comment]
表示名は後からでも変更可能なのでこの疑問はいったん保留にします。
