### ISSUE TITLE
[Reactive Component] Shape Changer のみ操作対象ごとにコンポーネントが必要

### ISSUE THREAD

**Issue by nekobako** [bdunderscore/modular-avatar#992]
Object Toggle と Material Setter は操作対象と操作内容のセットをリストで持っているのに対し、Shape Changer だけ操作対象がリストの外にあるのが気になりました。
Shape Changer も他のコンポーネントと同様に複数の対象を操作できれば便利かもと思いました。
(仕様面で何か理由があるのだろうとは思いつつ、念のため起票しました)

**Comment by bdunderscore** [comment]
たしかに、BlendshapeSyncと同様にまとめて設定できたらいいかもとチュートリアルを作りながら思いました 😅
