### ISSUE TITLE
Menu Item のパラメーター名を入力すると一部設定が非表示になる

### ISSUE THREAD

**Issue by nekobako** [bdunderscore/modular-avatar#994]
複数の Toggle で Int 型のパラメーターを切り替えたいとき、複数の Menu Item に同じパラメーター名を設定する必要があるかと思いますが、パラメーター名を設定するとその下の 3 つのチェックボックスが非表示になり確認も変更できなくなります。
この状態で別途 MA Parameters も設定せずにビルドすると、パラメーター名を入力する前に (3 つのチェックボックスが非表示になる前に) 設定した通りに動きますが、これが Inspector 上で判断できないため分かりにくく感じています。

Menu Item のパラメーター名が設定されていても、それが MA Parameters になければ、3 つのチェックボックスは表示したままでよいのではないかと思っています。(「保存する」や「同期する」はどれか一つでもオンになっていれば…等の説明は必要そうですが)

**Comment by bdunderscore** [comment]
![image](https://github.com/user-attachments/assets/a5f794c0-943f-4cce-ac80-e9c327aa886c)
Parametersなどからくる情報を表示するように変更してみます。なお、NDMF側のAPI変更が必要なので今はSavedの表示ができない仕様です。

![image](https://github.com/user-attachments/assets/46971189-1dbc-4461-8645-a2a024da3a62)
異なるパラメーターが複数選択された場合の取り扱い

**Comment by nekobako** [comment]
ありがとうございます。とても分かりやすそうです！

PR のブランチで試していていくつか気になったところがあるので書いておきます。

---

- MA Parameters なし
  - MA Menu Item (パラメーター名: Hoge, パラメーター値: 0)
  - MA Menu Item (パラメーター名: Hoge, パラメーター値: 1)
  - MA Menu Item (パラメーター名: Hoge, パラメーター値: 2)

という構成にしたとき、

- すべての MA Menu Item の「初期設定にする」のシリアライズされた値が false であれば、いずれかの MA Menu Item の「初期設定にする」にチェックを入れることができますが、いずれかの MA Menu Item の「初期設定にする」のシリアライズされた値が true であれば、すべての MA Menu Item の「初期設定にする」のチェックボックスが操作できなくなります。
ただし、複数選択した場合には操作できるようになります。
- すべての MA Menu Item の「同期する」のシリアライズされた値がどうなっていても、すべての MA Menu Item の「同期する」のチェックボックスが操作できなくなります。
ただし、複数選択した場合には操作できるようになります。

期待する挙動は操作できなくならないことです。(多分…)

---

- MA Parameters (パラメーター名: Hoge, パラメーター型: Int, 初期値: 1)
  - MA Menu Item (パラメーター名: Hoge, パラメーター値: 0)
  - MA Menu Item (パラメーター名: Hoge, パラメーター値: 1)
  - MA Menu Item (パラメーター名: Hoge, パラメーター値: 2)
 
という構成にしたとき、

- すべての MA Menu Item の「初期設定にする」のシリアライズされた値が false であれば、「パラメーター値」が MA Parameters の「初期値」と一致する MA Menu Item の「初期設定にする」にチェックが付きますが、いずれかの MA Menu Item の「初期設定にする」のシリアライズされた値が true であれば、それらのうち最後の MA Menu Item の「初期設定にする」にチェックが付きます。
- すべての MA Menu Item の「同期する」のシリアライズされた値が false であれば、すべての MA Menu Item の「同期する」のチェックは MA Parameters の「同期する」のチェックと同じ状態になりますが、いずれかの MA Menu Item の「同期する」のシリアライズされた値が true であれば、すべての MA Menu Item の「同期する」にチェックが付きます。

期待する挙動はシリアライズされた値がどうなっていても MA Parameters 側の設定が反映されることです。
(アバターのプレビューもシリアライズされた値の方が優先されてしまっているかも)

**Comment by bdunderscore** [comment]
フィードバックありがとうございます！
・複数選択の場合は「初期設定にする」項目をディスエーブルします。すべてOFFの場合はOFF表示、そうでないときは混合表記になります。
・複数選択の場合、「保存」「同期」設定はパラメーターが同じかつMA Parametersなどで操作されてない場合操作可能になります。可能な限りMA Parametersなどの設定値を表示します。
